import type { ManorDomain } from '@/types/manor';

export interface KeywordEntry {
  keyword: string;
  weight: number;
}

export const MANOR_KEYWORD_MAP: Array<[ManorDomain, KeywordEntry[]]> = [
  ['legal', [
    { keyword: '合同', weight: 3 },
    { keyword: '违约', weight: 4 },
    { keyword: '诉讼', weight: 5 },
    { keyword: '仲裁', weight: 5 },
    { keyword: '知识产权', weight: 4 },
    { keyword: '侵权', weight: 4 },
    { keyword: '法律', weight: 3 },
    { keyword: '赔偿', weight: 3 },
    { keyword: '索赔', weight: 4 },
    { keyword: '起诉', weight: 5 },
    { keyword: '律师函', weight: 5 },
    { keyword: '判决', weight: 5 },
    { keyword: '法务', weight: 4 },
    { keyword: '保密协议', weight: 5 },
    { keyword: '竞业', weight: 5 },
    { keyword: '合同纠纷', weight: 6 },
    { keyword: '合同争议', weight: 6 },
    { keyword: '拒付', weight: 4 },
    { keyword: '尾款', weight: 3 },
    { keyword: '商业秘密', weight: 5 },
    { keyword: '管辖', weight: 3 },
    { keyword: '诉前', weight: 5 },
    { keyword: '财产保全', weight: 5 },
    { keyword: '法院', weight: 4 },
    { keyword: '法律风险', weight: 6 },
    { keyword: '审查合同', weight: 6 },
    { keyword: '合同审查', weight: 6 },
    { keyword: '供应商合同', weight: 5 },
    { keyword: '条款', weight: 2 },
    { keyword: '乙方', weight: 3 },
    { keyword: '甲方', weight: 3 },
    { keyword: '签约', weight: 3 },
    { keyword: '风险点', weight: 3 },
  ]],
  ['hr', [
    { keyword: '员工', weight: 2 },
    { keyword: '薪资', weight: 2 },
    { keyword: '招聘', weight: 3 },
    { keyword: '绩效', weight: 2 },
    { keyword: '离职', weight: 2 },
    { keyword: '劳务', weight: 2 },
    { keyword: '人事', weight: 2 },
    { keyword: '培训', weight: 2 },
    { keyword: '裁员', weight: 2 },
    { keyword: '晋升', weight: 2 },
    { keyword: '考勤', weight: 2 },
    { keyword: '劳动仲裁', weight: 3 },
    { keyword: '加班费', weight: 2 },
    { keyword: '绩效评估', weight: 4 },
    { keyword: '绩效争议', weight: 5 },
    { keyword: '员工异议', weight: 4 },
    { keyword: '人力资源', weight: 3 },
    { keyword: '年终奖', weight: 3 },
    { keyword: '工资', weight: 2 },
    { keyword: '社保', weight: 2 },
    { keyword: '劳动合同', weight: 4 },
    { keyword: '试用期', weight: 3 },
    { keyword: '辞退', weight: 3 },
    { keyword: '解雇', weight: 3 },
    { keyword: '人才', weight: 1 },
    { keyword: '团队', weight: 1 },
    { keyword: '劳动关系', weight: 4 },
  ]],
  ['finance', [
    { keyword: '财务', weight: 2 },
    { keyword: '预算', weight: 2 },
    { keyword: '现金流', weight: 2 },
    { keyword: '融资', weight: 2 },
    { keyword: '利润', weight: 2 },
    { keyword: '账期', weight: 2 },
    { keyword: '营收', weight: 2 },
    { keyword: '成本', weight: 2 },
    { keyword: '报表', weight: 2 },
    { keyword: '审计', weight: 2 },
    { keyword: '资金', weight: 2 },
    { keyword: '税务', weight: 2 },
    { keyword: '稽查', weight: 2 },
    { keyword: '超支', weight: 4 },
    { keyword: '预算超支', weight: 6 },
    { keyword: '财务管控', weight: 5 },
    { keyword: '研发超支', weight: 5 },
    { keyword: '毛利', weight: 3 },
    { keyword: '毛利率', weight: 3 },
    { keyword: 'ROI', weight: 3 },
    { keyword: '财务分析', weight: 4 },
    { keyword: '财务风险', weight: 4 },
    { keyword: '资金链', weight: 4 },
    { keyword: '盈利', weight: 2 },
    { keyword: '亏损', weight: 3 },
    { keyword: '预算管理', weight: 4 },
    { keyword: '财务预测', weight: 4 },
  ]],
  ['ecommerce', [
    { keyword: '电商', weight: 2 },
    { keyword: '平台', weight: 1 },
    { keyword: 'GMV', weight: 2 },
    { keyword: '退款', weight: 2 },
    { keyword: '店铺', weight: 2 },
    { keyword: '天猫', weight: 3 },
    { keyword: '拼多多', weight: 3 },
    { keyword: '抖音小店', weight: 3 },
    { keyword: '直通车', weight: 3 },
    { keyword: '淘宝', weight: 3 },
    { keyword: '京东', weight: 3 },
    { keyword: '转化率', weight: 2 },
    { keyword: '客单价', weight: 2 },
    { keyword: '复购', weight: 2 },
    { keyword: '退货率', weight: 2 },
    { keyword: '差评', weight: 2 },
    { keyword: '直播', weight: 2 },
  ]],
  ['ops', [
    { keyword: '运维', weight: 2 },
    { keyword: '服务器', weight: 2 },
    { keyword: '部署', weight: 2 },
    { keyword: '容器', weight: 2 },
    { keyword: 'Docker', weight: 3 },
    { keyword: 'K8s', weight: 3 },
    { keyword: '告警', weight: 2 },
    { keyword: '回滚', weight: 2 },
    { keyword: '监控', weight: 2 },
    { keyword: '故障', weight: 2 },
    { keyword: '502', weight: 3 },
    { keyword: '线上问题', weight: 3 },
    { keyword: '服务降级', weight: 3 },
    { keyword: 'CPU', weight: 2 },
    { keyword: '内存泄漏', weight: 3 },
    { keyword: '响应时间', weight: 2 },
    { keyword: '吞吐量', weight: 2 },
    { keyword: 'SLA', weight: 3 },
  ]],
  ['compliance', [
    { keyword: '合规', weight: 2 },
    { keyword: '隐私', weight: 2 },
    { keyword: '监管', weight: 2 },
    { keyword: '数据采集', weight: 2 },
    { keyword: '制度', weight: 1 },
    { keyword: '红线', weight: 2 },
    { keyword: '整改', weight: 2 },
    { keyword: '抽查', weight: 2 },
    { keyword: '合规稽查', weight: 6 },
    { keyword: '数据合规', weight: 5 },
    { keyword: '个人信息保护', weight: 5 },
    { keyword: '个人信息保护稽查', weight: 6 },
    { keyword: '数据处理', weight: 3 },
    { keyword: '等保', weight: 4 },
    { keyword: 'GDPR', weight: 4 },
    { keyword: '数据安全', weight: 3 },
    { keyword: '个人信息', weight: 3 },
    { keyword: '用户授权', weight: 3 },
    { keyword: '数据泄露', weight: 4 },
    { keyword: '风险合规', weight: 4 },
    { keyword: '监管要求', weight: 3 },
    { keyword: '内控', weight: 3 },
  ]],
  ['sales', [
    { keyword: '销售', weight: 2 },
    { keyword: '客户', weight: 1 },
    { keyword: '线索', weight: 2 },
    { keyword: '商机', weight: 2 },
    { keyword: '成交', weight: 2 },
    { keyword: '报价', weight: 2 },
    { keyword: '谈判', weight: 2 },
    { keyword: '大客户', weight: 3 },
    { keyword: '销售目标', weight: 3 },
    { keyword: '业绩', weight: 2 },
    { keyword: '客户流失', weight: 3 },
    { keyword: '复购率', weight: 3 },
    { keyword: 'KPI', weight: 2 },
    { keyword: '渠道', weight: 2 },
    { keyword: '代理商', weight: 3 },
  ]],
  ['marketing', [
    { keyword: '营销', weight: 2 },
    { keyword: '流量', weight: 2 },
    { keyword: 'SEO', weight: 3 },
    { keyword: '转化', weight: 2 },
    { keyword: '内容', weight: 1 },
    { keyword: '表单', weight: 2 },
    { keyword: '落地页', weight: 2 },
    { keyword: '推广', weight: 2 },
    { keyword: '投放', weight: 2 },
    { keyword: '品牌', weight: 1 },
    { keyword: '获客', weight: 3 },
    { keyword: 'ROI 营销', weight: 4 },
    { keyword: '小红书', weight: 3 },
    { keyword: '抖音', weight: 2 },
    { keyword: '私域', weight: 3 },
    { keyword: 'KOL', weight: 3 },
    { keyword: '用户增长', weight: 3 },
  ]],
  ['battery_pack', [
    { keyword: '电池', weight: 2 },
    { keyword: 'Pack', weight: 2 },
    { keyword: '电芯', weight: 3 },
    { keyword: 'BMS', weight: 3 },
    { keyword: '储能', weight: 2 },
    { keyword: 'kWh', weight: 3 },
    { keyword: '锂电', weight: 3 },
    { keyword: '电池组', weight: 3 },
    { keyword: '充放电', weight: 3 },
    { keyword: '循环寿命', weight: 3 },
    { keyword: '热失控', weight: 4 },
    { keyword: '电池安全', weight: 4 },
  ]],
  ['supply-chain', [
    { keyword: '供应链', weight: 2 },
    { keyword: '采购', weight: 2 },
    { keyword: '库存', weight: 2 },
    { keyword: '物流', weight: 2 },
    { keyword: '仓储', weight: 2 },
    { keyword: '供应商', weight: 2 },
    { keyword: '关税', weight: 2 },
    { keyword: '备货', weight: 2 },
    { keyword: '供应商断供', weight: 6 },
    { keyword: '供应链风险', weight: 6 },
    { keyword: '供应链预警', weight: 6 },
    { keyword: '交付延迟', weight: 5 },
    { keyword: '断货', weight: 4 },
    { keyword: '缺货', weight: 3 },
    { keyword: '交货', weight: 3 },
    { keyword: '原材料', weight: 3 },
    { keyword: '货期', weight: 3 },
    { keyword: '产能', weight: 2 },
    { keyword: '外包', weight: 2 },
    { keyword: '工厂', weight: 1 },
  ]],
  ['investment', [
    { keyword: '投资', weight: 2 },
    { keyword: '建仓', weight: 3 },
    { keyword: '仓位', weight: 3 },
    { keyword: '估值', weight: 2 },
    { keyword: '尽调', weight: 3 },
    { keyword: '股票', weight: 2 },
    { keyword: '基金', weight: 2 },
    { keyword: '回撤', weight: 3 },
    { keyword: '止盈', weight: 3 },
    { keyword: 'NVIDIA', weight: 5 },
    { keyword: 'nvidia', weight: 5 },
    { keyword: '英伟达', weight: 5 },
    { keyword: 'A股', weight: 3 },
    { keyword: '港股', weight: 3 },
    { keyword: '美股', weight: 3 },
    { keyword: 'PE', weight: 2 },
    { keyword: 'PEG', weight: 3 },
    { keyword: '市盈率', weight: 3 },
    { keyword: '市值', weight: 2 },
    { keyword: '买入', weight: 3 },
    { keyword: '卖出', weight: 3 },
    { keyword: '配置', weight: 2 },
  ]],
];
