import type { BureauActionIntent, BureauDepartmentCode } from '@/lib/contracts/bureau-page-view';
import type { DepartmentRailTone, DepartmentCommandTone } from '@/lib/contracts/department-page-view';

export type BureauPageSpec = {
  department: BureauDepartmentCode;
  slug: string;
  name: string;
  alias?: string[];
  role: string;
  scope: string;
  userConcern: string;
  pageDisplay: string[];
  backendSupply: string[];
  userActions: string[];
  avoidIllusion: string;
  verdict: string;
  verdictTone: DepartmentRailTone;
  blockedValue: string;
  evidence: string[];
  risks: string[];
  handoffs: Array<{ label: string; target: string; reason: string }>;
};

export const BUREAU_ACTIONS: Array<{
  id: string;
  label: string;
  intent: BureauActionIntent;
  tone: DepartmentCommandTone;
}> = [
  { id: 'request_evidence', label: '要求补证', intent: 'request_evidence', tone: 'amber' },
  { id: 'approve', label: '准奏通过', intent: 'approve', tone: 'green' },
  { id: 'block', label: '拦下风险', intent: 'block', tone: 'red' },
  { id: 'handoff', label: '移交会签', intent: 'handoff', tone: 'blue' },
  { id: 'recheck', label: '设置复查', intent: 'recheck', tone: 'neutral' },
  { id: 'archive', label: '归档留痕', intent: 'archive', tone: 'neutral' },
];

function b(input: BureauPageSpec): BureauPageSpec {
  return input;
}

export const BUREAU_PAGE_SPECS: Record<BureauDepartmentCode, BureauPageSpec[]> = {
  finance: [
    b({ department: 'finance', slug: 'treasury', name: '出纳司', alias: ['国库司', '金库司'], role: '现金安全与付款裁决', scope: '现金余量、回款、付款、账期和资金安全垫。', userConcern: '钱还能撑多久；这笔款现在能不能付；哪些回款没回来，哪些付款会压穿现金流。', pageDisplay: ['今日现金安全', '现金余量、可用天数、最低安全垫', '待付款和待回款', '付款裁决', '已挡下的现金风险'], backendSupply: ['现金余量、可用天数、安全垫', '待付款裁决', '回款、账期、付款依据', '现金流穿透风险', '已拦下的付款'], userActions: ['补现金流证明', '交刑部看合同尾款', '交工部补验收证据', '缓付并设置复查日期'], avoidIllusion: '不要让用户以为系统已经自动付款。现金数字必须标记来源和更新时间。', verdict: '先看现金安全垫，再决定付款是否放行。', verdictTone: 'amber', blockedValue: '替用户拦下可能压穿现金缓冲的付款。', evidence: ['现金流水', '应收回款计划', '付款申请', '合同付款条件', '验收证明'], risks: ['现金流穿透', '无验收付款', '逾期回款未覆盖付款窗口'], handoffs: [{ label: '合同尾款核验', target: '刑部合同审查司', reason: '付款条件不明时先看合同。' }, { label: '验收证据', target: '工部质量司', reason: '未验收不得放款。' }] }),
    b({ department: 'finance', slug: 'budget', name: '预算司', alias: ['度支司'], role: '预算与经营分析', scope: '预算、预测、费用控制和经营分析。', userConcern: '预算该不该批；哪些项目在超支；多个事项同时要钱时先批谁。', pageDisplay: ['预算余额', '预算占用', '预测偏差', '超支项目', '待批预算', '预算裁决', '优先级建议'], backendSupply: ['预算余额和占用率', '待批预算', '预算归属、负责人、现金影响', '超支和无预算事项', '需要交出纳司或审计司的事项'], userActions: ['准批预算', '要求补预算说明', '改为分期释放', '移交审计司复核'], avoidIllusion: '预算司只能展示预算判断，不能承诺最终付款。', verdict: '预算可批与否取决于归属、负责人和现金影响是否清楚。', verdictTone: 'amber', blockedValue: '替用户挡住无预算归属、无负责人和超支推进。', evidence: ['预算科目', '项目负责人', '现金影响', '费用预测', '历史执行偏差'], risks: ['无预算事项', '预算挪用', '现金影响不明'], handoffs: [{ label: '付款能力', target: '出纳司', reason: '预算可批不代表现金可付。' }, { label: '异常预算', target: '审计司', reason: '超支或绕流程需稽核。' }] }),
    b({ department: 'finance', slug: 'pricing-cost', name: '盐铁司', alias: ['价本司'], role: '报价、成本与毛利', scope: '价格合理性、成本拆解、报价偏差和供应价格。', userConcern: '价格是否合理；毛利是不是被压穿；供应或报价有没有异常。', pageDisplay: ['成本拆解', '目标毛利', '报价偏差', '供应商价格对比', '异常价格提醒', '可接受报价区间'], backendSupply: ['毛利率、成本偏差、报价区间', '待核价事项', '采购价、历史价、供应商报价', '低毛利、倒挂、异常折扣', '需要交工部物料司或刑部合同审查司的事项'], userActions: ['要求重报', '锁定成本基准', '移交合同审查', '提交价格特批'], avoidIllusion: '不要把建议报价说成最终成交价，避免越权定价。', verdict: '先核成本和毛利底线，再给报价区间。', verdictTone: 'amber', blockedValue: '替用户挡住毛利倒挂、异常折扣和无依据报价。', evidence: ['采购价', '历史成交价', '供应商报价', '成本拆解', '报价审批'], risks: ['毛利倒挂', '价格战误判', '供应价格异常'], handoffs: [{ label: '供应核价', target: '工部物料司', reason: '供应侧成本需确认。' }, { label: '合同价格条款', target: '刑部合同审查司', reason: '价格承诺进入合同前需审。' }] }),
    b({ department: 'finance', slug: 'financing', name: '融资司', role: '资金缺口与融资方案', scope: '融资需求、资金成本、还款压力和融资红线。', userConcern: '资金缺口多大；融资是否必要；哪种融资成本最低、风险可控。', pageDisplay: ['资金缺口', '融资需求', '资金成本', '可选融资方案', '还款压力', '融资红线'], backendSupply: ['缺口、成本、期限', '融资方案比较', '现金流预测、还款来源、授信情况', '高成本、期限错配、偿付压力', '需要交国库司、审计司或刑部的事项'], userActions: ['发起融资评估', '补还款来源', '移交合同审查', '驳回高风险融资'], avoidIllusion: '融资司只给可行性和风险判断，不代表已完成融资。', verdict: '融资先看缺口真实性和还款来源，再比较成本。', verdictTone: 'blue', blockedValue: '替用户挡住高成本、期限错配和无还款来源融资。', evidence: ['现金流预测', '授信材料', '还款来源', '融资方案', '合同条款'], risks: ['高成本融资', '期限错配', '偿付压力过大'], handoffs: [{ label: '现金口径', target: '国库司', reason: '缺口要和现金计划一致。' }, { label: '融资合同', target: '刑部合同审查司', reason: '融资条款需要法务审。' }] }),
    b({ department: 'finance', slug: 'audit', name: '审计司', alias: ['稽核司'], role: '内控审计与异常稽核', scope: '异常报销、重复付款、缺证费用和流程绕行。', userConcern: '钱花得是否合规；有没有异常报销、重复付款、流程绕行。', pageDisplay: ['异常支出', '重复付款', '缺证费用', '超权限审批', '审计结论', '追责建议'], backendSupply: ['异常金额、异常数量、缺证率', '待稽核事项', '票据、审批链、支付记录', '违规报销、重复支付、无凭证支出', '刑部合规或吏部责任链'], userActions: ['要求补票', '冻结支付', '发起复核', '移交刑部或吏部'], avoidIllusion: '审计结论需要区分疑点和已确认违规。', verdict: '先把疑点、证据和违规结论分开，再决定是否冻结。', verdictTone: 'red', blockedValue: '替用户挡住重复支付、无凭证报销和绕审批支出。', evidence: ['票据', '审批链', '支付记录', '合同依据', '报销说明'], risks: ['重复支付', '无凭证支出', '超权限审批'], handoffs: [{ label: '合规追责', target: '刑部合规稽查司', reason: '违规疑点需合规定性。' }, { label: '责任链', target: '吏部协同司', reason: '需要明确责任人。' }] }),
    b({ department: 'finance', slug: 'accounting', name: '会计司', alias: ['计簿司'], role: '账务、税务与月结', scope: '收入、成本、费用、科目、项目归集和月结。', userConcern: '账有没有记清楚；收入、成本、费用和项目是否能对上。', pageDisplay: ['账务状态', '待入账事项', '科目异常', '项目归集', '月结进度', '缺失凭证'], backendSupply: ['待入账数、缺凭证数、月结进度', '待处理账务', '凭证、科目、项目、合同或付款来源', '错科目、漏记、跨期', '审计司或国库司'], userActions: ['补凭证', '调整科目', '发起月结', '提交审计复核'], avoidIllusion: '会计司展示账是否可入，不展示未经确认的利润结论。', verdict: '凭证、科目和项目归集齐后，账才可入。', verdictTone: 'blue', blockedValue: '替用户挡住错科目、漏记和跨期入账。', evidence: ['凭证', '会计科目', '项目归集', '合同来源', '付款来源'], risks: ['错科目', '漏记', '跨期确认'], handoffs: [{ label: '审计复核', target: '审计司', reason: '异常入账需稽核。' }, { label: '付款核对', target: '国库司', reason: '账款一致性需要确认。' }] }),
    b({ department: 'finance', slug: 'investment', name: '投资司', alias: ['投审司'], role: '投资评审与退出假设', scope: '投资标的、回报测算、风险和退出路径。', userConcern: '这笔投资值不值得做；回报、风险和退出路径是否清楚。', pageDisplay: ['投资标的', '投入规模', '收益测算', '风险清单', '退出假设', '投审建议'], backendSupply: ['投入、预期收益、回收期', '待投审事项', '商业计划、财务预测、尽调材料', '估值过高、退出不清、现金占用', '刑部合同、国库现金、审计尽调'], userActions: ['要求补尽调', '准入下一轮', '驳回投资', '移交合同审查'], avoidIllusion: '投资司不能把预测收益包装成确定收益。', verdict: '投资进入下一轮前，必须补齐尽调和退出假设。', verdictTone: 'amber', blockedValue: '替用户挡住估值过高、现金占用和退出不清的投资。', evidence: ['商业计划', '财务预测', '尽调材料', '退出路径', '合同草案'], risks: ['估值过高', '退出不清', '现金占用'], handoffs: [{ label: '合同审查', target: '刑部合同审查司', reason: '投资条款进入合同前需审。' }, { label: '现金影响', target: '国库司', reason: '投资占用现金需确认。' }] }),
  ],
  ops: [
    b({ department: 'ops', slug: 'sales', name: '报价司', alias: ['销售司'], role: '报价与商机推进', scope: '商机队列、阶段、金额、赢率、报价动作和阻塞点。', userConcern: '哪些机会最该跟；这单能不能赢；报价边界在哪里。', pageDisplay: ['商机队列', '阶段、金额、赢率', '报价动作', '阻塞点', '报价裁决'], backendSupply: ['pipeline、赢率、预计签约', '重点商机', '客户需求、报价、历史沟通', '无决策人、无预算、无下一步', '线索、渠道、刑部合同'], userActions: ['标记推进', '要求补客户证据', '移交合同审查', '放弃低质量商机'], avoidIllusion: '报价司不能只展示 CRM 列表，要给该不该报价和怎么报价的判断。', verdict: '优先推进有预算、决策人和明确下一步的商机。', verdictTone: 'green', blockedValue: '替用户挡住无预算、无决策人和无下一步的低质量商机。', evidence: ['客户需求', '报价记录', '历史沟通', '决策链', '预算信号'], risks: ['无决策人', '无预算', '无下一步'], handoffs: [{ label: '合同审查', target: '刑部合同司', reason: '签约前要审关键条款。' }, { label: '线索来源', target: '线索司', reason: '线索质量需复盘。' }] }),
    b({ department: 'ops', slug: 'marketing', name: '线索司', alias: ['市场司'], role: '线索与投放复盘', scope: '市场活动、线索质量、获客成本和转化路径。', userConcern: '市场活动有没有效果；线索质量怎么样；投入是否值得。', pageDisplay: ['活动表现', '线索数量', '有效线索率', '获客成本', '转化路径', '活动复盘'], backendSupply: ['线索、成本、转化率', '活动复盘和待决策投放', '渠道来源、素材、转化数据', '高成本低转化、虚假线索', '报价司或品牌司'], userActions: ['继续投放', '暂停活动', '交报价司跟进', '要求补复盘'], avoidIllusion: '线索司展示线索质量和投入产出，不是只展示热闹指标。', verdict: '投放是否继续，取决于有效线索率和获客成本。', verdictTone: 'amber', blockedValue: '替用户挡住高成本低转化和虚假线索扩投。', evidence: ['渠道来源', '活动素材', '转化数据', '销售反馈', '成本记录'], risks: ['高成本低转化', '虚假线索', '素材口径偏差'], handoffs: [{ label: '报价跟进', target: '报价司', reason: '有效线索需要进入商机和报价。' }, { label: '品牌素材', target: '礼部品牌司', reason: '素材表达需品牌审。' }] }),
    b({ department: 'ops', slug: 'channel', name: '渠道司', role: '渠道合作、报备与冲突处理', scope: '渠道贡献、质量、冲突、返佣和合作等级。', userConcern: '哪些渠道靠谱；渠道冲突怎么处理；返佣和价格是否安全。', pageDisplay: ['渠道贡献', '渠道质量', '冲突案件', '返佣风险', '渠道等级', '合作建议'], backendSupply: ['渠道成交、转化、冲突数', '渠道事项', '报备、合同、成交归属', '撞单、虚假报备、返佣异常', '销售司、刑部合同、审计司'], userActions: ['确认归属', '冻结返佣', '要求补报备', '调整渠道等级'], avoidIllusion: '渠道司必须解释为什么归这个渠道，不能只给结果。', verdict: '渠道归属必须有报备、合同和成交证据。', verdictTone: 'amber', blockedValue: '替用户挡住撞单、虚假报备和返佣异常。', evidence: ['渠道报备', '合作合同', '成交归属', '返佣规则', '客户沟通'], risks: ['撞单', '虚假报备', '返佣异常'], handoffs: [{ label: '成交归属', target: '销售司', reason: '销售链路需确认。' }, { label: '返佣审计', target: '户部审计司', reason: '异常返佣需稽核。' }] }),
    b({ department: 'ops', slug: 'customer', name: '客户司', role: '客户健康、续约与投诉协同', scope: '客户健康度、续约、投诉、交付问题和关键联系人。', userConcern: '客户是否健康；续约风险在哪里；投诉或交付问题谁处理。', pageDisplay: ['客户健康度', '续约概率', '投诉事项', '服务风险', '关键联系人', '客户动作建议'], backendSupply: ['健康分、续约金额、投诉数', '重点客户', '交付记录、沟通记录、合同状态', '流失、升级投诉、欠款', '工部现场、刑部争议、礼部沟通'], userActions: ['发起客户关怀', '移交现场处理', '触发续约计划', '升级争议处理'], avoidIllusion: '客户司页面要让用户看到客户为什么危险，而不是只给红黄绿灯。', verdict: '客户风险要拆成续约、投诉、交付和欠款四条线。', verdictTone: 'amber', blockedValue: '替用户挡住投诉未闭环、承诺逾期导致的续约流失。', evidence: ['交付记录', '沟通记录', '合同状态', '投诉单', '欠款记录'], risks: ['客户流失', '升级投诉', '欠款扩大'], handoffs: [{ label: '现场问题', target: '工部现场司', reason: '现场证据和处理进度需确认。' }, { label: '争议升级', target: '刑部争议处置司', reason: '争议需要事实链。' }] }),
    b({ department: 'ops', slug: 'competitive-intel', name: '竞情司', role: '竞争对手与输赢原因', scope: '竞品对比、价格战风险、功能差距和竞争策略。', userConcern: '竞争对手是谁；对方怎么打；我们赢在哪里、输在哪里。', pageDisplay: ['竞品对比', '价格战风险', '功能差距', '客户偏好', '竞争策略建议'], backendSupply: ['竞品出现频次、输单原因、价格差', '重点竞争案件', '客户反馈、报价对比、竞品资料', '价格战、功能缺口、品牌劣势', '产品司、销售司、品牌司'], userActions: ['生成竞争话术', '移交产品补能力', '调整报价策略', '记录输单原因'], avoidIllusion: '竞情司不能制造没有证据的竞争结论。', verdict: '竞争判断必须来自客户反馈、报价对比和竞品材料。', verdictTone: 'blue', blockedValue: '替用户挡住无证据的竞品结论和盲目价格战。', evidence: ['客户反馈', '报价对比', '竞品资料', '输单记录', '销售复盘'], risks: ['价格战', '功能缺口', '品牌劣势'], handoffs: [{ label: '能力补齐', target: '工部方案司', reason: '功能缺口需产品判断。' }, { label: '品牌战术', target: '礼部品牌司', reason: '品牌劣势需表达调整。' }] }),
    b({ department: 'ops', slug: 'growth', name: '增长司', role: '漏斗、实验与增长瓶颈', scope: '漏斗转化、增长瓶颈、实验队列和优先级。', userConcern: '增长卡在哪里；哪个环节最值得优化；下一轮实验怎么做。', pageDisplay: ['漏斗转化', '增长瓶颈', '实验队列', '实验结果', '优先级', '增长建议'], backendSupply: ['转化率、留存、增长贡献', '实验队列', '漏斗数据、AB 结果、渠道数据', '样本不足、误判、过度投放', '市场、销售、产品'], userActions: ['发起实验', '停止无效实验', '扩大有效实验', '移交产品优化'], avoidIllusion: '增长司要强调实验置信度，不能把小样本当确定结论。', verdict: '先找漏斗最大瓶颈，再发起可验证实验。', verdictTone: 'blue', blockedValue: '替用户挡住小样本误判和无效实验扩张。', evidence: ['漏斗数据', 'AB 结果', '渠道数据', '用户行为', '销售反馈'], risks: ['样本不足', '误判增长', '过度投放'], handoffs: [{ label: '投放调整', target: '市场司', reason: '渠道实验需市场执行。' }, { label: '产品优化', target: '工部方案司', reason: '体验瓶颈需产品处理。' }] }),
  ],
  personnel: [
    b({ department: 'personnel', slug: 'talent', name: '招聘司', alias: ['选才司'], role: '招聘与候选人匹配', scope: '招聘需求、岗位缺口、候选人匹配和面试进度。', userConcern: '该招谁；候选人是否匹配；缺什么人会影响业务。', pageDisplay: ['招聘需求', '岗位缺口', '候选人匹配', '面试进度', '录用建议'], backendSupply: ['缺口、候选人数、平均周期', '待决策候选人', '简历、面试评价、岗位要求', '能力不匹配、招聘拖延', '薪酬司或制度司'], userActions: ['推进面试', '发 offer', '驳回候选人', '调整岗位画像'], avoidIllusion: '招聘司不能只按关键词匹配，要展示匹配依据。', verdict: '候选人推进必须解释岗位要求、能力证据和风险。', verdictTone: 'blue', blockedValue: '替用户挡住能力不匹配和岗位画像不清的招聘推进。', evidence: ['简历', '面试评价', '岗位要求', '业务缺口', '薪酬范围'], risks: ['能力不匹配', '招聘拖延', '岗位画像模糊'], handoffs: [{ label: '薪酬报价', target: '薪酬司', reason: '发 offer 前需薪酬边界。' }, { label: '岗位制度', target: '制度司', reason: '岗位职责需制度确认。' }] }),
    b({ department: 'personnel', slug: 'labor-relations', name: '劳关司', role: '劳动关系与入离调转续', scope: '合同状态、试用期、离职风险、争议隐患和手续缺口。', userConcern: '劳动关系是否有风险；入离调转续手续是否完整。', pageDisplay: ['合同状态', '试用期', '离职风险', '争议隐患', '手续缺口', '处理建议'], backendSupply: ['待签合同、到期合同、风险员工', '劳关事项', '合同、沟通、审批记录', '违法解除、手续缺失、争议升级', '刑部合规或吏部制度'], userActions: ['补签合同', '发起离职流程', '移交争议处理', '设置续签提醒'], avoidIllusion: '劳关司不能给出超出证据的法律结论，高风险事项要交刑部。', verdict: '手续和证据完整前，不推进高风险劳动关系动作。', verdictTone: 'amber', blockedValue: '替用户挡住违法解除、手续缺失和争议升级。', evidence: ['劳动合同', '沟通记录', '审批记录', '试用期记录', '离职材料'], risks: ['违法解除', '手续缺失', '争议升级'], handoffs: [{ label: '劳动争议', target: '刑部争议处置司', reason: '高风险劳动事项需法务处理。' }, { label: '制度依据', target: '制度司', reason: '流程要按制度执行。' }] }),
    b({ department: 'personnel', slug: 'compensation', name: '薪酬司', role: '薪酬、奖金与公平性', scope: '薪酬区间、预算、调薪、奖金和公平性风险。', userConcern: '薪酬是否公平；预算是否够；奖金和调薪有没有依据。', pageDisplay: ['薪酬区间', '预算占用', '调薪名单', '奖金方案', '公平性风险'], backendSupply: ['薪酬预算、调薪人数、偏离度', '调薪和奖金事项', '绩效、市场薪酬、岗位等级', '倒挂、不公平、预算超支', '度支司和铨叙司'], userActions: ['准批调薪', '要求补绩效依据', '调整方案', '移交预算复核'], avoidIllusion: '薪酬司要展示依据，不能让用户感觉是黑箱分钱。', verdict: '调薪必须同时满足绩效依据、岗位等级和预算边界。', verdictTone: 'amber', blockedValue: '替用户挡住薪酬倒挂、不公平和预算超支。', evidence: ['绩效记录', '市场薪酬', '岗位等级', '预算边界', '调薪历史'], risks: ['薪酬倒挂', '不公平感知', '预算超支'], handoffs: [{ label: '预算复核', target: '户部度支司', reason: '薪酬动作需要预算支持。' }, { label: '职级确认', target: '铨叙司', reason: '岗位等级影响薪酬。' }] }),
    b({ department: 'personnel', slug: 'appointment', name: '任免司', alias: ['铨叙司'], role: '任免、晋升与职级', scope: '职级、任职资格、晋升、调岗和职责匹配。', userConcern: '谁该晋升；谁该调岗；岗位等级和职责是否匹配。', pageDisplay: ['职级', '任职资格', '晋升候选', '调岗建议', '岗位职责偏差'], backendSupply: ['晋升候选、岗位空缺、资格缺口', '任免调转事项', '绩效、任职资格、岗位职责', '越级晋升、职责不清、错配', '薪酬司、制度司、协同司'], userActions: ['发起晋升评审', '调整岗位', '驳回任命', '补资格材料'], avoidIllusion: '任免司页面要说明为什么是这个人，不是只给名单。', verdict: '任免调转要先看资格、绩效和岗位职责匹配。', verdictTone: 'blue', blockedValue: '替用户挡住越级晋升、职责不清和人岗错配。', evidence: ['绩效记录', '任职资格', '岗位职责', '组织编制', '调岗申请'], risks: ['越级晋升', '职责不清', '人岗错配'], handoffs: [{ label: '薪酬联动', target: '薪酬司', reason: '职级变化影响薪酬。' }, { label: '责任协同', target: '协同司', reason: '调岗需明确责任链。' }] }),
    b({ department: 'personnel', slug: 'policy', name: '制度司', role: '人事制度与流程规则', scope: '相关制度、适用条款、制度冲突、流程和例外处理。', userConcern: '规则是什么；这件事按哪条制度办；制度是否冲突或过期。', pageDisplay: ['相关制度', '适用条款', '制度冲突', '流程要求', '例外处理'], backendSupply: ['有效制度、待更新制度、例外数', '制度适用事项', '制度文本、审批链、历史案例', '制度冲突、过期、例外滥用', '刑部合规或相关业务司'], userActions: ['引用制度', '发起制度修订', '申请例外', '移交合规审查'], avoidIllusion: '制度司要给用户可执行的规则，而不是只挂制度全文。', verdict: '制度页要回答按哪条办、缺什么、能不能例外。', verdictTone: 'blue', blockedValue: '替用户挡住过期制度、规则冲突和例外滥用。', evidence: ['制度文本', '审批链', '历史案例', '例外申请', '合规要求'], risks: ['制度冲突', '制度过期', '例外滥用'], handoffs: [{ label: '合规审查', target: '刑部合规稽查司', reason: '制度例外需合规边界。' }, { label: '业务司会签', target: '相关业务司', reason: '制度影响具体业务流程。' }] }),
    b({ department: 'personnel', slug: 'coordination', name: '协同司', alias: ['责任链'], role: '责任链和跨司协同', scope: '责任人、协同链路、卡点、逾期事项和催办建议。', userConcern: '这件事到底谁负责；卡在哪个环节；谁该接下一棒。', pageDisplay: ['责任人', '协同链路', '卡点', '逾期事项', '下一责任司', '催办建议'], backendSupply: ['逾期数、卡点数、跨司事项', '待协同事项', '任务流、审批流、沟通记录', '无人负责、重复处理、职责冲突', '目标司和责任人'], userActions: ['指派责任人', '催办', '移交', '升级处理'], avoidIllusion: '协同司的核心价值是让事情不掉地上。', verdict: '先明确责任人和下一责任司，再推进催办或升级。', verdictTone: 'amber', blockedValue: '替用户挡住无人负责、重复处理和职责冲突。', evidence: ['任务流', '审批流', '沟通记录', '责任人', '交接记录'], risks: ['无人负责', '重复处理', '职责冲突'], handoffs: [{ label: '目标司接办', target: '下一责任司', reason: '需要明确接办方。' }, { label: '责任追踪', target: '相关负责人', reason: '逾期事项需到人。' }] }),
  ],
  gongbu: [
    b({ department: 'gongbu', slug: 'solution', name: '产研司', alias: ['方案司', '产品司'], role: '产品、研发与优先级', scope: '需求清单、方案状态、用户价值、范围边界和优先级。', userConcern: '需求该不该做；方案是否清楚；做完能解决什么问题。', pageDisplay: ['需求清单', '方案状态', '用户价值', '范围边界', '优先级', '方案裁决'], backendSupply: ['需求数、待评审数、优先级', '待定方案', '需求来源、客户价值、成本估算', '范围膨胀、价值不清、资源不足', '技术司、报价司、客户司'], userActions: ['通过方案', '要求补需求', '调整优先级', '移交技术评估'], avoidIllusion: '产研司不能只展示需求池，要给该不该做的产品判断。', verdict: '方案先判断用户价值和范围边界，再进入技术评估。', verdictTone: 'blue', blockedValue: '替用户挡住价值不清、范围膨胀和无资源需求。', evidence: ['需求来源', '客户价值', '成本估算', '范围边界', '业务目标'], risks: ['范围膨胀', '价值不清', '资源不足'], handoffs: [{ label: '技术评估', target: '技术司', reason: '方案可做性需工程判断。' }, { label: '客户价值', target: '客户司', reason: '客户问题要被确认。' }] }),
    b({ department: 'gongbu', slug: 'engineering', name: '技术司', role: '技术可行性与工程风险', scope: '技术可行性、架构风险、研发成本、依赖项和技术债。', userConcern: '技术上能不能做；风险在哪里；需要多少成本。', pageDisplay: ['技术可行性', '架构风险', '研发成本', '依赖项', '技术债', '评审结论'], backendSupply: ['开发量、风险等级、依赖数', '技术评审事项', '方案、代码模块、依赖系统', '不可行、性能、安全、债务', '方案司、质量司、刑部合规'], userActions: ['准入开发', '要求拆分方案', '拒绝高风险实现', '移交质量验证'], avoidIllusion: '技术司要把风险翻译成人话，不让用户读工程细节。', verdict: '技术风险能被拆分和验证时，才准入开发。', verdictTone: 'amber', blockedValue: '替用户挡住不可行方案、性能安全风险和债务失控。', evidence: ['产品方案', '代码模块', '依赖系统', '接口契约', '验收条件'], risks: ['技术不可行', '性能风险', '安全风险', '技术债扩大'], handoffs: [{ label: '质量验证', target: '质量司', reason: '技术实现需要质门。' }, { label: '合规边界', target: '刑部合规稽查司', reason: '安全合规需审。' }] }),
    b({ department: 'gongbu', slug: 'material', name: '物料司', alias: ['供应司'], role: '物料、采购与供应稳定', scope: '物料库存、采购进度、供应商状态、缺料风险和替代方案。', userConcern: '物料是否够；供应是否稳定；采购是否拖交付。', pageDisplay: ['物料库存', '采购进度', '供应商状态', '缺料风险', '替代方案'], backendSupply: ['库存、缺料、到货日期', '采购和缺料事项', '采购单、供应商承诺、历史交付', '断供、延期、成本上涨', '盐铁司、进度司、合同审查'], userActions: ['催交', '换供应商', '发起采购', '移交价格复核'], avoidIllusion: '物料司要展示缺料会影响哪个交付，不能只列库存。', verdict: '物料风险要和交付影响绑定展示。', verdictTone: 'amber', blockedValue: '替用户挡住断供、延期和成本上涨拖垮交付。', evidence: ['采购单', '供应商承诺', '历史交付', '库存记录', '替代清单'], risks: ['断供', '采购延期', '成本上涨'], handoffs: [{ label: '价格复核', target: '户部盐铁司', reason: '供应价格异常需核价。' }, { label: '交付影响', target: '进度司', reason: '缺料影响排期。' }] }),
    b({ department: 'gongbu', slug: 'schedule', name: '进度司', alias: ['制造司'], role: '里程碑、排期与制造推进', scope: '里程碑、当前进度、延期风险、卡点责任人和交付预测。', userConcern: '项目是否按期；卡点是什么；延期会影响谁。', pageDisplay: ['里程碑', '当前进度', '延期风险', '卡点责任人', '交付预测'], backendSupply: ['进度、延期天数、里程碑完成率', '延期和卡点事项', '计划、工单、负责人反馈', '延期、资源冲突、依赖未完成', '现场司、物料司、质量司'], userActions: ['调整排期', '催办责任人', '升级风险', '移交现场处理'], avoidIllusion: '进度司的页面要让用户看到为什么会晚和谁能解。', verdict: '进度判断要落到卡点、责任人和交付影响。', verdictTone: 'amber', blockedValue: '替用户挡住无人处理的延期、资源冲突和依赖未完成。', evidence: ['项目计划', '工单', '负责人反馈', '依赖清单', '交付承诺'], risks: ['延期', '资源冲突', '依赖未完成'], handoffs: [{ label: '缺料影响', target: '物料司', reason: '供应卡点需要物料处理。' }, { label: '验收准备', target: '质量司', reason: '交付前需质量检查。' }] }),
    b({ department: 'gongbu', slug: 'quality', name: '质量司', role: '质量检查与验收裁决', scope: '质量检查、缺陷清单、验收证据、返工建议和质量裁决。', userConcern: '质量是否达标；能不能验收；缺陷会不会影响交付。', pageDisplay: ['质量检查', '缺陷清单', '验收证据', '返工建议', '质量裁决'], backendSupply: ['缺陷数、严重缺陷、通过率', '验收和返工事项', '测试报告、验收单、现场照片', '重大缺陷、证据不足、返工延期', '现场司、承诺司、刑部争议'], userActions: ['准予验收', '要求返工', '补验收证据', '移交争议处理'], avoidIllusion: '质量司不能把未验证展示成已通过。', verdict: '验收必须有证据，重大缺陷未闭环前不能放行。', verdictTone: 'red', blockedValue: '替用户挡住未验证验收、重大缺陷和证据不足交付。', evidence: ['测试报告', '验收单', '现场照片', '缺陷记录', '客户确认'], risks: ['重大缺陷', '证据不足', '返工延期'], handoffs: [{ label: '现场证据', target: '现场司', reason: '现场事实需补齐。' }, { label: '争议处理', target: '刑部争议处置司', reason: '客户不认可验收时进入争议。' }] }),
    b({ department: 'gongbu', slug: 'field', name: '现场司', role: '现场事实与客户反馈', scope: '现场事件、客户反馈、处理进度、照片或记录、待协调事项。', userConcern: '现场到底发生了什么；客户问题有没有人处理；证据是否齐。', pageDisplay: ['现场事件', '客户反馈', '处理进度', '照片或记录', '待协调事项'], backendSupply: ['现场事件、待处理、响应时长', '现场工单', '照片、记录、客户确认', '客户升级、证据缺失、安全问题', '质量司、客户司、争议处置司'], userActions: ['派单', '补现场证据', '升级处理', '交质量复核'], avoidIllusion: '现场司要把碎片反馈整理成可判断事实。', verdict: '现场反馈要先形成事实链，再交质量或争议处理。', verdictTone: 'amber', blockedValue: '替用户挡住证据缺失、客户升级和现场安全问题。', evidence: ['现场照片', '处理记录', '客户确认', '工单', '沟通记录'], risks: ['客户升级', '证据缺失', '现场安全问题'], handoffs: [{ label: '质量复核', target: '质量司', reason: '现场事实需要质门判断。' }, { label: '客户协同', target: '兵部客户司', reason: '客户情绪和续约风险需处理。' }] }),
    b({ department: 'gongbu', slug: 'commitment', name: '承诺司', role: '客户承诺与兑现计划', scope: '承诺清单、兑现状态、承诺来源、责任人、越权风险和兑现计划。', userConcern: '对客户承诺了什么；能不能兑现；哪些承诺有越权风险。', pageDisplay: ['承诺清单', '兑现状态', '承诺来源', '责任人', '越权风险', '兑现计划'], backendSupply: ['承诺数、逾期数、高风险承诺', '待兑现承诺', '合同、沟通记录、审批记录', '越权承诺、无法兑现、口头承诺无证据', '刑部合同、客户司、进度司'], userActions: ['确认承诺', '修订承诺', '移交合同审查', '设置兑现计划'], avoidIllusion: '承诺司要防止销售、交付、客服各说各话。', verdict: '承诺必须有来源、责任人和兑现计划，越权承诺先拦下。', verdictTone: 'red', blockedValue: '替用户挡住越权承诺、无法兑现和口头无证承诺。', evidence: ['合同', '沟通记录', '审批记录', '责任人', '兑现计划'], risks: ['越权承诺', '无法兑现', '口头承诺无证据'], handoffs: [{ label: '合同承诺', target: '刑部合同审查司', reason: '承诺写入合同前需审。' }, { label: '客户沟通', target: '礼部客户沟通司', reason: '修订承诺需要统一口径。' }] }),
  ],
  legal: [
    b({ department: 'legal', slug: 'contract-review', name: '合同司', alias: ['合同审查司'], role: '合同条款与签署门禁', scope: '合同风险、关键条款、缺失条款、模板偏离和修改建议。', userConcern: '合同能不能签；哪些条款有坑；哪些承诺不能写。', pageDisplay: ['合同风险', '关键条款', '缺失条款', '偏离模板', '审查结论', '修改建议'], backendSupply: ['风险条款、缺失条款、模板偏离', '待审合同', '合同文本、报价、承诺、审批记录', '付款、违约、交付、授权风险', '报价司、承诺司、出纳司'], userActions: ['要求改条款', '准许签署', '退回补证', '移交授权核查'], avoidIllusion: '合同司必须展示为什么不能签，而不是只给拒绝。', verdict: '合同能否签，先看付款、违约、交付和授权条款。', verdictTone: 'red', blockedValue: '替用户挡住高风险条款、缺失条款和越权承诺写入合同。', evidence: ['合同文本', '报价', '客户承诺', '审批记录', '授权规则'], risks: ['付款风险', '违约风险', '交付风险', '授权风险'], handoffs: [{ label: '承诺核查', target: '工部承诺司', reason: '合同承诺需兑现能力。' }, { label: '付款能力', target: '户部出纳司', reason: '付款条款影响现金。' }] }),
    b({ department: 'legal', slug: 'compliance', name: '合规稽查司', role: '合规规则与整改', scope: '合规事项、触发规则、风险等级、整改要求和稽查结论。', userConcern: '这件事是否合法合规；有没有红线；谁需要负责。', pageDisplay: ['合规事项', '触发规则', '风险等级', '整改要求', '稽查结论'], backendSupply: ['合规风险、待整改、逾期整改', '稽查事项', '制度、记录、审批、外部要求', '红线、违规、监管风险', '审计司、制度司、责任链'], userActions: ['发起整改', '冻结动作', '移交追责', '申请例外'], avoidIllusion: '合规稽查司要区分提示、警告和禁止。', verdict: '触碰红线的动作先冻结，再补整改和责任链。', verdictTone: 'red', blockedValue: '替用户挡住违规动作、监管风险和逾期整改。', evidence: ['制度规则', '审批记录', '外部要求', '整改材料', '操作记录'], risks: ['合规红线', '违规事实', '监管风险'], handoffs: [{ label: '审计稽核', target: '户部审计司', reason: '资金和流程疑点需审计。' }, { label: '责任链', target: '吏部协同司', reason: '整改要落实到人。' }] }),
    b({ department: 'legal', slug: 'risk-control', name: '风控司', role: '整体风险评分与控制措施', scope: '风险评分、风险来源、控制措施、风险趋势和准入建议。', userConcern: '这件事整体风险多大；能不能继续推进；需要什么风控措施。', pageDisplay: ['风险评分', '风险来源', '控制措施', '风险趋势', '准入或拦截建议'], backendSupply: ['风险分、趋势、风险项', '待风控事项', '客户、合同、财务、履约证据', '信用、付款、交付、法律风险', '合同审查、国库、客户司'], userActions: ['准入', '加控制条件', '暂停推进', '移交专项审查'], avoidIllusion: '风控司要解释风险来源，不能只给神秘分数。', verdict: '风险可控才准入，不可控则加条件或暂停。', verdictTone: 'amber', blockedValue: '替用户挡住无控制措施的高风险推进。', evidence: ['客户资料', '合同条款', '财务证据', '履约记录', '历史风险'], risks: ['信用风险', '付款风险', '交付风险', '法律风险'], handoffs: [{ label: '合同专项', target: '合同审查司', reason: '合同风险需专项审。' }, { label: '客户风险', target: '兵部客户司', reason: '客户健康影响风险。' }] }),
    b({ department: 'legal', slug: 'authorization', name: '缺证核查司', alias: ['授权司'], role: '证据完整与授权链', scope: '缺失材料、授权链、审批状态、越权提示和可继续条件。', userConcern: '证据齐不齐；谁有权批准；现在能不能进入下一步。', pageDisplay: ['缺失材料', '授权链', '审批状态', '越权提示', '可继续条件'], backendSupply: ['缺证数、授权缺口、待审批', '缺证事项', '材料清单、审批记录、授权规则', '无证推进、越权批准、材料失真', '相关业务司'], userActions: ['补证', '申请授权', '退回发起人', '准入下一步'], avoidIllusion: '缺证核查司的价值是让流程在证据齐之前停住。', verdict: '证据和授权齐之前，流程不得继续推进。', verdictTone: 'red', blockedValue: '替用户挡住无证推进、越权批准和材料失真。', evidence: ['材料清单', '审批记录', '授权规则', '发起说明', '业务证据'], risks: ['无证推进', '越权批准', '材料失真'], handoffs: [{ label: '业务补证', target: '相关业务司', reason: '证据由业务侧补齐。' }, { label: '合规核验', target: '合规稽查司', reason: '授权边界需合规确认。' }] }),
    b({ department: 'legal', slug: 'dispute', name: '争议处置司', role: '争议事实链与处置策略', scope: '争议事实、双方诉求、证据强弱、处理策略和升级建议。', userConcern: '争议怎么解决；我们站不站得住；要不要升级法律处理。', pageDisplay: ['争议事实', '双方诉求', '证据强弱', '处理策略', '和解或升级建议'], backendSupply: ['争议金额、证据完整度、处理时长', '争议案件', '合同、沟通、现场、验收证据', '败诉、赔付、客户升级', '客户司、现场司、合同审查'], userActions: ['发起和解', '补证', '升级法务', '归档结案'], avoidIllusion: '争议处置司要围绕事实链，不要直接替用户下最终法律结论。', verdict: '争议先补事实链，再决定和解、升级或归档。', verdictTone: 'amber', blockedValue: '替用户挡住证据薄弱下的冲动升级或错误承诺。', evidence: ['合同', '沟通记录', '现场证据', '验收证据', '双方诉求'], risks: ['败诉风险', '赔付风险', '客户升级'], handoffs: [{ label: '客户协同', target: '兵部客户司', reason: '争议影响客户关系。' }, { label: '现场补证', target: '工部现场司', reason: '现场事实要补齐。' }] }),
    b({ department: 'legal', slug: 'ip', name: '知识产权司', role: 'IP 权属、授权与侵权风险', scope: 'IP 资产、授权状态、侵权风险、相似内容和保护建议。', userConcern: '这个内容、方案或技术有没有侵权风险；我们的资产有没有被保护。', pageDisplay: ['IP 资产', '授权状态', '侵权风险', '相似内容', '保护建议'], backendSupply: ['资产数、授权缺口、风险项', 'IP 审查事项', '作品、代码、素材、授权文件', '未授权、抄袭、权属不清', '内容司、技术司、合同审查'], userActions: ['补授权', '下架内容', '申请登记', '移交合同审查'], avoidIllusion: '知识产权司不能把相似直接说成侵权，要保留审查层级。', verdict: '相似、未授权和权属不清要分层处理。', verdictTone: 'amber', blockedValue: '替用户挡住未授权发布、权属不清和疑似抄袭。', evidence: ['作品', '代码', '素材', '授权文件', '权属证明'], risks: ['未授权', '疑似抄袭', '权属不清'], handoffs: [{ label: '内容下架', target: '礼部内容司', reason: '内容风险需发布侧处理。' }, { label: '技术权属', target: '工部技术司', reason: '代码和方案权属需工程补证。' }] }),
    b({ department: 'legal', slug: 'legal-policy', name: '制度司', role: '法律制度、整改与豁免', scope: '适用规则、处罚风险、整改路径、豁免条件和制度建议。', userConcern: '这件事按哪条法律或制度处理；有没有处罚、整改或豁免路径。', pageDisplay: ['适用规则', '处罚风险', '整改路径', '豁免条件', '制度建议'], backendSupply: ['适用规则、整改事项、处罚风险', '制度适用事项', '规则文本、案例、审批记录', '处罚、无依据、规则冲突', '合规稽查、吏部制度、业务司'], userActions: ['引用规则', '发起整改', '申请豁免', '移交合规'], avoidIllusion: '刑部制度司要服务裁决，不是做制度库入口。', verdict: '制度要服务本次裁决，明确规则、整改和豁免路径。', verdictTone: 'blue', blockedValue: '替用户挡住无依据处理、规则冲突和处罚风险。', evidence: ['规则文本', '历史案例', '审批记录', '整改材料', '豁免依据'], risks: ['处罚风险', '规则无依据', '规则冲突'], handoffs: [{ label: '合规执行', target: '合规稽查司', reason: '整改需要合规推进。' }, { label: '人事制度', target: '吏部制度司', reason: '涉及人事规则需会签。' }] }),
  ],
  market: [
    b({ department: 'market', slug: 'brand', name: '品牌司', role: '品牌表达与资产一致性', scope: '品牌表达、视觉资产、语气一致性、品牌风险和推荐改法。', userConcern: '对外表达是否符合品牌；品牌资产是否一致；会不会伤害认知。', pageDisplay: ['品牌表达', '视觉资产', '语气一致性', '品牌风险', '推荐改法'], backendSupply: ['待审素材、品牌偏离、资产覆盖', '品牌审查事项', '素材、品牌规范、历史案例', '误导、低质、不一致', '内容司、公关司、知识产权司'], userActions: ['通过素材', '要求修改', '移交 IP 审查', '沉淀品牌资产'], avoidIllusion: '品牌司要说明哪里不符合，不能只说不高级。', verdict: '品牌审查要指出偏离点和可执行改法。', verdictTone: 'blue', blockedValue: '替用户挡住误导表达、低质素材和品牌不一致。', evidence: ['素材', '品牌规范', '历史案例', '视觉资产', '发布渠道'], risks: ['误导表达', '低质素材', '品牌不一致'], handoffs: [{ label: 'IP 审查', target: '刑部知识产权司', reason: '素材权属需审。' }, { label: '内容修改', target: '内容司', reason: '改法需要内容侧执行。' }] }),
    b({ department: 'market', slug: 'pr', name: '公关司', role: '舆情、事实核查与回应口径', scope: '舆情事件、影响范围、回应口径、媒体或客户反馈和升级建议。', userConcern: '舆情有没有风险；对外回应怎么说；是否需要升级。', pageDisplay: ['舆情事件', '影响范围', '回应口径', '媒体或客户反馈', '升级建议'], backendSupply: ['舆情热度、风险等级、响应时长', '公关事件', '舆情截图、沟通记录、事实材料', '扩散、误回应、承诺过度', '法务、客户司、品牌司'], userActions: ['发布回应', '要求补事实', '升级危机处理', '移交法务审查'], avoidIllusion: '公关司必须先核事实，再出话术。', verdict: '事实未核清前，不发布强回应。', verdictTone: 'red', blockedValue: '替用户挡住误回应、承诺过度和舆情扩散。', evidence: ['舆情截图', '沟通记录', '事实材料', '媒体反馈', '客户反馈'], risks: ['舆情扩散', '误回应', '承诺过度'], handoffs: [{ label: '法务审查', target: '刑部合规稽查司', reason: '回应口径需合法合规。' }, { label: '客户侧处理', target: '兵部客户司', reason: '客户反馈需同步处理。' }] }),
    b({ department: 'market', slug: 'customer-comms', name: '客户沟通司', role: '客户话术与沟通边界', scope: '沟通对象、沟通目标、建议话术、禁用话术、客户情绪和关注点。', userConcern: '该怎么跟客户说；哪些话不能说；客户现在最在意什么。', pageDisplay: ['沟通对象', '沟通目标', '建议话术', '禁用话术', '客户情绪和关注点'], backendSupply: ['待沟通客户、升级风险、响应时长', '沟通事项', '客户记录、合同、交付状态', '误承诺、激化冲突、信息不一致', '客户司、承诺司、争议处置'], userActions: ['生成话术', '发送沟通', '转交客户经理', '升级争议'], avoidIllusion: '客户沟通司要帮用户说清楚，但不能替业务做无法兑现的承诺。', verdict: '话术要和合同、交付状态、客户关注点一致。', verdictTone: 'amber', blockedValue: '替用户挡住误承诺、激化冲突和信息不一致。', evidence: ['客户记录', '合同状态', '交付状态', '历史沟通', '客户情绪'], risks: ['误承诺', '激化冲突', '信息不一致'], handoffs: [{ label: '客户经理', target: '兵部客户司', reason: '客户关系动作需客户司承接。' }, { label: '争议升级', target: '刑部争议处置司', reason: '争议话术需要法务事实链。' }] }),
    b({ department: 'market', slug: 'content', name: '内容司', role: '内容质量、事实和发布门禁', scope: '内容草稿、适用渠道、质量评分、事实校验、风险提示和修改建议。', userConcern: '内容能不能发；是否准确、有价值、无风险；要怎么改。', pageDisplay: ['内容草稿', '适用渠道', '质量评分', '事实校验', '风险提示', '修改建议'], backendSupply: ['待审内容、通过率、风险项', '内容审查事项', '素材来源、事实依据、品牌规范', '虚假宣传、侵权、口径不一致', '品牌司、IP 司、公关司'], userActions: ['发布', '退回修改', '补事实来源', '移交品牌或 IP 审查'], avoidIllusion: '内容司不要只给润色，要给能不能发布的判断。', verdict: '内容发布前必须过事实、品牌和权属三道门。', verdictTone: 'amber', blockedValue: '替用户挡住虚假宣传、侵权和口径不一致发布。', evidence: ['素材来源', '事实依据', '品牌规范', '授权文件', '发布渠道'], risks: ['虚假宣传', '侵权', '口径不一致'], handoffs: [{ label: '品牌审查', target: '品牌司', reason: '内容表达需品牌一致。' }, { label: 'IP 审查', target: '刑部知识产权司', reason: '素材权属需确认。' }] }),
    b({ department: 'market', slug: 'government-enterprise', name: '政企司', role: '政企合作与合规边界', scope: '政企事项、合作对象、材料清单、合规边界和跟进计划。', userConcern: '政企合作是否合规；关系维护要注意什么；哪些材料要准备。', pageDisplay: ['政企事项', '合作对象', '材料清单', '合规边界', '跟进计划'], backendSupply: ['待跟进事项、材料缺口、风险等级', '政企合作事项', '资质、沟通记录、政策要求', '不合规承诺、材料不足、流程缺失', '合规稽查、品牌司、合同审查'], userActions: ['补材料', '发起拜访', '移交合规', '归档记录'], avoidIllusion: '政企司要特别强调边界，避免不合规承诺。', verdict: '政企动作先看材料和合规边界，再安排跟进。', verdictTone: 'amber', blockedValue: '替用户挡住不合规承诺、材料不足和流程缺失。', evidence: ['资质材料', '沟通记录', '政策要求', '合同草案', '审批记录'], risks: ['不合规承诺', '材料不足', '流程缺失'], handoffs: [{ label: '合规边界', target: '刑部合规稽查司', reason: '政企事项需合规先行。' }, { label: '合同审查', target: '刑部合同审查司', reason: '合作条款需审。' }] }),
    b({ department: 'market', slug: 'experience', name: '体验司', role: '用户反馈与体验优先级', scope: '体验问题、用户反馈、影响范围、优先级、优化建议和验证结果。', userConcern: '用户体验哪里不好；哪些问题最影响转化、满意度或续约。', pageDisplay: ['体验问题', '用户反馈', '影响范围', '优先级', '优化建议', '验证结果'], backendSupply: ['反馈数、影响用户、满意度', '体验问题', '反馈、行为数据、访谈记录', '体验恶化、流失、投诉升级', '产品司、客户司、质量司'], userActions: ['发起优化', '移交产品', '验证修复', '关闭问题'], avoidIllusion: '体验司要把用户反馈变成可执行优先级，而不是只做意见箱。', verdict: '体验问题要按影响范围、业务影响和修复成本排序。', verdictTone: 'blue', blockedValue: '替用户挡住反馈堆积、体验恶化和投诉升级。', evidence: ['用户反馈', '行为数据', '访谈记录', '满意度', '修复结果'], risks: ['体验恶化', '客户流失', '投诉升级'], handoffs: [{ label: '产品优化', target: '工部方案司', reason: '体验问题要转产品方案。' }, { label: '客户风险', target: '兵部客户司', reason: '体验问题影响续约和满意度。' }] }),
  ],
};

export function getBureauPageSpecs(department: BureauDepartmentCode): BureauPageSpec[] {
  return BUREAU_PAGE_SPECS[department] ?? [];
}

export function getBureauSpecBySlug(department: BureauDepartmentCode, slug: string): BureauPageSpec | null {
  const specs = getBureauPageSpecs(department);
  const bureauMatch = /^bureau-(\d+)$/.exec(slug);
  if (bureauMatch) return specs[Number(bureauMatch[1]) - 1] ?? null;
  return specs.find((item) => item.slug === slug) ?? null;
}

export function getBureauCanonicalSlug(department: BureauDepartmentCode, slug: string): string | null {
  const spec = getBureauSpecBySlug(department, slug);
  if (!spec) return null;
  const index = getBureauPageSpecs(department).indexOf(spec);
  return index >= 0 ? `bureau-${index + 1}` : spec.slug;
}
