export const STUDY_OFFICIALS = {
  libu: {
    name: '吏部尚书',
    title: 'Ministry of Personnel',
    avatar: '吏',
    summary: '负责组织编制、职责重整与人力结构判断。',
    dossier: ['当前组织编制是否支撑治理推进', '哪些角色职责出现重叠', '这轮议题是否需要新增责任人'],
    prompts: ['现在最该增援哪支队伍？', '哪些职责正在互相打架？', '这轮调整谁该背书？'],
    notes: ['批：先收职责，再谈扩编。', '批：高优先级议题需要明确主责人。'],
    logs: ['辰时召见：要求先看组织瓶颈。', '申时复命：建议先清边界再加人。'],
    risk: 'medium',
  },
  hubu: {
    name: '户部尚书',
    title: 'Ministry of Revenue',
    avatar: '户',
    summary: '负责营收推进、预算占用、回款预测与 ROI 判断。',
    dossier: ['高价值线索与回款预测', '预算投放与 ROI 审视', '本周经营动作优先级'],
    prompts: ['先保增长还是先保现金流？', '哪些议题最影响回款进度？', '当前投入是否值得继续加码？'],
    notes: ['批：先稳现金流，再谈扩投。', '批：高价值线索可放行，低置信度动作暂缓。'],
    logs: ['巳时入见：先呈预算占用与回款预测。', '午后复命：建议优先保高分线索回款，不宜盲目扩投。'],
    risk: 'high',
  },
  libu_rites: {
    name: '礼部尚书',
    title: 'Ministry of Rites',
    avatar: '礼',
    summary: '负责品牌口径、高层表达与对外叙事定调。',
    dossier: ['品牌语气是否统一', '路演话术是否越界', '治理与销售叙事是否对齐'],
    prompts: ['这次对外说法会不会过度承诺？', '哪句话该收紧？', '如何让品牌和事实一致？'],
    notes: ['批：先收口径，再发言。'],
    logs: ['早朝请示：需统一外部叙事。'],
    risk: 'medium',
  },
  bingbu: {
    name: '兵部尚书',
    title: 'Ministry of War',
    avatar: '兵',
    summary: '负责竞对攻防、阵地选择与市场切入判断。',
    dossier: ['竞对最近动作', '主战场与侧翼机会', '当前攻守节奏'],
    prompts: ['先抢哪个阵地？', '当前最大威胁是什么？', '哪里最容易打出主动权？'],
    notes: ['批：先查敌情，再定攻守。'],
    logs: ['晨朝请见：竞对已出现跟进动作。', '申时批示：优先稳守主阵地，再做侧翼试探。'],
    risk: 'high',
  },
  xingbu: {
    name: '刑部尚书',
    title: 'Ministry of Justice',
    avatar: '刑',
    summary: '负责制度边界、合规风险与流程问责点。',
    dossier: ['当前合规边界', '制度缺口与问责点', '高风险议题会签结果'],
    prompts: ['最大的合规风险是什么？', '这条链路哪里最危险？', '现在该批还是该压？'],
    notes: ['批：先补边界，再批执行。'],
    logs: ['早间会签：当前需补合规边界说明。', '晚课结案：未补齐前不宜直接放量执行。'],
    risk: 'critical',
  },
  gongbu: {
    name: '工部尚书',
    title: 'Ministry of Works',
    avatar: '工',
    summary: '负责产品能力、工程质量与交付节奏。',
    dossier: ['产品链路是否顺滑', '当前技术债与性能负担', '交付节奏是否稳固'],
    prompts: ['先提体验还是先补稳定性？', '当前最大技术瓶颈是什么？', '这版上线隐患在哪里？'],
    notes: ['批：先保稳定，再做花。'],
    logs: ['晚间召见：要求先清技术债再扩功能。'],
    risk: 'medium',
  },
} as const;

export type StudyOfficialCode = keyof typeof STUDY_OFFICIALS;
