import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync, spawn } from 'node:child_process';
import { createHash } from 'node:crypto';
import { chmodSync, existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { createTask } from '../../scripts/harness-task.mjs';
import { processIdentity } from '../../scripts/lib/control-plane-db.mjs';
import { acquireResource, releaseResource } from '../../scripts/lib/resource-lock.mjs';
import { activateBuild, buildCandidate, inspectActiveBuild, rollbackBuild } from './lib/immutable-build-manager.mjs';
import { captureProcessIdentity, processIdentityAlive } from './lib/process-identity.mjs';

process.env.NODE_ENV='test';process.env.CHAOTANG_CONTROL_PLANE_TEST_ADAPTER='1';
const git=(cwd,args)=>execFileSync('git',args,{cwd,encoding:'utf8'}).trim();
function fixture(){const root=mkdtempSync(join(tmpdir(),'s5-build-'));git(root,['init','-q']);git(root,['config','user.email','s5@test']);git(root,['config','user.name','S5']);mkdirSync(join(root,'frontend'),{recursive:true});writeFileSync(join(root,'frontend','source'),'v1');writeFileSync(join(root,'frontend','next.config.ts'),'export default {};\n');git(root,['add','.']);git(root,['commit','-qm','base']);writeFileSync(join(root,'.git','info','exclude'),'.s5-runtime/\n');const databasePath=join(root,'.s5-runtime','control.sqlite3'),taskId='task-s5',owner='builder',buildRoot=join(root,'.s5-runtime','builds'),active=join(root,'.s5-runtime','active');createTask({task_id:taskId,title:'s5',owner,risk:'high',write_paths:['frontend'],read_paths:[],dependencies:[],worktree:'.worktrees/task-s5',resources:['build:frontend-production'],expires_at:new Date(Date.now()+60000).toISOString(),metadata:{approved_base_sha:git(root,['rev-parse','HEAD'])}},{cwd:root,databasePath});const identity=processIdentity(process.cwd()),lock=acquireResource({dbPath:databasePath,key:'build:frontend-production',holder:{owner,taskId,pid:identity.pid,pgid:identity.pgid,cwd:identity.cwd,worktree:root,commit:git(root,['rev-parse','HEAD']),command:'s5-test',nonce:identity.nonce,hostId:identity.host_id,bootId:identity.boot_id,pidNamespace:identity.pid_namespace,startTicks:identity.start_ticks,protectedPaths:[buildRoot,active]},ttlMs:60000});return{root,databasePath,taskId,owner,buildRoot,active,lock,cleanup(){try{releaseResource({dbPath:databasePath,key:lock.key,fencingEpoch:lock.fencingEpoch,nonce:lock.nonce});}catch{}try{execFileSync('chmod',['-R','u+w',root]);}catch{}rmSync(root,{recursive:true,force:true});}};}
function artifact(next,label='good'){mkdirSync(join(next,'static','chunks'),{recursive:true});writeFileSync(join(next,'BUILD_ID'),label);writeFileSync(join(next,'build-manifest.json'),'{}');writeFileSync(join(next,'routes-manifest.json'),'{}');writeFileSync(join(next,'static','chunks',`${label}.js`),label);}
const options=(f,releaseId,runner)=>({cwd:f.root,frontendRoot:join(f.root,'frontend'),buildRoot:f.buildRoot,activePointer:f.active,releaseId,databasePath:f.databasePath,lock:{key:f.lock.key,fencingEpoch:f.lock.fencingEpoch,nonce:f.lock.nonce},command:['fake-build'],env:{NEXT_PUBLIC_API_MODE:'real'},runner});

test('interrupted and half builds never replace active and failed candidate is precisely removed',async()=>{const f=fixture();try{const first=await buildCandidate(options(f,'r1',async({nextDir})=>artifact(nextDir,'one')));activateBuild({...options(f,'r1'),manifest:first.manifest});const before=readFileSync(f.active,'utf8');await assert.rejects(()=>buildCandidate(options(f,'r2',async({nextDir})=>{mkdirSync(nextDir,{recursive:true});writeFileSync(join(nextDir,'BUILD_ID'),'half');throw new Error('interrupt');})),/interrupt/);assert.equal(readFileSync(f.active,'utf8'),before);assert.equal(existsSync(join(f.buildRoot,'.candidate-r2')),false);}finally{f.cleanup();}});
test('old chunk, pointer tamper and runtime artifact mutation stop closed',async()=>{const f=fixture();try{const built=await buildCandidate(options(f,'r1',async({nextDir})=>artifact(nextDir,'one')));activateBuild({...options(f,'r1'),manifest:built.manifest});assert.equal(inspectActiveBuild({cwd:f.root,buildRoot:f.buildRoot,activePointer:f.active}).release_id,'r1');chmodSync(join(f.buildRoot,'r1','next','static','chunks','one.js'),0o644);writeFileSync(join(f.buildRoot,'r1','next','static','chunks','one.js'),'old');assert.throws(()=>inspectActiveBuild({cwd:f.root,buildRoot:f.buildRoot,activePointer:f.active}),/digest|read-only/);rmSync(f.active);symlinkSync(join(f.root,'frontend'),f.active);assert.throws(()=>inspectActiveBuild({cwd:f.root,buildRoot:f.buildRoot,activePointer:f.active}),/pointer|build/);}finally{f.cleanup();}});
test('rollback selects only a verified immutable build and dirty/cross-worktree builds are rejected',async()=>{const f=fixture();try{const a=await buildCandidate(options(f,'r1',async({nextDir})=>artifact(nextDir,'one')));activateBuild({...options(f,'r1'),manifest:a.manifest});const b=await buildCandidate(options(f,'r2',async({nextDir})=>artifact(nextDir,'two')));activateBuild({...options(f,'r2'),manifest:b.manifest});rollbackBuild({...options(f,'r1')});assert.equal(inspectActiveBuild({cwd:f.root,buildRoot:f.buildRoot,activePointer:f.active}).release_id,'r1');writeFileSync(join(f.root,'frontend','source'),'dirty');await assert.rejects(()=>buildCandidate(options(f,'r3',async({nextDir})=>artifact(nextDir))),/dirty/);await assert.rejects(()=>buildCandidate({...options(f,'r4',async({nextDir})=>artifact(nextDir)),frontendRoot:mkdtempSync(join(tmpdir(),'foreign-'))}),/worktree|repository/);}finally{f.cleanup();}});
test('concurrent build with stale fencing credential is rejected',async()=>{const f=fixture();try{await assert.rejects(()=>buildCandidate({...options(f,'r1',async({nextDir})=>artifact(nextDir)),lock:{key:f.lock.key,fencingEpoch:f.lock.fencingEpoch+1,nonce:f.lock.nonce}}),/fencing|lock/);}finally{f.cleanup();}});
test('runner-created source dirt rejects publication after build',async()=>{const f=fixture();try{await assert.rejects(()=>buildCandidate(options(f,'dirty-after',async({nextDir})=>{artifact(nextDir);writeFileSync(join(f.root,'frontend','source'),'mutated');})),/dirtied worktree/);assert.equal(existsSync(join(f.buildRoot,'dirty-after')),false);assert.equal(existsSync(join(f.buildRoot,'.candidate-dirty-after')),false);}finally{f.cleanup();}});
test('same fenced owner cannot run two candidate builds concurrently',async()=>{const f=fixture();let releaseFirst;const gate=new Promise(resolve=>{releaseFirst=resolve;});try{const first=buildCandidate(options(f,'r1',async({nextDir})=>{await gate;artifact(nextDir,'one');}));await new Promise(resolve=>setTimeout(resolve,25));await assert.rejects(()=>buildCandidate(options(f,'r2',async({nextDir})=>artifact(nextDir,'two'))),/concurrent build/);releaseFirst();await first;}finally{releaseFirst?.();f.cleanup();}});
test('dead activation sentinel is audited/recovered while corrupt sentinel fails closed',async()=>{const f=fixture();try{const built=await buildCandidate(options(f,'r1',async({nextDir})=>artifact(nextDir,'one'))),dead={...processIdentity(process.cwd()),pid:99999999,pgid:99999999,start_ticks:1};writeFileSync(join(f.buildRoot,'.activation.lock'),JSON.stringify({schema_version:1,lock_key:f.lock.key,fencing_epoch:f.lock.fencingEpoch,holder:dead}));activateBuild({...options(f,'r1'),manifest:built.manifest});assert.equal(inspectActiveBuild({cwd:f.root,buildRoot:f.buildRoot,activePointer:f.active}).release_id,'r1');writeFileSync(join(f.buildRoot,'.activation.lock'),'{}');assert.throws(()=>activateBuild({...options(f,'r1'),manifest:built.manifest}),/activation lock invalid/);}finally{f.cleanup();}});
test('runtime identity remains pinned to concrete build after active switches',async()=>{const f=fixture();try{const a=await buildCandidate(options(f,'r1',async({nextDir})=>artifact(nextDir,'one')));activateBuild({...options(f,'r1'),manifest:a.manifest});const running=inspectActiveBuild({cwd:f.root,buildRoot:f.buildRoot,activePointer:f.active});const b=await buildCandidate(options(f,'r2',async({nextDir})=>artifact(nextDir,'two')));activateBuild({...options(f,'r2'),manifest:b.manifest});assert.equal(running.runtime_dir,join(f.buildRoot,'r1','next'));assert.equal(inspectActiveBuild({cwd:f.root,buildRoot:f.buildRoot,activePointer:f.active}).runtime_dir,join(f.buildRoot,'r2','next'));}finally{f.cleanup();}});
test('process identity detects PID metadata mismatch for precise stop',async()=>{const cwd=mkdtempSync(join(tmpdir(),'s5-process-')),child=spawn('setsid',['sleep','30'],{cwd});try{await new Promise(resolve=>setTimeout(resolve,20));const identity=captureProcessIdentity(child.pid,cwd);assert.equal(processIdentityAlive(identity),true);assert.equal(processIdentityAlive({...identity,start_ticks:identity.start_ticks+1}),false);process.kill(-identity.pgid,'SIGTERM');await new Promise(resolve=>child.once('close',resolve));assert.equal(processIdentityAlive(identity),false);}finally{child.kill();rmSync(cwd,{recursive:true,force:true});}});
test('stale operation identity is recovered but malformed paths and live operations fail closed',async()=>{const f=fixture(),commitment=createHash('sha256').update(f.lock.nonce).digest('hex'),base={schema_version:1,lock_key:f.lock.key,fencing_epoch:f.lock.fencingEpoch,nonce_commitment:commitment};try{const current=processIdentity(process.cwd()),dead={...current,pid:99999999,pgid:99999999,start_ticks:1};mkdirSync(join(f.buildRoot,'.candidate-dead','next'),{recursive:true});writeFileSync(join(f.buildRoot,'.build-operation.json'),JSON.stringify({...base,release_id:'dead',candidate:join(f.buildRoot,'.candidate-dead'),holder:dead}));await buildCandidate(options(f,'recovered',async({nextDir})=>artifact(nextDir,'recovered')));assert.equal(existsSync(join(f.buildRoot,'.candidate-dead')),false);writeFileSync(join(f.buildRoot,'.build-operation.json'),JSON.stringify({...base,release_id:'recovered',candidate:join(f.buildRoot,'recovered'),holder:dead}));await assert.rejects(()=>buildCandidate(options(f,'blocked-path',async({nextDir})=>artifact(nextDir))),/schema invalid/);assert.equal(existsSync(join(f.buildRoot,'recovered')),true);rmSync(join(f.buildRoot,'.build-operation.json'));writeFileSync(join(f.buildRoot,'.build-operation.json'),JSON.stringify({...base,release_id:'live',candidate:join(f.buildRoot,'.candidate-live'),holder:current}));await assert.rejects(()=>buildCandidate(options(f,'blocked',async({nextDir})=>artifact(nextDir))),/concurrent build/);}finally{f.cleanup();}});
test('public snapshot is immutable and included in artifact identity',async()=>{const f=fixture();try{mkdirSync(join(f.root,'frontend','public'));writeFileSync(join(f.root,'frontend','public','version.txt'),'one');git(f.root,['add','.']);git(f.root,['commit','-qm','public']);const built=await buildCandidate({...options(f,'public1',async({nextDir})=>artifact(nextDir,'one')),expectedCommit:git(f.root,['rev-parse','HEAD'])});activateBuild({...options(f,'public1'),manifest:built.manifest});const copy=join(f.buildRoot,'public1','public','version.txt');assert.equal(readFileSync(copy,'utf8'),'one');chmodSync(copy,0o644);writeFileSync(copy,'tampered');assert.throws(()=>inspectActiveBuild({cwd:f.root,buildRoot:f.buildRoot,activePointer:f.active}),/digest|read-only/);}finally{f.cleanup();}});
test('runtime next config is copied read-only and included in artifact identity',async()=>{const f=fixture();try{const built=await buildCandidate(options(f,'config1',async({nextDir})=>artifact(nextDir,'one')));activateBuild({...options(f,'config1'),manifest:built.manifest});const config=join(f.buildRoot,'config1','next.config.ts');assert.equal(readFileSync(config,'utf8'),'export default {};\n');chmodSync(config,0o644);writeFileSync(config,'export default {distDir:"wrong"};\n');assert.throws(()=>inspectActiveBuild({cwd:f.root,buildRoot:f.buildRoot,activePointer:f.active}),/digest|read-only/);}finally{f.cleanup();}});
test('50 interrupted candidates never publish a half active build',async()=>{const f=fixture();try{const good=await buildCandidate(options(f,'stable',async({nextDir})=>artifact(nextDir,'stable')));activateBuild({...options(f,'stable'),manifest:good.manifest});for(let i=0;i<50;i++){await assert.rejects(()=>buildCandidate(options(f,`fault-${i}`,async({nextDir})=>{mkdirSync(nextDir,{recursive:true});writeFileSync(join(nextDir,'BUILD_ID'),'half');throw new Error('fault injection');})),/fault injection/);assert.equal(inspectActiveBuild({cwd:f.root,buildRoot:f.buildRoot,activePointer:f.active}).release_id,'stable');assert.equal(existsSync(join(f.buildRoot,`.candidate-fault-${i}`)),false);}}finally{f.cleanup();}});
