"""Authoritative Runtime Skill declaration for one bureau."""

from app.agents.runtime_skills.roles.bureaus.skill_spec import (
    BureauMethod,
    BureauRuntimeSkillSpec,
    BureauToolPolicySpec,
)
from app.agents.runtime_skills.tool_models import ToolName

__all__ = ("SKILL",)

SKILL: BureauRuntimeSkillSpec = BureauRuntimeSkillSpec(
    department="兵部",
    bureau="竞情司",
    agent_id="bingbu-competition",
    skill_id="analyze-competitive-position",
    method=BureauMethod(
        data_requirements=(
            "竞品功能、价格、渠道与公开来源",
            "输赢记录、客户反馈和比较口径",
        ),
        analysis_procedure=(
            "验证竞品信息来源及时点",
            "按一致口径比较能力与价格",
            "归因输赢并评估价格战情景",
        ),
        required_findings=(
            "竞争差距与输赢原因",
            "价格战和错误定位风险",
        ),
        forbidden_actions=(
            "不得使用非法取得的竞品信息",
            "不得把推测包装为竞品事实",
        ),
    ),
    tool_policy=BureauToolPolicySpec(
        policy_id="bureau.bingbu.competition.tools",
        version="1.0.0",
        agent_id="bingbu-competition",
        allowed_tools=(
            ToolName.REQUEST_EVIDENCE,
            ToolName.READ_APPROVED_MATERIALS,
            ToolName.INSPECT_APPROVED_DATA,
            ToolName.COMPUTE_ANALYSIS,
        ),
        allowed_data_domains=("commercial.competition",),
        tool_operations=(
            (
                ToolName.REQUEST_EVIDENCE,
                ("request_fact_slots",),
            ),
            (
                ToolName.READ_APPROVED_MATERIALS,
                (
                    "read_summary",
                    "lookup_section",
                ),
            ),
            (
                ToolName.INSPECT_APPROVED_DATA,
                (
                    "filter",
                    "aggregate",
                    "compare",
                    "top_n",
                ),
            ),
            (
                ToolName.COMPUTE_ANALYSIS,
                (
                    "share",
                    "trend",
                    "threshold",
                ),
            ),
        ),
        tool_argument_constraints=(
            (
                ToolName.REQUEST_EVIDENCE,
                (
                    (
                        "allowed_domains",
                        ("commercial.competition",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        False,
                    ),
                    (
                        "allowed_fields",
                        ("commercial.competition.competitor_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("commercial.competition.market_segment",),
                    ),
                    (
                        "allowed_metrics",
                        ("commercial.competition.win_loss_rate",),
                    ),
                ),
            ),
            (
                ToolName.READ_APPROVED_MATERIALS,
                (
                    (
                        "allowed_domains",
                        ("commercial.competition",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("commercial.competition.competitor_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("commercial.competition.market_segment",),
                    ),
                    (
                        "allowed_metrics",
                        ("commercial.competition.win_loss_rate",),
                    ),
                ),
            ),
            (
                ToolName.INSPECT_APPROVED_DATA,
                (
                    (
                        "allowed_domains",
                        ("commercial.competition",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("commercial.competition.competitor_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("commercial.competition.market_segment",),
                    ),
                    (
                        "allowed_metrics",
                        ("commercial.competition.win_loss_rate",),
                    ),
                ),
            ),
            (
                ToolName.COMPUTE_ANALYSIS,
                (
                    (
                        "allowed_domains",
                        ("commercial.competition",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("commercial.competition.competitor_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("commercial.competition.market_segment",),
                    ),
                    (
                        "allowed_metrics",
                        ("commercial.competition.win_loss_rate",),
                    ),
                ),
            ),
        ),
        required_data_refs=(
            "case",
            "decree",
        ),
        max_tool_calls=4,
        max_tool_rounds=2,
        max_result_rows=200,
        max_result_bytes=262144,
    ),
)
