"""Authoritative Runtime Skill declaration for one bureau."""

from app.agents.runtime_skills.roles.bureaus.skill_spec import (
    BureauMethod,
    BureauRuntimeSkillSpec,
    BureauToolPolicySpec,
)
from app.agents.runtime_skills.tool_models import ToolName

__all__ = ("SKILL",)

SKILL: BureauRuntimeSkillSpec = BureauRuntimeSkillSpec(
    department="兵部",
    bureau="增长司",
    agent_id="bingbu-growth",
    skill_id="analyze-growth-funnel",
    method=BureauMethod(
        data_requirements=(
            "全漏斗事件、基线和分群数据",
            "实验假设、样本量、成本与结果",
        ),
        analysis_procedure=(
            "校验漏斗定义与数据质量",
            "定位转化瓶颈和关键分群",
            "按影响、成本和证据排列实验",
        ),
        required_findings=(
            "漏斗损失和增长瓶颈",
            "实验优先级与护栏指标",
        ),
        forbidden_actions=(
            "不得把相关性宣称为因果",
            "不得绕过实验审批或用户保护",
        ),
    ),
    tool_policy=BureauToolPolicySpec(
        policy_id="bureau.bingbu.growth.tools",
        version="1.0.0",
        agent_id="bingbu-growth",
        allowed_tools=(
            ToolName.READ_APPROVED_MATERIALS,
            ToolName.INSPECT_APPROVED_DATA,
            ToolName.COMPUTE_ANALYSIS,
        ),
        allowed_data_domains=("commercial.growth",),
        tool_operations=(
            (
                ToolName.READ_APPROVED_MATERIALS,
                (
                    "read_summary",
                    "lookup_section",
                ),
            ),
            (
                ToolName.INSPECT_APPROVED_DATA,
                (
                    "filter",
                    "aggregate",
                    "compare",
                    "top_n",
                ),
            ),
            (
                ToolName.COMPUTE_ANALYSIS,
                (
                    "percentage",
                    "share",
                    "trend",
                ),
            ),
        ),
        tool_argument_constraints=(
            (
                ToolName.READ_APPROVED_MATERIALS,
                (
                    (
                        "allowed_domains",
                        ("commercial.growth",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("commercial.growth.experiment_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("commercial.growth.cohort",),
                    ),
                    (
                        "allowed_metrics",
                        ("commercial.growth.uplift_rate",),
                    ),
                ),
            ),
            (
                ToolName.INSPECT_APPROVED_DATA,
                (
                    (
                        "allowed_domains",
                        ("commercial.growth",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("commercial.growth.experiment_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("commercial.growth.cohort",),
                    ),
                    (
                        "allowed_metrics",
                        ("commercial.growth.uplift_rate",),
                    ),
                ),
            ),
            (
                ToolName.COMPUTE_ANALYSIS,
                (
                    (
                        "allowed_domains",
                        ("commercial.growth",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("commercial.growth.experiment_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("commercial.growth.cohort",),
                    ),
                    (
                        "allowed_metrics",
                        ("commercial.growth.uplift_rate",),
                    ),
                ),
            ),
        ),
        required_data_refs=(
            "case",
            "decree",
        ),
        max_tool_calls=4,
        max_tool_rounds=2,
        max_result_rows=200,
        max_result_bytes=262144,
    ),
)
