"""Authoritative Runtime Skill declaration for one bureau."""

from app.agents.runtime_skills.roles.bureaus.skill_spec import (
    BureauMethod,
    BureauRuntimeSkillSpec,
    BureauToolPolicySpec,
)
from app.agents.runtime_skills.tool_models import ToolName

__all__ = ("SKILL",)

SKILL: BureauRuntimeSkillSpec = BureauRuntimeSkillSpec(
    department="兵部",
    bureau="客户司",
    agent_id="bingbu-customers",
    skill_id="analyze-customer-health",
    method=BureauMethod(
        data_requirements=(
            "合同、使用、交付和回款状态",
            "投诉、续约计划与关键联系人记录",
        ),
        analysis_procedure=(
            "汇总客户健康信号",
            "识别投诉、交付与续约关联",
            "制定责任到人的挽回动作",
        ),
        required_findings=(
            "客户健康与流失信号",
            "续约障碍和关系风险",
        ),
        forbidden_actions=(
            "不得隐藏有效投诉或交付失败",
            "不得作出未经批准的补偿承诺",
        ),
    ),
    tool_policy=BureauToolPolicySpec(
        policy_id="bureau.bingbu.customers.tools",
        version="1.0.0",
        agent_id="bingbu-customers",
        allowed_tools=(
            ToolName.READ_APPROVED_MATERIALS,
            ToolName.INSPECT_APPROVED_DATA,
            ToolName.COMPUTE_ANALYSIS,
        ),
        allowed_data_domains=("commercial.customers",),
        tool_operations=(
            (
                ToolName.READ_APPROVED_MATERIALS,
                (
                    "read_summary",
                    "lookup_section",
                ),
            ),
            (
                ToolName.INSPECT_APPROVED_DATA,
                (
                    "filter",
                    "aggregate",
                    "compare",
                    "top_n",
                ),
            ),
            (
                ToolName.COMPUTE_ANALYSIS,
                (
                    "percentage",
                    "share",
                    "trend",
                ),
            ),
        ),
        tool_argument_constraints=(
            (
                ToolName.READ_APPROVED_MATERIALS,
                (
                    (
                        "allowed_domains",
                        ("commercial.customers",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("commercial.customers.customer_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("commercial.customers.health_band",),
                    ),
                    (
                        "allowed_metrics",
                        ("commercial.customers.retention_rate",),
                    ),
                ),
            ),
            (
                ToolName.INSPECT_APPROVED_DATA,
                (
                    (
                        "allowed_domains",
                        ("commercial.customers",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("commercial.customers.customer_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("commercial.customers.health_band",),
                    ),
                    (
                        "allowed_metrics",
                        ("commercial.customers.retention_rate",),
                    ),
                ),
            ),
            (
                ToolName.COMPUTE_ANALYSIS,
                (
                    (
                        "allowed_domains",
                        ("commercial.customers",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("commercial.customers.customer_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("commercial.customers.health_band",),
                    ),
                    (
                        "allowed_metrics",
                        ("commercial.customers.retention_rate",),
                    ),
                ),
            ),
        ),
        required_data_refs=(
            "case",
            "decree",
        ),
        max_tool_calls=4,
        max_tool_rounds=2,
        max_result_rows=200,
        max_result_bytes=262144,
    ),
)
