"""Authoritative Runtime Skill declaration for one bureau."""

from app.agents.runtime_skills.roles.bureaus.skill_spec import (
    BureauMethod,
    BureauRuntimeSkillSpec,
    BureauToolPolicySpec,
)
from app.agents.runtime_skills.tool_models import ToolName

__all__ = ("SKILL",)

SKILL: BureauRuntimeSkillSpec = BureauRuntimeSkillSpec(
    department="兵部",
    bureau="渠道司",
    agent_id="bingbu-channels",
    skill_id="analyze-channel-performance",
    method=BureauMethod(
        data_requirements=(
            "渠道协议、报备记录与区域规则",
            "成交归属、返佣计算和冲突记录",
        ),
        analysis_procedure=(
            "核验报备时点与协议资格",
            "追溯成交归属和返佣依据",
            "识别渠道冲突并提出处置顺序",
        ),
        required_findings=(
            "成交归属与返佣差异",
            "渠道冲突和伙伴影响",
        ),
        forbidden_actions=(
            "不得篡改报备时间或归属证据",
            "不得承诺返佣或终止渠道",
        ),
    ),
    tool_policy=BureauToolPolicySpec(
        policy_id="bureau.bingbu.channels.tools",
        version="1.0.0",
        agent_id="bingbu-channels",
        allowed_tools=(
            ToolName.READ_APPROVED_MATERIALS,
            ToolName.INSPECT_APPROVED_DATA,
            ToolName.COMPUTE_ANALYSIS,
        ),
        allowed_data_domains=("commercial.channels",),
        tool_operations=(
            (
                ToolName.READ_APPROVED_MATERIALS,
                (
                    "read_summary",
                    "lookup_section",
                ),
            ),
            (
                ToolName.INSPECT_APPROVED_DATA,
                (
                    "filter",
                    "aggregate",
                    "compare",
                    "top_n",
                ),
            ),
            (
                ToolName.COMPUTE_ANALYSIS,
                (
                    "percentage",
                    "share",
                    "trend",
                ),
            ),
        ),
        tool_argument_constraints=(
            (
                ToolName.READ_APPROVED_MATERIALS,
                (
                    (
                        "allowed_domains",
                        ("commercial.channels",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("commercial.channels.channel_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("commercial.channels.region",),
                    ),
                    (
                        "allowed_metrics",
                        ("commercial.channels.attributed_revenue",),
                    ),
                ),
            ),
            (
                ToolName.INSPECT_APPROVED_DATA,
                (
                    (
                        "allowed_domains",
                        ("commercial.channels",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("commercial.channels.channel_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("commercial.channels.region",),
                    ),
                    (
                        "allowed_metrics",
                        ("commercial.channels.attributed_revenue",),
                    ),
                ),
            ),
            (
                ToolName.COMPUTE_ANALYSIS,
                (
                    (
                        "allowed_domains",
                        ("commercial.channels",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("commercial.channels.channel_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("commercial.channels.region",),
                    ),
                    (
                        "allowed_metrics",
                        ("commercial.channels.attributed_revenue",),
                    ),
                ),
            ),
        ),
        required_data_refs=(
            "case",
            "decree",
        ),
        max_tool_calls=4,
        max_tool_rounds=2,
        max_result_rows=200,
        max_result_bytes=262144,
    ),
)
