"""Authoritative Runtime Skill declaration for one bureau."""

from app.agents.runtime_skills.roles.bureaus.skill_spec import (
    BureauMethod,
    BureauRuntimeSkillSpec,
    BureauToolPolicySpec,
)
from app.agents.runtime_skills.tool_models import ToolName

__all__ = ("SKILL",)

SKILL: BureauRuntimeSkillSpec = BureauRuntimeSkillSpec(
    department="兵部",
    bureau="报价司",
    agent_id="bingbu-sales-opportunity",
    skill_id="analyze-sales-opportunity",
    method=BureauMethod(
        data_requirements=(
            "商机阶段、客户需求与决策链",
            "报价版本、竞标节点和历史赢率",
        ),
        analysis_procedure=(
            "核验商机阶段和关键关系",
            "分析报价动作、阻塞点与赢率",
            "制定下一步动作和退出条件",
        ),
        required_findings=(
            "成交阻塞与赢率驱动",
            "报价时机和推进风险",
        ),
        forbidden_actions=(
            "不得伪造客户意向或赢率",
            "不得未经批准发送报价或承诺",
        ),
    ),
    tool_policy=BureauToolPolicySpec(
        policy_id="bureau.bingbu.sales_opportunity.tools",
        version="1.0.0",
        agent_id="bingbu-sales-opportunity",
        allowed_tools=(
            ToolName.READ_APPROVED_MATERIALS,
            ToolName.INSPECT_APPROVED_DATA,
            ToolName.COMPUTE_ANALYSIS,
        ),
        allowed_data_domains=("commercial.opportunity",),
        tool_operations=(
            (
                ToolName.READ_APPROVED_MATERIALS,
                (
                    "read_summary",
                    "lookup_section",
                ),
            ),
            (
                ToolName.INSPECT_APPROVED_DATA,
                (
                    "filter",
                    "aggregate",
                    "compare",
                    "top_n",
                ),
            ),
            (
                ToolName.COMPUTE_ANALYSIS,
                (
                    "percentage",
                    "share",
                    "trend",
                ),
            ),
        ),
        tool_argument_constraints=(
            (
                ToolName.READ_APPROVED_MATERIALS,
                (
                    (
                        "allowed_domains",
                        ("commercial.opportunity",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("commercial.opportunity.opportunity_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("commercial.opportunity.sales_stage",),
                    ),
                    (
                        "allowed_metrics",
                        ("commercial.opportunity.win_rate",),
                    ),
                ),
            ),
            (
                ToolName.INSPECT_APPROVED_DATA,
                (
                    (
                        "allowed_domains",
                        ("commercial.opportunity",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("commercial.opportunity.opportunity_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("commercial.opportunity.sales_stage",),
                    ),
                    (
                        "allowed_metrics",
                        ("commercial.opportunity.win_rate",),
                    ),
                ),
            ),
            (
                ToolName.COMPUTE_ANALYSIS,
                (
                    (
                        "allowed_domains",
                        ("commercial.opportunity",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("commercial.opportunity.opportunity_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("commercial.opportunity.sales_stage",),
                    ),
                    (
                        "allowed_metrics",
                        ("commercial.opportunity.win_rate",),
                    ),
                ),
            ),
        ),
        required_data_refs=(
            "case",
            "decree",
        ),
        max_tool_calls=4,
        max_tool_rounds=2,
        max_result_rows=200,
        max_result_bytes=262144,
    ),
)
