"""Authoritative Runtime Skill declaration for one bureau."""

from app.agents.runtime_skills.roles.bureaus.skill_spec import (
    BureauMethod,
    BureauRuntimeSkillSpec,
    BureauToolPolicySpec,
)
from app.agents.runtime_skills.tool_models import ToolName

__all__ = ("SKILL",)

SKILL: BureauRuntimeSkillSpec = BureauRuntimeSkillSpec(
    department="兵部",
    bureau="线索司",
    agent_id="bingbu-leads",
    skill_id="analyze-lead-acquisition",
    method=BureauMethod(
        data_requirements=(
            "活动、渠道、线索来源与成本",
            "线索评分、转化阶段和归因规则",
        ),
        analysis_procedure=(
            "校验来源和归因口径",
            "分析质量、获客成本与阶段转化",
            "识别低效投放并形成实验建议",
        ),
        required_findings=(
            "线索质量与获客成本",
            "归因偏差和投放浪费",
        ),
        forbidden_actions=(
            "不得用重复线索夸大获客量",
            "不得自动调整或购买投放",
        ),
    ),
    tool_policy=BureauToolPolicySpec(
        policy_id="bureau.bingbu.leads.tools",
        version="1.0.0",
        agent_id="bingbu-leads",
        allowed_tools=(
            ToolName.READ_APPROVED_MATERIALS,
            ToolName.INSPECT_APPROVED_DATA,
            ToolName.COMPUTE_ANALYSIS,
        ),
        allowed_data_domains=("commercial.leads",),
        tool_operations=(
            (
                ToolName.READ_APPROVED_MATERIALS,
                (
                    "read_summary",
                    "lookup_section",
                ),
            ),
            (
                ToolName.INSPECT_APPROVED_DATA,
                (
                    "filter",
                    "aggregate",
                    "compare",
                    "top_n",
                ),
            ),
            (
                ToolName.COMPUTE_ANALYSIS,
                (
                    "percentage",
                    "share",
                    "trend",
                ),
            ),
        ),
        tool_argument_constraints=(
            (
                ToolName.READ_APPROVED_MATERIALS,
                (
                    (
                        "allowed_domains",
                        ("commercial.leads",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("commercial.leads.lead_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("commercial.leads.lead_stage",),
                    ),
                    (
                        "allowed_metrics",
                        ("commercial.leads.qualified_rate",),
                    ),
                ),
            ),
            (
                ToolName.INSPECT_APPROVED_DATA,
                (
                    (
                        "allowed_domains",
                        ("commercial.leads",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("commercial.leads.lead_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("commercial.leads.lead_stage",),
                    ),
                    (
                        "allowed_metrics",
                        ("commercial.leads.qualified_rate",),
                    ),
                ),
            ),
            (
                ToolName.COMPUTE_ANALYSIS,
                (
                    (
                        "allowed_domains",
                        ("commercial.leads",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("commercial.leads.lead_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("commercial.leads.lead_stage",),
                    ),
                    (
                        "allowed_metrics",
                        ("commercial.leads.qualified_rate",),
                    ),
                ),
            ),
        ),
        required_data_refs=(
            "case",
            "decree",
        ),
        max_tool_calls=4,
        max_tool_rounds=2,
        max_result_rows=200,
        max_result_bytes=262144,
    ),
)
