"""Authoritative Runtime Skill declaration for one bureau."""

from app.agents.runtime_skills.roles.bureaus.skill_spec import (
    BureauMethod,
    BureauRuntimeSkillSpec,
    BureauToolPolicySpec,
)
from app.agents.runtime_skills.tool_models import ToolName

__all__ = ("SKILL",)

SKILL: BureauRuntimeSkillSpec = BureauRuntimeSkillSpec(
    department="礼部",
    bureau="体验司",
    agent_id="libu-rites-experience",
    skill_id="analyze-user-experience",
    method=BureauMethod(
        data_requirements=(
            "用户反馈、行为路径与工单样本",
            "体验指标、版本信息与验证结果",
        ),
        analysis_procedure=(
            "按旅程阶段聚类体验问题",
            "结合频次、严重度和影响排序",
            "定义优化假设与验证指标",
        ),
        required_findings=(
            "关键体验断点",
            "优先级与验证标准",
        ),
        forbidden_actions=(
            "不得以少量反馈代表全部用户",
            "不得宣称未验证的优化已生效",
        ),
    ),
    tool_policy=BureauToolPolicySpec(
        policy_id="bureau.libu_rites.experience.tools",
        version="1.0.0",
        agent_id="libu-rites-experience",
        allowed_tools=(
            ToolName.READ_APPROVED_MATERIALS,
            ToolName.INSPECT_APPROVED_DATA,
            ToolName.COMPUTE_ANALYSIS,
        ),
        allowed_data_domains=("communications.experience",),
        tool_operations=(
            (
                ToolName.READ_APPROVED_MATERIALS,
                (
                    "read_summary",
                    "lookup_section",
                ),
            ),
            (
                ToolName.INSPECT_APPROVED_DATA,
                (
                    "filter",
                    "aggregate",
                    "compare",
                    "top_n",
                ),
            ),
            (
                ToolName.COMPUTE_ANALYSIS,
                (
                    "percentage",
                    "share",
                    "trend",
                ),
            ),
        ),
        tool_argument_constraints=(
            (
                ToolName.READ_APPROVED_MATERIALS,
                (
                    (
                        "allowed_domains",
                        ("communications.experience",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("communications.experience.journey_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("communications.experience.journey_stage",),
                    ),
                    (
                        "allowed_metrics",
                        ("communications.experience.friction_rate",),
                    ),
                ),
            ),
            (
                ToolName.INSPECT_APPROVED_DATA,
                (
                    (
                        "allowed_domains",
                        ("communications.experience",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("communications.experience.journey_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("communications.experience.journey_stage",),
                    ),
                    (
                        "allowed_metrics",
                        ("communications.experience.friction_rate",),
                    ),
                ),
            ),
            (
                ToolName.COMPUTE_ANALYSIS,
                (
                    (
                        "allowed_domains",
                        ("communications.experience",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("communications.experience.journey_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("communications.experience.journey_stage",),
                    ),
                    (
                        "allowed_metrics",
                        ("communications.experience.friction_rate",),
                    ),
                ),
            ),
        ),
        required_data_refs=(
            "case",
            "decree",
        ),
        max_tool_calls=4,
        max_tool_rounds=2,
        max_result_rows=200,
        max_result_bytes=262144,
    ),
)
