"""Authoritative Runtime Skill declaration for one bureau."""

from app.agents.runtime_skills.roles.bureaus.skill_spec import (
    BureauMethod,
    BureauRuntimeSkillSpec,
    BureauToolPolicySpec,
)
from app.agents.runtime_skills.tool_models import ToolName

__all__ = ("SKILL",)

SKILL: BureauRuntimeSkillSpec = BureauRuntimeSkillSpec(
    department="礼部",
    bureau="政企司",
    agent_id="libu-rites-government-enterprise",
    skill_id="analyze-government-enterprise-relations",
    method=BureauMethod(
        data_requirements=(
            "合作目标、主体资质与往来材料",
            "政策要求、申报清单和审批节点",
        ),
        analysis_procedure=(
            "核验合作主体与适用政策",
            "检查材料完整性和合规边界",
            "制定节点化跟进与升级计划",
        ),
        required_findings=(
            "材料缺口和政策适配",
            "合作边界与审批依赖",
        ),
        forbidden_actions=(
            "不得暗示政府背书或特殊通道",
            "不得代替主体提交或签署材料",
        ),
    ),
    tool_policy=BureauToolPolicySpec(
        policy_id="bureau.libu_rites.government_enterprise.tools",
        version="1.0.0",
        agent_id="libu-rites-government-enterprise",
        allowed_tools=(
            ToolName.REQUEST_EVIDENCE,
            ToolName.READ_APPROVED_MATERIALS,
            ToolName.INSPECT_APPROVED_DATA,
            ToolName.COMPUTE_ANALYSIS,
        ),
        allowed_data_domains=("communications.government_enterprise",),
        tool_operations=(
            (
                ToolName.REQUEST_EVIDENCE,
                ("request_fact_slots",),
            ),
            (
                ToolName.READ_APPROVED_MATERIALS,
                (
                    "read_summary",
                    "lookup_section",
                ),
            ),
            (
                ToolName.INSPECT_APPROVED_DATA,
                (
                    "describe",
                    "compare",
                    "lookup",
                ),
            ),
            (
                ToolName.COMPUTE_ANALYSIS,
                (
                    "difference",
                    "threshold",
                ),
            ),
        ),
        tool_argument_constraints=(
            (
                ToolName.REQUEST_EVIDENCE,
                (
                    (
                        "allowed_domains",
                        ("communications.government_enterprise",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        False,
                    ),
                    (
                        "allowed_fields",
                        ("communications.government_enterprise.counterparty_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("communications.government_enterprise.approval_stage",),
                    ),
                    (
                        "allowed_metrics",
                        ("communications.government_enterprise.material_gap_count",),
                    ),
                ),
            ),
            (
                ToolName.READ_APPROVED_MATERIALS,
                (
                    (
                        "allowed_domains",
                        ("communications.government_enterprise",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("communications.government_enterprise.counterparty_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("communications.government_enterprise.approval_stage",),
                    ),
                    (
                        "allowed_metrics",
                        ("communications.government_enterprise.material_gap_count",),
                    ),
                ),
            ),
            (
                ToolName.INSPECT_APPROVED_DATA,
                (
                    (
                        "allowed_domains",
                        ("communications.government_enterprise",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("communications.government_enterprise.counterparty_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("communications.government_enterprise.approval_stage",),
                    ),
                    (
                        "allowed_metrics",
                        ("communications.government_enterprise.material_gap_count",),
                    ),
                ),
            ),
            (
                ToolName.COMPUTE_ANALYSIS,
                (
                    (
                        "allowed_domains",
                        ("communications.government_enterprise",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("communications.government_enterprise.counterparty_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("communications.government_enterprise.approval_stage",),
                    ),
                    (
                        "allowed_metrics",
                        ("communications.government_enterprise.material_gap_count",),
                    ),
                ),
            ),
        ),
        required_data_refs=(
            "case",
            "decree",
        ),
        max_tool_calls=4,
        max_tool_rounds=2,
        max_result_rows=200,
        max_result_bytes=262144,
    ),
)
