"""Authoritative Runtime Skill declaration for one bureau."""

from app.agents.runtime_skills.roles.bureaus.skill_spec import (
    BureauMethod,
    BureauRuntimeSkillSpec,
    BureauToolPolicySpec,
)
from app.agents.runtime_skills.tool_models import ToolName

__all__ = ("SKILL",)

SKILL: BureauRuntimeSkillSpec = BureauRuntimeSkillSpec(
    department="礼部",
    bureau="公关司",
    agent_id="libu-rites-public-relations",
    skill_id="analyze-public-relations",
    method=BureauMethod(
        data_requirements=(
            "舆情样本、来源、时间线与传播量",
            "经核实事实、回应记录和升级预案",
        ),
        analysis_procedure=(
            "区分原始舆情与已核实事实",
            "评估传播路径、情绪和影响范围",
            "匹配回应口径与危机升级阈值",
        ),
        required_findings=(
            "舆情事实差距与传播态势",
            "回应窗口和升级条件",
        ),
        forbidden_actions=(
            "不得传播未核实指控",
            "不得未经批准对外回应或发布",
        ),
    ),
    tool_policy=BureauToolPolicySpec(
        policy_id="bureau.libu_rites.public_relations.tools",
        version="1.0.0",
        agent_id="libu-rites-public-relations",
        allowed_tools=(
            ToolName.REQUEST_EVIDENCE,
            ToolName.READ_APPROVED_MATERIALS,
            ToolName.INSPECT_APPROVED_DATA,
            ToolName.COMPUTE_ANALYSIS,
        ),
        allowed_data_domains=("communications.public_relations",),
        tool_operations=(
            (
                ToolName.REQUEST_EVIDENCE,
                ("request_fact_slots",),
            ),
            (
                ToolName.READ_APPROVED_MATERIALS,
                (
                    "read_summary",
                    "lookup_section",
                ),
            ),
            (
                ToolName.INSPECT_APPROVED_DATA,
                (
                    "filter",
                    "aggregate",
                    "compare",
                    "top_n",
                ),
            ),
            (
                ToolName.COMPUTE_ANALYSIS,
                (
                    "share",
                    "trend",
                    "threshold",
                ),
            ),
        ),
        tool_argument_constraints=(
            (
                ToolName.REQUEST_EVIDENCE,
                (
                    (
                        "allowed_domains",
                        ("communications.public_relations",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        False,
                    ),
                    (
                        "allowed_fields",
                        ("communications.public_relations.topic_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("communications.public_relations.sentiment_band",),
                    ),
                    (
                        "allowed_metrics",
                        ("communications.public_relations.reach_count",),
                    ),
                ),
            ),
            (
                ToolName.READ_APPROVED_MATERIALS,
                (
                    (
                        "allowed_domains",
                        ("communications.public_relations",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("communications.public_relations.topic_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("communications.public_relations.sentiment_band",),
                    ),
                    (
                        "allowed_metrics",
                        ("communications.public_relations.reach_count",),
                    ),
                ),
            ),
            (
                ToolName.INSPECT_APPROVED_DATA,
                (
                    (
                        "allowed_domains",
                        ("communications.public_relations",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("communications.public_relations.topic_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("communications.public_relations.sentiment_band",),
                    ),
                    (
                        "allowed_metrics",
                        ("communications.public_relations.reach_count",),
                    ),
                ),
            ),
            (
                ToolName.COMPUTE_ANALYSIS,
                (
                    (
                        "allowed_domains",
                        ("communications.public_relations",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("communications.public_relations.topic_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("communications.public_relations.sentiment_band",),
                    ),
                    (
                        "allowed_metrics",
                        ("communications.public_relations.reach_count",),
                    ),
                ),
            ),
        ),
        required_data_refs=(
            "case",
            "decree",
        ),
        max_tool_calls=4,
        max_tool_rounds=2,
        max_result_rows=200,
        max_result_bytes=262144,
    ),
)
