"""Authoritative Runtime Skill declaration for one bureau."""

from app.agents.runtime_skills.roles.bureaus.skill_spec import (
    BureauMethod,
    BureauRuntimeSkillSpec,
    BureauToolPolicySpec,
)
from app.agents.runtime_skills.tool_models import ToolName

__all__ = ("SKILL",)

SKILL: BureauRuntimeSkillSpec = BureauRuntimeSkillSpec(
    department="礼部",
    bureau="内容司",
    agent_id="libu-rites-content",
    skill_id="analyze-content-quality",
    method=BureauMethod(
        data_requirements=(
            "内容草稿、引用来源与事实清单",
            "渠道规范、受众和发布时间要求",
        ),
        analysis_procedure=(
            "逐项核验事实与引用",
            "评估结构、可读性和渠道适配",
            "列出发布门禁与修改优先级",
        ),
        required_findings=(
            "事实或引用缺陷",
            "内容质量与发布阻断项",
        ),
        forbidden_actions=(
            "不得补写无来源事实",
            "不得绕过审核直接发布",
        ),
    ),
    tool_policy=BureauToolPolicySpec(
        policy_id="bureau.libu_rites.content.tools",
        version="1.0.0",
        agent_id="libu-rites-content",
        allowed_tools=(
            ToolName.REQUEST_EVIDENCE,
            ToolName.READ_APPROVED_MATERIALS,
            ToolName.INSPECT_APPROVED_DATA,
            ToolName.COMPUTE_ANALYSIS,
        ),
        allowed_data_domains=("communications.content",),
        tool_operations=(
            (
                ToolName.REQUEST_EVIDENCE,
                ("request_fact_slots",),
            ),
            (
                ToolName.READ_APPROVED_MATERIALS,
                (
                    "read_summary",
                    "lookup_section",
                ),
            ),
            (
                ToolName.INSPECT_APPROVED_DATA,
                (
                    "filter",
                    "aggregate",
                    "compare",
                    "top_n",
                ),
            ),
            (
                ToolName.COMPUTE_ANALYSIS,
                (
                    "share",
                    "trend",
                    "threshold",
                ),
            ),
        ),
        tool_argument_constraints=(
            (
                ToolName.REQUEST_EVIDENCE,
                (
                    (
                        "allowed_domains",
                        ("communications.content",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        False,
                    ),
                    (
                        "allowed_fields",
                        ("communications.content.content_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("communications.content.channel",),
                    ),
                    (
                        "allowed_metrics",
                        ("communications.content.citation_gap_count",),
                    ),
                ),
            ),
            (
                ToolName.READ_APPROVED_MATERIALS,
                (
                    (
                        "allowed_domains",
                        ("communications.content",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("communications.content.content_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("communications.content.channel",),
                    ),
                    (
                        "allowed_metrics",
                        ("communications.content.citation_gap_count",),
                    ),
                ),
            ),
            (
                ToolName.INSPECT_APPROVED_DATA,
                (
                    (
                        "allowed_domains",
                        ("communications.content",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("communications.content.content_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("communications.content.channel",),
                    ),
                    (
                        "allowed_metrics",
                        ("communications.content.citation_gap_count",),
                    ),
                ),
            ),
            (
                ToolName.COMPUTE_ANALYSIS,
                (
                    (
                        "allowed_domains",
                        ("communications.content",),
                    ),
                    (
                        "operation_required",
                        True,
                    ),
                    (
                        "approved_refs_only",
                        True,
                    ),
                    (
                        "allowed_fields",
                        ("communications.content.content_id",),
                    ),
                    (
                        "allowed_dimensions",
                        ("communications.content.channel",),
                    ),
                    (
                        "allowed_metrics",
                        ("communications.content.citation_gap_count",),
                    ),
                ),
            ),
        ),
        required_data_refs=(
            "case",
            "decree",
        ),
        max_tool_calls=4,
        max_tool_rounds=2,
        max_result_rows=200,
        max_result_bytes=262144,
    ),
)
