"use client";
import Link from "next/link";
import { useMemo, useState, type FormEvent } from "react";
import { NAV_LINKS, PAIN_POINTS, PROOF_ITEMS, STAGES, USE_CASES } from "./welcomeContent";
import styles from "./welcome.module.css";
const DEFAULT_PROMPT = "这个客户该不该降价签？";
function demoFor(question: string) { const pricing = /降价|报价|客户|签/.test(question); return pricing ? { title: "客户降价签约 · 待裁奏折", risk: "若无条件降价，会形成长期价格锚点。", next: "给条件式报价：换年度预付、案例授权、回款节点。" } : { title: "经营事项 · 待裁奏折", risk: "信息尚不足，直接执行会放大不确定性。", next: "先下小令：补证、设限、回传，再请您准驳。" }; }
function Mark({ children }: { children: React.ReactNode }) { return <span className={styles.mark} aria-hidden="true">{children}</span>; }
export function WelcomeGate() {
 const [prompt,setPrompt]=useState(DEFAULT_PROMPT); const [submitted,setSubmitted]=useState(DEFAULT_PROMPT); const demo=useMemo(()=>demoFor(submitted),[submitted]);
 function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitted(prompt.trim() || DEFAULT_PROMPT); }
 return <main className={styles.page}><section className={styles.hero}><div className={styles.backdrop} aria-hidden="true"/><div className={styles.overlay} aria-hidden="true"/><div className={styles.grid} aria-hidden="true"/><div className={styles.axis} aria-hidden="true"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><path d="M51 0 46 18 54 32 48 48 55 63 45 79 51 100"/></svg></div>
 <header className={styles.header}><Link href="/" className={styles.brand}><span className={styles.seal} aria-hidden="true">朝</span><span>朝堂 OS<small>COURTOS</small></span></Link><nav className={styles.nav} aria-label="欢迎页导航">{NAV_LINKS.map(x=><a key={x.href} href={x.href}>{x.label}</a>)}</nav><div className={styles.accountLinks}><Link href="/login">已有账号</Link><Link href="/register" className={styles.primaryLink}>创建朝堂</Link></div></header>
 <div className={styles.content}><p className={styles.kicker}>AI 决策操作系统</p><h1>朝堂 OS</h1><p className={styles.tagline}>把你的公司，交给一座会思考的朝堂</p><p className={styles.intro}>专为老板决策太慢、部门信息割裂、AI 结果不可追责的企业设计。你只裁断关键事项。</p><div className={styles.tags}>{["老板被小事淹没","部门信息割裂","AI 输出不可追责","增长动作失控"].map(x=><span key={x}>{x}</span>)}</div><div className={styles.actions}><Link href="/register" className={styles.primaryLink}>创建朝堂</Link><a href="#pain-points" className={styles.secondaryLink}>先看解决什么痛点</a></div>
 <section id="demo" className={styles.demo} aria-label="试问朝堂"><form onSubmit={submit}><label>试问朝堂<input value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={DEFAULT_PROMPT}/></label><button type="submit">生成奏折</button></form><div className={styles.flow}>{STAGES.map((stage,i)=><span key={stage}><b>0{i+1}</b>{stage}</span>)}</div><div className={styles.verdict} aria-live="polite"><p>奏折预览</p><h2>{demo.title}</h2><strong>伏候圣裁</strong><p>“{submitted.trim() || DEFAULT_PROMPT}”</p><div><b>风险</b><p>{demo.risk}</p></div><div><b>下一步</b><p>{demo.next}</p></div></div></section></div></section>
 <section id="pain-points" className={styles.section}><p className={styles.kicker}>PAIN POINTS</p><h2>企业不是缺 AI，是缺一套可追责的决策系统</h2><p className={styles.lead}>朝堂 OS 不把 AI 包装成聊天框，而是把经营判断变成可审、可派、可复盘的闭环。</p><div className={styles.cards}>{PAIN_POINTS.map((x,i)=><article key={x.title}><Mark>0{i+1}</Mark><h3>{x.title}</h3><p><b>今天：</b>{x.old}</p><p><b>朝堂：</b>{x.court}</p></article>)}</div></section>
 <section id="solution" className={styles.section}><p className={styles.kicker}>FIRST LOOP</p><h2>从一个问题，到一个可执行裁断</h2><div className={styles.metrics}><span><b>5 殿</b>核心入口</span><span><b>2 轨</b>权责边界</span><span><b>准 / 驳</b>裁断方式</span></div><div className={styles.stages}>{STAGES.map((x,i)=><article key={x}><b>0{i+1}</b><h3>{x}</h3><span>{["收问题","查证据","会审","代办","归档"][i]}</span></article>)}</div></section>
 <section id="use-cases" className={styles.section}><p className={styles.kicker}>USE CASES</p><h2>先服务最常见的老板决策</h2><div className={styles.cards}>{USE_CASES.map((x,i)=><article key={x.title}><Mark>案例 {i+1}</Mark><h3>{x.title}</h3><p>{x.owner}</p><p>{x.result}</p></article>)}</div><div className={styles.proofs}>{PROOF_ITEMS.map(([title,body])=><article key={title}><Mark>证</Mark><h3>{title}</h3><p>{body}</p></article>)}</div></section>
 <section id="conversion" className={styles.conversion}><div><p className={styles.kicker}>DEMO ONLY</p><h2>预约体验，保存你的第一座朝堂</h2><p>这是公开演示入口：不会提交或保存任何信息。注册和登录均前往对应页面。</p></div><div className={styles.actions}><a href="#demo" className={styles.secondaryLink}>再看奏折</a><Link href="/register" className={styles.primaryLink}>创建朝堂</Link></div></section>
 </main>;
}
