import { randomUUID } from 'node:crypto';
import { pathToFileURL } from 'node:url';
import { existsSync } from 'node:fs';
import { openControlPlaneDb, withImmediateTransaction, normalizeGitEntryPath, normalizeRepoPath, pathsOverlap, nextFencingEpoch, processIdentity, registeredProcessIdentity, registeredProcessAlive, nowIso, auditEvent } from './lib/control-plane-db.mjs';

const isoAfter = ms => new Date(Date.now()+ms).toISOString();
function expireDue(db, now=nowIso()){const rows=db.prepare("SELECT lease_id,owner FROM leases WHERE state='active' AND expires_at<=?").all(now); for(const r of rows){db.prepare("UPDATE leases SET state='reclaimed',released_at=? WHERE lease_id=?").run(now,r.lease_id); auditEvent(db,{event:'lease.expired',actor:'system',subject:r.lease_id});} return rows.length;}
export function acquireLease({task_id, owner, resource_type='path', resource, mode='write', ttl_ms=60000,holder_process}, options={}) {
  if(!['path','port','build','release','integration'].includes(resource_type)||typeof resource!=='string'||!resource||!['read','write'].includes(mode)||ttl_ms<=0||(resource_type!=='path'&&mode!=='write'))throw new Error('invalid resource, mode or ttl; non-path resources are exclusive');
  const normalized=resource_type==='path'?normalizeRepoPath(resource,options.cwd):resource,entryResource=resource_type==='path'?normalizeGitEntryPath(resource,options.cwd):resource;
  const {db}=openControlPlaneDb(options); try{return withImmediateTransaction(db,()=>{expireDue(db); const task=db.prepare('SELECT owner,status,spec_json,expires_at FROM tasks WHERE task_id=?').get(task_id); if(!task)throw new Error('task not found'); if(task.owner!==owner)throw new Error('owner mismatch');if(!['ready','leased','running'].includes(task.status)||Date.parse(task.expires_at)<=Date.now())throw new Error('task is expired or not leasable'); const spec=JSON.parse(task.spec_json);
    if(resource_type==='path'){const frozen=spec.metadata?._control_plane;if(!frozen)throw new Error('task lacks frozen canonical path authorization');const currentRead=spec.read_paths.map(p=>normalizeRepoPath(p,options.cwd)),currentWrite=spec.write_paths.map(p=>normalizeRepoPath(p,options.cwd));if(JSON.stringify(currentRead)!==JSON.stringify(frozen.canonical_read_paths)||JSON.stringify(currentWrite)!==JSON.stringify(frozen.canonical_write_paths))throw new Error('task path resolution drifted since creation; fail closed');const permitted=mode==='write'?frozen.canonical_write_paths:[...frozen.canonical_read_paths,...frozen.canonical_write_paths],entryPermitted=(mode==='write'?spec.write_paths:[...spec.read_paths,...spec.write_paths]).map(p=>normalizeGitEntryPath(p,options.cwd));if(!permitted.some(p=>normalized===p||normalized.startsWith(`${p}/`))||!entryPermitted.some(p=>entryResource===p||entryResource.startsWith(`${p}/`)))throw new Error('resource is outside task path authorization');}
    else if(!spec.resources.includes(normalized))throw new Error('resource is outside task resource authorization');
    const active=db.prepare("SELECT resource,entry_resource,mode,lease_id,task_id,owner FROM leases WHERE state='active' AND resource_type=?").all(resource_type);
    for(const row of active){const overlap=resource_type==='path'?(pathsOverlap(row.resource,normalized)||pathsOverlap(row.entry_resource,entryResource)):row.resource===normalized;if(overlap&&(mode==='write'||row.mode==='write')&&!(row.task_id===task_id&&row.owner===owner))throw new Error(`lease conflict: ${row.lease_id}`);}
    const lease_id=`lease-${randomUUID()}`, acquired_at=nowIso(), fencing_epoch=nextFencingEpoch(db); const process=holder_process?registeredProcessIdentity(holder_process):processIdentity(options.cwd);
    const expires_at=isoAfter(ttl_ms);
    db.prepare('INSERT INTO leases(lease_id,task_id,owner,resource_type,resource,mode,acquired_at,heartbeat_at,expires_at,state,fencing_epoch,process_json,released_at,entry_resource) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,NULL,?)').run(lease_id,task_id,owner,resource_type,normalized,mode,acquired_at,acquired_at,expires_at,'active',fencing_epoch,JSON.stringify(process),entryResource);
    db.prepare("UPDATE tasks SET status='leased' WHERE task_id=?").run(task_id); auditEvent(db,{event:'lease.acquired',actor:owner,subject:lease_id,payload:{resource:normalized,entry_resource:entryResource,mode,fencing_epoch}}); return {schema_version:1,lease_id,task_id,holder:owner,resource_type,resource:normalized,entry_resource:entryResource,...(resource_type==='path'?{mode}:{}),acquired_at,heartbeat_at:acquired_at,expires_at,state:'active',fencing_epoch,process};});}finally{db.close();}
}
function assertLeaseIdentity(r,holder){const p=JSON.parse(r.process_json);if(!holder||holder.nonce!==p.nonce||holder.fencing_epoch!==r.fencing_epoch||!registeredProcessAlive(p))throw new Error('lease credential, holder identity or fencing mismatch');}
export function heartbeatLease({lease_id,holder,ttl_ms=60000},options={}){const{db}=openControlPlaneDb(options);try{return withImmediateTransaction(db,()=>{expireDue(db);const r=db.prepare("SELECT * FROM leases WHERE lease_id=? AND state='active'").get(lease_id);if(!r)throw new Error('active lease not found');assertLeaseIdentity(r,holder);const now=nowIso(),expires=isoAfter(ttl_ms);db.prepare('UPDATE leases SET heartbeat_at=?,expires_at=? WHERE lease_id=?').run(now,expires,lease_id);auditEvent(db,{event:'lease.heartbeat',actor:r.owner,subject:lease_id});return{lease_id,heartbeat_at:now,expires_at:expires,fencing_epoch:r.fencing_epoch};});}finally{db.close();}}
export function releaseLease({lease_id,holder,force=false,actor,reason,evidence},options={}){if(force&&(!actor||!reason||!evidence))throw new Error('force-release requires actor, reason and evidence');const{db}=openControlPlaneDb(options);try{return withImmediateTransaction(db,()=>{const r=db.prepare("SELECT * FROM leases WHERE lease_id=? AND state='active'").get(lease_id);if(!r)throw new Error('active lease not found');if(!force)assertLeaseIdentity(r,holder);db.prepare("UPDATE leases SET state=?,released_at=? WHERE lease_id=?").run(force?'fenced':'released',nowIso(),lease_id);auditEvent(db,{event:force?'lease.force_released':'lease.released',actor:force?actor:r.owner,subject:lease_id,reason,payload:{evidence,previous_owner:r.owner,fencing_epoch:r.fencing_epoch}});return{lease_id,state:force?'fenced':'released'};});}finally{db.close();}}
export function expireLeases(options={}){const{db}=openControlPlaneDb(options);try{return withImmediateTransaction(db,()=>({expired:expireDue(db)}));}finally{db.close();}}
function publicLease(r,{revealNonce=false}={}){const process=JSON.parse(r.process_json);if(!revealNonce)process.nonce='redacted-redacted';return{schema_version:1,lease_id:r.lease_id,task_id:r.task_id,holder:r.owner,resource_type:r.resource_type,resource:r.resource,...(r.resource_type==='path'?{mode:r.mode}:{}),state:r.state,fencing_epoch:r.fencing_epoch,acquired_at:r.acquired_at,heartbeat_at:r.heartbeat_at,expires_at:r.expires_at,...(['released','reclaimed'].includes(r.state)?{released_at:r.released_at}:{}),process};}
export function leaseStatus(options={}){const{db}=openControlPlaneDb(options);try{return withImmediateTransaction(db,()=>{expireDue(db);return db.prepare('SELECT * FROM leases ORDER BY fencing_epoch').all().map(publicLease);});}finally{db.close();}}

function val(args,k,d){const i=args.indexOf(`--${k}`);return i<0?d:args[i+1];} async function main(){const[c,...a]=process.argv.slice(2);let out;const barrier=process.env.CHAOTANG_TEST_BARRIER_FILE;if(barrier){if(process.env.NODE_ENV!=='test')throw new Error('barrier is test-only');while(!existsSync(barrier))Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,5);}const databasePath=val(a,'test-db');if(databasePath&&!(process.env.NODE_ENV==='test'&&process.env.CHAOTANG_CONTROL_PLANE_TEST_ADAPTER==='1'))throw new Error('test-db requires explicit test adapter');const options={databasePath};if(c==='acquire')out=acquireLease({task_id:val(a,'task'),owner:val(a,'owner'),resource_type:val(a,'type','path'),resource:val(a,'path',val(a,'resource')),mode:val(a,'mode','write'),ttl_ms:Number(val(a,'ttl-ms','60000')),holder_process:val(a,'holder-pid')?{pid:Number(val(a,'holder-pid')),pgid:Number(val(a,'holder-pgid')),start_ticks:Number(val(a,'holder-start-ticks')),cwd:val(a,'holder-cwd')}:undefined},options);else if(c==='heartbeat')out=heartbeatLease({lease_id:val(a,'lease'),holder:{nonce:val(a,'nonce'),fencing_epoch:Number(val(a,'epoch'))},ttl_ms:Number(val(a,'ttl-ms','60000'))},options);else if(c==='release'||c==='force-release')out=releaseLease({lease_id:val(a,'lease'),holder:{nonce:val(a,'nonce'),fencing_epoch:Number(val(a,'epoch'))},force:c==='force-release',actor:val(a,'actor'),reason:val(a,'reason'),evidence:val(a,'evidence')},options);else if(c==='expire')out=expireLeases(options);else if(c==='status')out=leaseStatus(options);else throw new Error('usage: acquire|heartbeat|release|force-release|expire|status');console.log(JSON.stringify(out,null,a.includes('--json')?2:0));}
if(import.meta.url===pathToFileURL(process.argv[1]??'').href)main().catch(e=>{console.error(e.message);process.exitCode=1;});
