import { lstatSync, readFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import { openControlPlaneDb, withImmediateTransaction, normalizeRepoPath, nowIso, auditEvent, registeredProcessAlive } from './lib/control-plane-db.mjs';

const STATUSES = new Set(['draft','ready','leased','running','blocked','review','completed','cancelled']);
export function createTask(spec, options = {}) {
  const required = ['task_id','title','owner','risk','write_paths','read_paths','dependencies','worktree','resources','expires_at'];
  const allowed=new Set([...required,'metadata']);for(const key of Object.keys(spec))if(!allowed.has(key))throw new Error(`unknown task field: ${key}`);
  for (const key of required) if (!(key in spec)) throw new Error(`missing ${key}`);
  for(const key of ['schema_version','status','created_at','updated_at']) if(key in spec) throw new Error(`${key} is system managed`);
  if(new Set(spec.dependencies).size!==spec.dependencies.length||new Set(spec.write_paths).size!==spec.write_paths.length||new Set(spec.read_paths).size!==spec.read_paths.length||new Set(spec.resources).size!==spec.resources.length)throw new Error('duplicate task values');
  for(const p of [...spec.write_paths,...spec.read_paths])if(typeof p!=='string'||!p||p.startsWith('/')||/(^|\/)\.\.(\/|$)|[*?\[\]{}]/.test(p))throw new Error(`invalid task path: ${p}`);
  if (spec.dependencies.includes(spec.task_id)) throw new Error('task cannot depend on itself');
  if (!['low','medium','high','critical'].includes(spec.risk)) throw new Error('invalid risk');
  if(typeof spec.title!=='string'||!spec.title||typeof spec.owner!=='string'||!spec.owner||typeof spec.worktree!=='string'||!spec.worktree)throw new Error('invalid task strings');
  if(!Array.isArray(spec.dependencies)||!Array.isArray(spec.write_paths)||!Array.isArray(spec.read_paths)||!Array.isArray(spec.resources))throw new Error('task lists must be arrays');
  if(!Number.isFinite(Date.parse(spec.expires_at)))throw new Error('invalid expires_at');
  for(const r of spec.resources)if(!/^(port:(3002|3050|31\d{2})|build:[A-Za-z0-9._-]+|release:[A-Za-z0-9._-]+|integration:[A-Za-z0-9._-]+)$/.test(r))throw new Error(`invalid resource: ${r}`);
  const { db } = openControlPlaneDb(options);
  try { return withImmediateTransaction(db, () => {
    if (db.prepare('SELECT 1 FROM tasks WHERE task_id=?').get(spec.task_id)) throw new Error('task already exists');
    for (const dep of spec.dependencies) if (!db.prepare('SELECT 1 FROM tasks WHERE task_id=?').get(dep)) throw new Error(`dependency not found: ${dep}`);
    // Existing graph is acyclic; requiring dependencies to pre-exist prevents forward-reference cycles.
    const createdAt = nowIso();if(Date.parse(spec.expires_at)<=Date.parse(createdAt))throw new Error('task expires_at must be after created_at');
    if(!/^task-[A-Za-z0-9._-]+$/.test(spec.task_id)) throw new Error('invalid task_id');
    const publicRecord={schema_version:1,status:'ready',created_at:createdAt,...spec};
    const record={...publicRecord,metadata:{...(spec.metadata??{}),_control_plane:{canonical_read_paths:spec.read_paths.map(p=>normalizeRepoPath(p,options.cwd)),canonical_write_paths:spec.write_paths.map(p=>normalizeRepoPath(p,options.cwd))}}};
    db.prepare('INSERT INTO tasks VALUES(?,?,?,?,?,?)').run(spec.task_id, JSON.stringify(record), spec.owner, 'ready', createdAt, spec.expires_at);
    auditEvent(db,{event:'task.created',actor:spec.owner,subject:spec.task_id,payload:{dependencies:spec.dependencies}});
    return publicRecord;
  }); } finally { db.close(); }
}
export function listTasks(options={}) { const {db}=openControlPlaneDb(options); try{return db.prepare('SELECT spec_json,status FROM tasks ORDER BY created_at').all().map(r=>{const spec=JSON.parse(r.spec_json),metadata={...(spec.metadata??{})};delete metadata._control_plane;return{...spec,status:r.status,...(Object.keys(metadata).length?{metadata}:{metadata:undefined})};});}finally{db.close();} }
export function recordTaskStep(taskId,owner,stepId,outcome='completed',options={}){if(!/^step-[A-Za-z0-9._-]+$/.test(stepId??'')||!['completed','retried'].includes(outcome))throw new Error('task step invalid');const{db}=openControlPlaneDb(options);try{return withImmediateTransaction(db,()=>{const task=db.prepare('SELECT owner,status,spec_json FROM tasks WHERE task_id=?').get(taskId);if(!task||task.owner!==owner||!['leased','running','review'].includes(task.status))throw new Error('task step owner/status invalid');const spec=JSON.parse(task.spec_json),plan=spec.metadata?.rollout_steps,testAdapter=process.env.NODE_ENV==='test'&&process.env.CHAOTANG_CONTROL_PLANE_TEST_ADAPTER==='1'&&options.testAdapter===true;if((!Array.isArray(plan)||!plan.includes(stepId))&&!testAdapter)throw new Error('task step is not in the predeclared rollout plan');if(!testAdapter){const credential=options.leaseCredential;if(!credential)throw new Error('task step requires a live lease credential');const lease=db.prepare("SELECT * FROM leases WHERE lease_id=? AND task_id=? AND owner=? AND state='active'").get(credential.lease_id,taskId,owner);if(!lease||lease.fencing_epoch!==credential.fencing_epoch||Date.parse(lease.expires_at)<=Date.now())throw new Error('task step lease credential invalid or expired');const process=JSON.parse(lease.process_json);if(process.nonce!==credential.nonce||!registeredProcessAlive(process))throw new Error('task step lease holder identity is not live');}if(db.prepare("SELECT 1 FROM audit_events WHERE event='task.step.completed' AND subject=? AND json_extract(payload_json,'$.step_id')=?").get(taskId,stepId)&&outcome==='completed')throw new Error('task step already completed');auditEvent(db,{event:`task.step.${outcome}`,actor:owner,subject:taskId,payload:{step_id:stepId}});return{task_id:taskId,step_id:stepId,outcome};});}finally{db.close();}}
export function finalizeTask(taskId,owner,options={}){const{db}=openControlPlaneDb(options);try{return withImmediateTransaction(db,()=>{const row=db.prepare('SELECT * FROM tasks WHERE task_id=?').get(taskId);if(!row||row.owner!==owner||!['running','review','leased'].includes(row.status))throw new Error('task is not finalizable by owner');const spec=JSON.parse(row.spec_json),events=db.prepare('SELECT id,event,payload_json,created_at FROM audit_events WHERE subject=? ORDER BY id').all(taskId),eventNames=events.map(event=>event.event),payloads=events.map(event=>{try{return JSON.parse(event.payload_json);}catch{return{};}}),taskClass=spec.metadata?.rollout_class,completed=events.filter(event=>event.event==='task.step.completed'),retried=events.filter(event=>event.event==='task.step.retried');if(typeof taskClass!=='string'||!/^[A-Za-z0-9._-]+$/.test(taskClass))throw new Error('task metadata.rollout_class is required for comparable rollout metrics');if(completed.length===0)throw new Error('at least one authoritative task.step.completed audit is required');const metric={taskClass,window:'auto',totalSteps:completed.length,duplicateSteps:retried.length,pathConflicts:eventNames.filter(event=>event==='path.conflict'||event==='lease.conflict').length,portConflicts:eventNames.filter(event=>event==='port.conflict').length,buildConflicts:eventNames.filter(event=>event==='build.conflict'||event==='resource.conflict').length,falsePositive:eventNames.includes('control.false_positive_confirmed'),overheadSeconds:payloads.reduce((sum,payload)=>sum+(Number.isFinite(payload.control_overhead_seconds)?payload.control_overhead_seconds:0),0),dataComplete:eventNames.includes('task.created')&&completed.every(event=>{try{return Boolean(JSON.parse(event.payload_json).step_id);}catch{return false;}})};if(metric.duplicateSteps>metric.totalSteps)throw new Error('retried steps exceed completed steps');db.prepare("UPDATE tasks SET status='completed' WHERE task_id=?").run(taskId);auditEvent(db,{event:'task.metrics.finalized',actor:owner,subject:taskId,payload:metric});auditEvent(db,{event:'task.completed',actor:owner,subject:taskId,payload:{metric_source:'task.metrics.finalized'}});return{task_id:taskId,status:'completed',metric};});}finally{db.close();}}

async function main(){ const [cmd,...args]=process.argv.slice(2),value=key=>{const i=args.indexOf(`--${key}`);return i<0?undefined:args[i+1];}; const json=args.includes('--json'); if(cmd==='create'){const i=args.indexOf('--spec'); if(i<0)throw new Error('--spec required'); console.log(JSON.stringify(createTask(JSON.parse(readFileSync(args[i+1],'utf8')))));} else if(cmd==='list')console.log(JSON.stringify(listTasks(),null,json?2:0));else if(cmd==='step'){const credentialFile=value('credential-file');if(!credentialFile)throw new Error('--credential-file required');const stat=lstatSync(credentialFile);if(stat.isSymbolicLink()||!stat.isFile()||(stat.mode&0o077)!==0||stat.uid!==process.getuid())throw new Error('credential file must be owner-only regular file');console.log(JSON.stringify(recordTaskStep(value('task'),value('owner'),value('step'),value('outcome')??'completed',{leaseCredential:JSON.parse(readFileSync(credentialFile,'utf8'))})));}else if(cmd==='finalize')console.log(JSON.stringify(finalizeTask(value('task'),value('owner')))); else throw new Error('usage: create --spec FILE | list --json | step --task ID --owner OWNER --step step-ID --credential-file FILE [--outcome completed|retried] | finalize --task ID --owner OWNER'); }
if(import.meta.url===pathToFileURL(process.argv[1]??'').href) main().catch(e=>{console.error(e.message);process.exitCode=1;});
