#!/usr/bin/env node
import {guardRolloutIfStarted,inspectRolloutWatch,evaluateRollout} from './lib/rollout-controller.mjs';
import {pathToFileURL} from 'node:url';

const args=new Set(process.argv.slice(2)),once=args.has('--once');
const intervalArg=process.argv.indexOf('--interval-seconds'),interval=intervalArg<0?14400:Number(process.argv[intervalArg+1]);
if(!once&&(!Number.isFinite(interval)||interval<60))throw new Error('watch interval must be at least 60 seconds');
export function rolloutAlerts(status,evaluation){const alerts=[];if(['enforce_paths','enforce_resources','mandatory'].includes(status.stage)&&status.external!=='VERIFIED')alerts.push({severity:'P0',code:'ANCHOR_NOT_VERIFIED'});if(status.anchorBacklog>0)alerts.push({severity:status.stage==='observe'?'P1':'P0',code:'ANCHOR_BACKLOG',count:status.anchorBacklog});if(status.lastTransition?.event==='rollout.auto_rollback')alerts.push({severity:'P1',code:'AUTOMATIC_ROLLBACK',reason:status.lastTransition.reason});if(status.metrics?.observation?.falsePositiveRate>=0.02)alerts.push({severity:'P1',code:'FALSE_POSITIVE_THRESHOLD'});if(status.metrics?.observation?.maxOverheadSeconds>300)alerts.push({severity:'P1',code:'TASK_OVERHEAD_THRESHOLD'});if(status.releaseStreak<20&&status.stage==='mandatory')alerts.push({severity:'P0',code:'RELEASE_STREAK_LOST'});if(status.acceptance?.passed<status.acceptance?.required&&status.stage==='mandatory')alerts.push({severity:'P0',code:'ACCEPTANCE_SET_LOST'});if(status.status==='ENFORCED'&&!evaluation.eligible)alerts.push({severity:'P0',code:'ENFORCED_ELIGIBILITY_LOST'});return alerts;}
function probe(){guardRolloutIfStarted({kind:'release',compliant:true,actor:'rollout-watch',subject:'authoritative-telemetry-poll'});const status=inspectRolloutWatch(),evaluation=evaluateRollout(),alerts=rolloutAlerts(status,evaluation),record={observed_at:new Date().toISOString(),status,evaluation,alerts};process.stdout.write(`${JSON.stringify(record)}\n`);if(alerts.some(alert=>alert.severity==='P0'))throw new Error(alerts.map(alert=>alert.code).join(','));return record;}
if(import.meta.url===pathToFileURL(process.argv[1]??'').href){probe();if(!once)setInterval(()=>{try{probe();}catch(error){process.stderr.write(`ROLLOUT ALERT: ${error.message}\n`);process.exitCode=1;}},interval*1000);}
