/**
 * 真主库 overview 快照(captured 2026-06-30 · 仅作 eval 输入,非编造)
 * 来源:GET /api/court/hubu/overview · source=turso · 7 行
 * 脱敏(会审 HIGH-1):含具体金额/客户/独家条款的谈判底牌那行已脱敏,只留驱动风险的关键词;
 * 结构字段保留以维持 eval 真实性。其余行为通用内部决策,无对手方机密。
 */
import type { HubuProject } from '@/lib/contracts/hubu';

export const REAL_OVERVIEW_SOURCE = "turso" as const;
export const REAL_OVERVIEW_SAMPLE: HubuProject[] = [
  {
    "id": "real-1782635315091",
    "title": "花12万投实体店装修",
    "target_dept": "",
    "owner_dept": "户部",
    "status": "pending_review",
    "requested_budget": "12万",
    "estimated_roi": "1.8倍",
    "payback_window": "8个月",
    "cash_flow_pressure": "现金紧张",
    "priority": "P1",
    "risk_level": "high",
    "recommendation": "",
    "command": "",
    "acceptance_criteria": [],
    "created_at": "2026-06-28T08:28:35.272Z",
    "updated_at": "2026-06-28T08:28:35.272Z"
  },
  {
    "id": "task_1ac95693-359a-4cb1-94a6-b3aadab6a9fb",
    "title": "PACK研发蜂群流程：请复盘需求、验证、采购和试制四段瓶颈，并给出下一步责任人。",
    "target_dept": "—",
    "owner_dept": "户部",
    "status": "pending_review",
    "requested_budget": "—",
    "estimated_roi": "—",
    "payback_window": "—",
    "cash_flow_pressure": "—",
    "priority": "P1",
    "risk_level": "medium",
    "recommendation": "据真实旨意派生 · 预算/ROI 仅取命令中明示值，余项待补。",
    "command": "PACK研发蜂群流程：请复盘需求、验证、采购和试制四段瓶颈，并给出下一步责任人。",
    "acceptance_criteria": [],
    "created_at": "2026-06-30T06:00:34.618Z",
    "updated_at": "2026-06-30T12:33:55.039Z"
  },
  {
    "id": "ssf_7f94f0c2-34c3-4391-8928-7b551497d889",
    "title": "请军机处围绕“请分析我们当前的展会预算执行情况，包括预算总额、已支出金额、使用明细及是否超出计划",
    "target_dept": "—",
    "owner_dept": "户部",
    "status": "pending_review",
    "requested_budget": "—",
    "estimated_roi": "—",
    "payback_window": "—",
    "cash_flow_pressure": "—",
    "priority": "P1",
    "risk_level": "medium",
    "recommendation": "据真实旨意派生 · 预算/ROI 仅取命令中明示值，余项待补。",
    "command": "请分析我们当前的展会预算执行情况，包括预算总额、已支出金额、使用明细及是否超出计划，并指出可能存在的资金使用效率问题或需关注的费用风险点。",
    "acceptance_criteria": [],
    "created_at": "2026-06-24T17:01:40.642Z",
    "updated_at": "2026-06-24T17:01:41.983Z"
  },
  {
    "id": "ssf_ff2eb027-7800-4da1-a81d-3735cb106a53",
    "title": "请军机处围绕“是否签下某供货合同?涉预付款、固定交期与独家供应条款",
    "target_dept": "—",
    "owner_dept": "户部",
    "status": "pending_review",
    "requested_budget": "—",
    "estimated_roi": "—",
    "payback_window": "—",
    "cash_flow_pressure": "—",
    "priority": "P1",
    "risk_level": "medium",
    "recommendation": "据真实旨意派生 · 预算/ROI 仅取命令中明示值，余项待补。",
    "command": "是否签下某供货合同?涉预付款、固定交期与独家供应条款。(金额/客户已脱敏,仅留风险关键词供 eval)",
    "acceptance_criteria": [],
    "created_at": "2026-06-24T16:45:17.977Z",
    "updated_at": "2026-06-24T16:46:03.914Z"
  },
  {
    "id": "ssf_6318fd7c-56b3-4ee8-9dea-5158bdbbdeea",
    "title": "请军机处围绕“客户要求正式报价，要不要发？”组织会审，重点核查证据、风险、缺口、责任边界和唯一下",
    "target_dept": "—",
    "owner_dept": "户部",
    "status": "pending_review",
    "requested_budget": "—",
    "estimated_roi": "—",
    "payback_window": "—",
    "cash_flow_pressure": "—",
    "priority": "P1",
    "risk_level": "medium",
    "recommendation": "据真实旨意派生 · 预算/ROI 仅取命令中明示值，余项待补。",
    "command": "客户要求正式报价，要不要发？",
    "acceptance_criteria": [],
    "created_at": "2026-06-24T16:16:19.998Z",
    "updated_at": "2026-06-24T16:16:19.998Z"
  },
  {
    "id": "ssf_0da78fb5-938a-4c23-9fae-9b427499fc07",
    "title": "请军机处围绕“审批市场部建设预算 12 万，预期 ROI 3x，要不要批？”组织会审，重点核查证",
    "target_dept": "—",
    "owner_dept": "户部",
    "status": "pending_review",
    "requested_budget": "12 万",
    "estimated_roi": "3x",
    "payback_window": "—",
    "cash_flow_pressure": "—",
    "priority": "P1",
    "risk_level": "medium",
    "recommendation": "据真实旨意派生 · 预算/ROI 仅取命令中明示值，余项待补。",
    "command": "审批市场部建设预算 12 万，预期 ROI 3x，要不要批？",
    "acceptance_criteria": [],
    "created_at": "2026-06-24T16:16:10.478Z",
    "updated_at": "2026-06-24T16:16:10.478Z"
  },
  {
    "id": "ssf_f214196c-d367-4ffe-940d-333f3107db6e",
    "title": "请军机处围绕“请户部会审压价清库存的利润风险。”组织会审，重点核查证据、风险、缺口、责任边界和唯",
    "target_dept": "—",
    "owner_dept": "户部",
    "status": "pending_review",
    "requested_budget": "—",
    "estimated_roi": "—",
    "payback_window": "—",
    "cash_flow_pressure": "—",
    "priority": "P1",
    "risk_level": "medium",
    "recommendation": "据真实旨意派生 · 预算/ROI 仅取命令中明示值，余项待补。",
    "command": "请户部会审压价清库存的利润风险。",
    "acceptance_criteria": [],
    "created_at": "2026-06-19T09:41:18.065Z",
    "updated_at": "2026-06-19T09:41:18.065Z"
  }
];
