// Generated by scripts/api-contract-stability.mjs.
// Do not edit by hand. Regenerate after backend contract changes.

export type _ChronicleRequest = {
  "days"?: number | null;
  "type"?: "日史" | "周史" | "月史" | "专题史";
};

export type _DepartmentRouteRequest = {
  "context"?: string;
  "task": string;
};

export type _ImaKnowledgeStatusRequest = {
  "id": string;
  "status": "active" | "archived";
};

export type _ImaKnowledgeUploadRequest = {
  "content": string;
  "filename": string;
  "lastModified"?: number | null;
  "mimeType"?: string | null;
  "size"?: number | null;
  "source"?: string;
};

export type _QuickCommandRequest = {
  "rawCommand": string;
};

export type _QuickSummonRequest = {
  "mode": string;
  "topic"?: string;
};

export type _RetrospectiveRequest = {
  "authoredBy"?: string;
  "failures"?: string[];
  "lessons"?: string[];
  "outcome"?: "success" | "blocked" | "pending";
  "playbook"?: string | null;
  "score"?: number;
  "successes"?: string[];
};

export type _TeachingRequest = {
  "context"?: string;
  "message": string;
};

export type ABTestRequest = {
  "config_a": string;
  "config_b": string;
  "qa_version_a"?: string | null;
  "qa_version_b"?: string | null;
  "task": string;
};

export type AcceptedDesignRequest = {
  "context"?: string;
  "design_choice"?: string;
  "step_id"?: string;
};

export type ActionRequest = {
  "action": string;
  "at"?: string;
  "confirm"?: boolean;
  "doc": {
  [key: string]: unknown;
};
  "idempotency_key"?: string | null;
};

export type AuthMeResponse = {
  "authenticated": boolean;
  "user"?: CurrentUser | null;
};

export type BriefDecisionAdvanceRequest = {
  "decision": string;
  "executionType"?: string | null;
  "manualConfirmation"?: boolean;
  "reason"?: string;
};

export type Budget = {
  "maxCalls"?: number | null;
  "maxCostUsd"?: number | null;
  "maxSubagentsPerGroup"?: number | null;
};

export type BusinessOutcomeRequest = {
  "flow_name"?: string;
  "metadata"?: {
  [key: string]: unknown;
};
  "outcome"?: string;
  "quality_score"?: number;
  "reviewer"?: string;
  "task_input"?: string;
};

export type CalibrationRequest = {
  "dimensions_human"?: {
  [key: string]: unknown;
};
  "dimensions_llm"?: {
  [key: string]: unknown;
};
  "human_score": number;
  "llm_score"?: number;
  "notes"?: string;
  "reviewer"?: string;
  "run_id": string;
  "step_id"?: string;
};

export type CapabilityActivationRequest = {
  "candidate_capability_ids": string[];
  "mission_contract_id": string;
};

export type CapabilityGrantV1 = {
  "activation_status": "NOT_ACTIVATED" | "ACTIVATED";
  "body_access"?: boolean;
  "capability_id": string;
  "required_by_mission": boolean;
  "schema_version"?: "CapabilityGrantV1";
  "token_scope"?: string[];
  "tool_access"?: string[];
};

export type CaseActionResponse = {
  "ok": boolean;
};

export type CaseRejectRequest = {
  "reason"?: string;
};

export type CategorySelection = {
  "groups"?: string[];
  "label"?: string | null;
  "ministers"?: string[];
  "taskType"?: string;
};

export type ChancellorChatRequest = {
  "message": string;
};

export type ChatCompletionChoice = {
  "finish_reason"?: string;
  "index": number;
  "message": ChatMessage;
};

export type ChatCompletionRequest = {
  "max_tokens"?: number | null;
  "messages"?: ChatMessage[];
  "model": string;
  "n"?: number | null;
  "stream"?: boolean;
  "temperature"?: number | null;
  "top_p"?: number | null;
};

export type ChatCompletionResponse = {
  "choices": ChatCompletionChoice[];
  "id": string;
  "model": string;
  "object"?: string;
  "usage"?: ChatCompletionUsage;
};

export type ChatCompletionUsage = {
  "completion_tokens"?: number;
  "prompt_tokens"?: number;
  "total_tokens"?: number;
};

export type ChatMessage = {
  "content"?: string;
  "role": string;
};

export type ChatSessionCreateRequest = {
  "config"?: string | null;
  "flow"?: string | null;
};

export type ChatSessionTurnRequest = {
  "config"?: string | null;
  "qa_version"?: string | null;
  "user_input": string;
};

export type ChatSessionTurnResponse = {
  "status"?: string;
  "task_id": string;
};

export type ConfirmEdictRequest = {
  "confirmed"?: boolean;
  "confirmed_edict_text"?: string | null;
  "edited_edict"?: {
  [key: string]: unknown;
} | null;
  "idempotency_key"?: string | null;
  "task_id": string;
};

export type ContractDecisionV1 = {
  "content_hash": string;
  "decided_at": string;
  "final_memorial_id": string;
  "mission_contract_id": string;
  "schema_version"?: "ContractDecisionV1";
  "verdict": "NEED_INFO" | "REVISE_BEFORE_PROCEED" | "PROCEED_TO_HUMAN_APPROVAL" | "BLOCKED" | "NEED_LEGAL_REVIEW";
  "verdict_narrative": string;
};

export type ContractIntakeV1 = {
  "contract_type"?: "procurement" | "sales" | "service" | "UNSUPPORTED_OR_UNKNOWN" | null;
  "jurisdiction"?: "CN_MAINLAND" | "UNSUPPORTED_OR_UNKNOWN" | null;
  "language"?: "zh-CN" | "UNSUPPORTED_OR_UNKNOWN" | null;
  "our_role"?: "buyer" | "seller" | "service_provider" | "other_party" | "UNSUPPORTED_OR_UNKNOWN" | null;
  "schema_version"?: "ContractIntakeV1";
};

export type ContractLineageStatusV1 = {
  "capability_activation_status": "NOT_ACTIVATED" | "ACTIVATED";
  "content_digest": string;
  "decision_status": "NOT_DECIDED" | "DECIDED";
  "lineage_id": string;
  "mission_contract_id": string;
  "mission_status": "DRAFT" | "AWAITING_CONFIRMATION" | "CONFIRMED" | "SUPERSEDED" | "EXPIRED";
  "revision": number;
  "schema_version"?: "ContractLineageStatusV1";
  "supersedes_revision"?: number | null;
  "support_status": "SUPPORTED" | "DECLINED";
};

export type ContractSupportDecisionV1 = {
  "decline_reasons": "MISSING_JURISDICTION" | "MISSING_LANGUAGE" | "MISSING_CONTRACT_TYPE" | "MISSING_ROLE" | "UNSUPPORTED_JURISDICTION" | "UNSUPPORTED_LANGUAGE" | "UNSUPPORTED_CONTRACT_TYPE" | "CAPABILITY_NOT_ACTIVATED" | "UNKNOWN_SCOPE"[];
  "evaluated_at": string;
  "mission_contract_id": string;
  "revision": number;
  "schema_version"?: "ContractSupportDecisionV1";
  "support_status": "SUPPORTED" | "DECLINED";
};

export type CorrectionRecordRequest = {
  "fix"?: string;
  "issue"?: string;
  "severity"?: string;
  "step_id"?: string;
};

export type CreateSwarmRunRequest = {
  "confirmed_edict"?: {
  [key: string]: unknown;
} | null;
  "mode"?: "dry_run" | "standard" | "deep" | "live_swarm";
  "review_id"?: string | null;
  "review_plan"?: {
  [key: string]: unknown;
} | null;
  "task_id": string;
  "trace_id"?: string | null;
};

export type CriticAnalyzeRequest = {
  "qa_result"?: {
  [key: string]: unknown;
};
  "steps_summary"?: string;
  "task_input"?: string;
};

export type CriticAnalyzeResponse = {
  "system_prompt": string;
  "user_prompt": string;
};

export type CurrentUser = {
  "role"?: string | null;
  "tenant_id"?: number | null;
  "tenant_slug"?: string;
  "user_id"?: number | null;
  "username"?: string | null;
};

export type DecisionJudgmentRequest = {
  "helpful": boolean;
  "note"?: string;
  "question": string;
  "taskId"?: string | null;
  "verdict"?: string | null;
};

export type DecisionRequest = {
  "action": "approve" | "archive" | "adopt" | "reject" | "request_evidence" | "recheck" | "followup";
  "followup_question"?: string | null;
  "human_confirmation_note"?: string | null;
  "human_confirmed"?: boolean;
  "reason"?: string;
};

export type DeptFlowsRequest = {
  "flow_ids"?: string[];
};

export type DeptInfo = {
  "created_at"?: string | null;
  "id": number;
  "name": string;
};

export type DeptNameRequest = {
  "name": string;
};

export type DeptRef = {
  "id": number;
  "name": string;
};

export type DigestResponse = {
  "archive_id"?: string | null;
  "digest": string;
  "run_id": string;
  "status"?: string;
};

export type DirectCommandRequest = {
  "command": string;
  "mode"?: string;
  "output_format"?: string;
  "save_to_file"?: string | null;
  "swarm_id"?: string | null;
};

export type DispatchRequest = {
  "budget"?: Budget | null;
  "councilAll"?: boolean;
  "intent"?: string;
  "mode"?: "scripted" | "hybrid" | "live" | null;
  "rawCommand": string;
  "selectedCategories"?: CategorySelection[];
  "stakes"?: string;
};

export type DomainExpertise = {
  "domain": string;
  "keywords"?: string[];
};

export type DraftEdictRequest = {
  "archive_matches"?: {
  [key: string]: unknown;
}[];
  "attachments"?: {
  [key: string]: unknown;
}[];
  "evidence_summary"?: {
  [key: string]: unknown;
} | null;
  "raw_question": string;
};

export type DraftRejectRequest = {
  "reason"?: string;
};

export type DraftRequest = {
  "rawCommand": string;
};

export type DraftStats = {
  "approved"?: number;
  "executed"?: number;
  "pending"?: number;
  "rejected"?: number;
  "total"?: number;
};

export type DraftStatusResponse = {
  "draft"?: {
  [key: string]: unknown;
} | null;
  "status": string;
};

export type EdictReturnRequest = {
  "command"?: string | null;
  "edictView"?: {
  [key: string]: unknown;
} | null;
  "finalOutputs"?: {
  [key: string]: unknown;
}[];
  "jiqunTaskId"?: string | null;
  "mode"?: string | null;
  "sessionId"?: string | null;
  "taskId": string;
};

export type EditFinalOutputRequest = {
  "edit_note"?: string;
  "final_output": {
  [key: string]: unknown;
};
};

export type EditFinalOutputResponse = {
  "backup": string;
  "fields_saved": number;
  "run_id": string;
  "status"?: string;
};

export type FeatureFlagUpdateRequest = {
  "description"?: string;
  "enabled"?: boolean;
  "roll_percentage"?: number;
};

export type FeedbackSaveResponse = {
  "run_id": string;
  "status"?: string;
};

export type FinanceIntelLoopCompleteRequest = {
  "edictMode"?: "public" | "secret";
  "executionType"?: string;
  "market"?: string;
  "question": string;
  "sourceUrls"?: string[];
  "ticker": string;
};

export type FinanceReportingLoopRequest = {
  "command": string;
  "fact_pack"?: {
  [key: string]: unknown;
} | null;
  "mode"?: "order" | "secret";
};

export type FinanceStatusMemorialRequest = {
  "command": string;
  "mode"?: "order" | "secret";
};

export type FlowCreatedResponse = {
  "filename": string;
  "status"?: string;
};

export type FlowCreateRequest = {
  "config": {
  [key: string]: unknown;
};
  "filename": string;
};

export type FlowSummary = {
  "default_model"?: string;
  "filename": string;
  "flow_name": string;
  "qa_version"?: string;
  "steps_count": number;
};

export type FlowUpdateResponse = {
  "backup": string;
  "status"?: string;
};

export type GoldenReviewRequest = {
  "note"?: string;
  "reference"?: string;
  "reviewer"?: string;
};

export type HealthResponse = {
  "checks": {
  [key: string]: string;
};
  "details"?: {
  [key: string]: {
  [key: string]: unknown;
};
};
  "status": string;
  "version"?: string;
};

export type HTTPValidationError = {
  "detail"?: ValidationError[];
};

export type ImMessagePayload = {
  "clientId"?: string | null;
  "id"?: string | null;
  "label"?: string;
  "mode"?: "ask" | "order" | "secret" | null;
  "role": "user" | "assistant";
  "sessionId"?: string | null;
  "text"?: string;
  "time"?: string | null;
};

export type ImPersistRequest = {
  "message": ImMessagePayload;
};

export type KnowledgeSearchResponse = {
  "results": {
  [key: string]: unknown;
}[];
};

export type LipuComplianceRequest = {
  "archive"?: boolean;
  "project_id"?: string | null;
  "task_input": string;
};

export type LocalAIAskRequest = {
  "query": string;
  "review"?: boolean;
};

export type LoginRequest = {
  "password": string;
  "username": string;
};

export type LoginResponse = {
  "landing_mode"?: string;
  "post_login_redirect"?: string;
  "tenant": TenantBrief;
  "token": string;
  "user": UserBrief;
};

export type MemorialsListResponse = {
  "items": {
  [key: string]: unknown;
}[];
  "total": number;
};

export type MemoryCreateRequest = {
  "content": string;
  "description"?: string;
  "name": string;
  "tags"?: string[];
  "type"?: string;
};

export type MemoryHeaderItem = {
  "created_at"?: string;
  "description"?: string;
  "filename": string;
  "name": string;
  "tags"?: string[];
  "type": string;
  "updated_at"?: string;
  "updated_at_hint"?: string;
};

export type MemorySearchRequest = {
  "query"?: string;
  "type"?: string | null;
};

export type MemoryUpdateRequest = {
  "content"?: string | null;
  "description"?: string | null;
  "tags"?: string[] | null;
};

export type MetricEventRequest = {
  "domain"?: string | null;
  "durationMs"?: number | null;
  "name": string;
  "reason"?: string | null;
  "route"?: string | null;
  "taskId"?: string | null;
  "ts"?: number | null;
};

export type MissionConfirmRequest = {
  "content_digest": string;
  "revision": number;
};

export type MissionContractV1 = {
  "constraints": string[];
  "content_digest": string;
  "contract_type": "procurement" | "sales" | "service" | "UNSUPPORTED_OR_UNKNOWN";
  "created_at": string;
  "desired_outcome": MissionOutcome;
  "goal": MissionGoal;
  "jurisdiction": "CN_MAINLAND" | "UNSUPPORTED_OR_UNKNOWN";
  "language": "zh-CN" | "UNSUPPORTED_OR_UNKNOWN";
  "mission_contract_id": string;
  "our_role": "buyer" | "seller" | "service_provider" | "other_party" | "UNSUPPORTED_OR_UNKNOWN";
  "prohibited_actions": string[];
  "revision": number;
  "schema_version"?: "MissionContractV1";
  "task_id": string;
};

export type MissionGoal = {
  "biggest_concern": string;
  "risk_tolerance"?: string;
  "user_intent": string;
};

export type MissionOutcome = {
  "required_artifacts": "PDF" | "DOCX" | "JSON"[];
};

export type OkResponse = {
  "ok"?: boolean;
};

export type OpenClawReplyRequest = {
  "message": string;
};

export type OptimizeApplyRequest = {
  "author"?: string;
  "from_step"?: number;
  "suggestion_indices"?: number[];
};

export type OrchestrationRunRequest = {
  "command": string;
};

export type OverviewMetrics = {
  "activeProjects"?: number;
  "asOf"?: string;
  "avgQualityScore"?: number;
  "cashflow"?: number | null;
  "opportunityCount"?: number;
  "passRate"?: number;
  "pendingApprovals"?: number;
  "revenue"?: number | null;
  "riskCount"?: number;
};

export type OverviewResponse = {
  "generatedAt": string;
  "memorialsToday": {
  [key: string]: unknown;
}[];
  "metrics": OverviewMetrics;
  "ministers": {
  [key: string]: unknown;
}[];
  "risks": {
  [key: string]: unknown;
}[];
  "systemStatus": SystemStatus;
};

export type PackSwarmLoopRequest = {
  "command": string;
  "mode"?: "order" | "secret";
  "source_urls"?: string[];
};

export type PatchTaskRequest = {
  "at"?: string | null;
  "command"?: string | null;
  "mode"?: string | null;
  "result"?: {
  [key: string]: unknown;
} | null;
  "status"?: string | null;
  "title"?: string | null;
};

export type PersistTaskRequest = {
  "at"?: string | null;
  "command": string;
  "mode"?: string | null;
  "result"?: {
  [key: string]: unknown;
} | null;
  "status"?: string;
  "taskId"?: string | null;
  "title"?: string | null;
};

export type PolishEdictRequest = {
  "mode"?: "order" | "secret";
  "raw_question": string;
};

export type PreferenceUpdateRequest = {
  "avoid_pattern"?: string | null;
  "domain_expertise"?: DomainExpertise[] | null;
  "reason"?: string;
  "style_preferences"?: {
  [key: string]: unknown;
} | null;
};

export type PromptFileSaveRequest = {
  "content"?: string;
};

export type PromptFileSaveResponse = {
  "filename": string;
  "key": string;
  "length": number;
  "status"?: string;
};

export type PromptFilesResponse = {
  "files": {
  [key: string]: string;
};
  "key": string;
};

export type PromptGroupedAgent = {
  "display_name": string;
  "key": string;
};

export type PromptGroupedResponse = {
  "swarms": PromptGroupedSwarm[];
  "ungrouped": PromptGroupedAgent[];
};

export type PromptGroupedSwarm = {
  "agents": PromptGroupedAgent[];
  "id": string;
  "name": string;
};

export type PromptProposalActionResponse = {
  "filename": string;
  "key": string;
  "status": string;
};

export type PromptSuggestRequest = {
  "input": string;
};

export type PromptUpdateRequest = {
  "author"?: string;
  "content": string;
  "reason"?: string;
};

export type PromptUpdateResponse = {
  "current_content_length": number;
  "key": string;
  "new_version": string;
  "status"?: string;
  "versions_count": number;
};

export type PromptUpgradesResponse = {
  "proposals": unknown[];
};

export type ProposalCreateRequest = {
  "options"?: {
  [key: string]: unknown;
}[];
  "proposal_id": string;
  "proposer"?: string;
  "quorum"?: number;
  "strategy"?: string;
  "topic": string;
};

export type QintianChatRequest = {
  "message": string;
  "scenarioContext"?: {
  [key: string]: unknown;
} | null;
};

export type ReceiptRequest = {
  "note"?: string;
  "outcome": string;
  "source": string;
};

export type RegisterResponse = {
  "message": string;
  "user_id": number;
  "username": string;
};

export type RepairRequest = {
  "config"?: string | null;
  "max_retries"?: number;
  "min_delta"?: number;
  "min_dimension_score"?: number;
  "min_score"?: number;
};

export type RequirementItem = {
  "content"?: string;
  "created_at"?: string;
  "flow_name"?: string;
  "id": string;
  "run_id"?: string;
  "title"?: string;
};

export type RequirementSaveRequest = {
  "content": string;
  "flow_name"?: string;
  "run_id"?: string;
  "title"?: string | null;
};

export type RequirementSaveResponse = {
  "id": string;
  "title": string;
};

export type RerunRequest = {
  "from_step"?: number;
  "step_id"?: string | null;
  "step_overrides"?: {
  [key: string]: unknown;
} | null;
};

export type RerunResponse = {
  "from_step": number;
  "new_run_id": string;
  "original_run_id": string;
  "step_id"?: string | null;
};

export type ResearchBudgetLoopRequest = {
  "budgetPeriod"?: string;
  "currency"?: string;
  "department"?: string;
  "evidenceRefs"?: {
  [key: string]: unknown;
}[];
  "lineItems"?: {
  [key: string]: unknown;
}[];
  "owner"?: string;
  "purpose"?: string;
  "requestedAmount"?: number;
  "riskThresholdAmount"?: number;
  "sacredEdict": string;
};

export type ResourceProfileUpdateRequest = {
  "mode": string;
};

export type ReviewRequest = {
  "action": "approve" | "reject" | "inquire";
  "comment"?: string;
};

export type RunAsyncRequest = {
  "config"?: string;
  "execution_modes"?: {
  [key: string]: string;
} | null;
  "qa_version"?: string | null;
  "swarm"?: string | boolean | null;
  "task_input": string;
};

export type RunFlowRequest = {
  "config": string;
  "provider"?: string | null;
  "task_input": string;
};

export type RunFlowResponse = {
  "config": string;
  "run_id_prefix": string;
  "status"?: string;
  "task_input": string;
};

export type SerialLoopRequest = {
  "confirmed_edict"?: {
  [key: string]: unknown;
} | null;
  "departments"?: string[];
  "mode"?: "dry_run" | "standard" | "deep" | "live_swarm";
  "review_id"?: string | null;
  "task_id": string;
  "trace_id"?: string | null;
};

export type StatusResponse = {
  "status": string;
};

export type StudyRunRequest = {
  "asyncRun"?: boolean;
  "command": string;
  "entrySwarm"?: string | null;
  "idempotencyKey"?: string | null;
  "mode"?: "dry_run" | "live";
  "provider"?: string | null;
  "taskId"?: string | null;
};

export type SuggestFlowRequest = {
  "task_input"?: string;
};

export type SwarmConfigBinding = {
  "enabled": boolean;
  "min_quality_score": number;
  "target_swarm": string;
  "topic": string;
  "transform": string;
};

export type SwarmConfigResponse = {
  "bindings": SwarmConfigBinding[];
  "swarms": SwarmConfigSwarm[];
};

export type SwarmConfigSwarm = {
  "config": string;
  "id": string;
  "name": string;
  "qa_version": string;
};

export type SwarmRosterItem = {
  "group"?: string;
  "id": string;
  "last_quality_score"?: number | null;
  "last_run_at"?: string | null;
  "last_run_id"?: string | null;
  "latest_title"?: string | null;
  "name": string;
  "source_label"?: string;
  "status"?: string;
};

export type SwarmRunRequest = {
  "config_path"?: string;
  "courtos_departments"?: string[];
  "courtos_edict_mode"?: string | null;
  "courtos_loop_trace_id"?: string | null;
  "courtos_swarm_bundles"?: string[];
  "courtos_task_id"?: string | null;
  "courtos_user_id"?: string | null;
  "entry_swarm"?: string | null;
  "evidence_bound_run"?: {
  [key: string]: unknown;
} | null;
  "evidence_refs"?: string[];
  "forbidden_outputs"?: string[];
  "intelligence_pack"?: {
  [key: string]: unknown;
} | null;
  "intelligence_pack_id"?: string | null;
  "missing_evidence"?: string[];
  "privacy_mode"?: string | null;
  "project_id"?: string | null;
  "provider"?: string | null;
  "source_label"?: string | null;
  "task_input": string;
};

export type SwarmRunResponse = {
  "entry_swarm"?: string | null;
  "message"?: string;
  "route_matched"?: boolean | null;
  "route_reason"?: string | null;
  "session_id": string;
  "success"?: boolean;
};

export type SwarmSessionSummary = {
  "completed_count"?: number;
  "duration"?: string;
  "end_time"?: string;
  "release_gate"?: string;
  "session_id": string;
  "session_type"?: string;
  "start_time"?: string;
  "status"?: string;
  "swarm_count"?: number;
  "synthetic"?: boolean;
  "task_input"?: string;
};

export type SystemStatus = {
  "knowledge"?: string;
  "litellm"?: string;
  "overall"?: string;
};

export type TaskAcceptedResponse = {
  "session_id"?: string | null;
  "status"?: string;
  "task_id": string;
};

export type TaskMonitorEntry = {
  "completed_steps"?: number;
  "config"?: string | null;
  "current_step"?: number | null;
  "current_step_name"?: string | null;
  "elapsed_seconds"?: number | null;
  "error"?: string | null;
  "finished_at"?: string | null;
  "flow_name"?: string | null;
  "run_id"?: string | null;
  "started_at"?: string | null;
  "status"?: string | null;
  "step_names"?: string[];
  "task_id": string;
  "task_input"?: string;
  "total_steps"?: number | null;
};

export type TaskProtocolPreviewRequest = {
  "task": string;
};

export type TasksSnapshot = {
  "recent": TaskMonitorEntry[];
  "running": TaskMonitorEntry[];
};

export type TaskStatusResponse = {
  "error"?: string | null;
  "run_id"?: string | null;
  "status": string;
  "task_id": string;
};

export type TenantBrief = {
  "id": number;
  "name": string;
  "slug": string;
};

export type TenantCreatedResponse = {
  "status"?: string;
  "tenant_id": number;
};

export type TenantCreateRequest = {
  "name": string;
  "slug": string;
};

export type TenantInfo = {
  "created_at": string;
  "id": number;
  "name": string;
  "slug": string;
};

export type TestStepRequest = {
  "config": string;
  "context_run_id"?: string | null;
  "step_id": string;
  "test_input": string;
};

export type ToolDescription = {
  "capabilities"?: {
  [key: string]: string;
};
  "description"?: string;
};

export type TransferRequest = {
  "reason"?: string;
  "target_department": string;
};

export type TransferResponse = {
  "created_at": string;
  "operator"?: string;
  "reason": string;
  "source_flow"?: string;
  "source_run_id": string;
  "status"?: string;
  "target_department": string;
  "task_input_excerpt"?: string;
  "transfer_id": string;
};

export type UserBrief = {
  "display_name"?: string;
  "id": number;
  "role"?: string;
  "username": string;
};

export type UserCreatedResponse = {
  "status"?: string;
  "user_id": number;
};

export type UserCreateRequest = {
  "display_name"?: string;
  "password": string;
  "role"?: string;
  "tenant_id": number;
  "username": string;
};

export type UserDeptsRequest = {
  "dept_ids"?: number[];
};

export type UserInfo = {
  "display_name"?: string;
  "id": number;
  "role": string;
  "tenant_name": string;
  "username": string;
};

export type ValidationError = {
  "ctx"?: Record<string, unknown>;
  "input"?: unknown;
  "loc": string | number[];
  "msg": string;
  "type": string;
};

export type VerifyInviteRequest = {
  "code"?: string;
};

export type VerifyInviteResponse = {
  "message"?: string;
  "valid": boolean;
};

export type VoiceAction = {
  "draft_id"?: string | null;
  "params"?: {
  [key: string]: unknown;
};
  "result"?: {
  [key: string]: unknown;
} | unknown[] | string;
  "status"?: string | null;
  "tool"?: string;
  "type": string;
};

export type VoiceProcessResponse = {
  "actions"?: VoiceAction[];
  "caller_phone"?: string;
  "duration_ms"?: number;
  "error"?: string | null;
  "mode"?: string;
  "output"?: {
  [key: string]: unknown;
};
  "run_id"?: string;
  "status": string;
};

export type VoiceSession = {
  "created_at"?: string;
  "run_id": string;
  "status"?: string;
  "step_count"?: number;
};

export type VoiceSessionsResponse = {
  "error"?: string | null;
  "sessions": VoiceSession[];
};

export type VoteRequest = {
  "option_id": string;
  "reason"?: string;
  "voter": string;
};

export type VoteResult = {
  "accepted": boolean;
};

export type web__routers__court__RegisterRequest = {
  "at"?: string;
  "doc": {
  [key: string]: unknown;
};
  "si"?: string;
};

export type web__routers__direct__FeedbackRequest = {
  "command": string;
  "comment"?: string | null;
  "corrected_mode"?: string | null;
  "corrected_target"?: string | null;
  "mode": string;
  "rating": string;
  "target": string;
  "task_id": string;
};

export type web__schemas__auth__RegisterRequest = {
  "email": string;
  "invite_code": string;
  "password": string;
  "username": string;
};

export type web__schemas__runs__FeedbackRequest = {
  "comment"?: string;
  "dimension_ratings"?: {
  [key: string]: number;
};
  "rating"?: number | string | null;
  "tags"?: string[];
  "thumb"?: string | null;
};

export interface BackendApiRoutes {
  "DELETE /api/admin/depts/{dept_id}": { method: "DELETE"; path: "/api/admin/depts/{dept_id}"; requestBody: unknown; responses: {"204":"unknown","422":"#/components/schemas/HTTPValidationError"} };
  "DELETE /api/chat/sessions/{session_id}": { method: "DELETE"; path: "/api/chat/sessions/{session_id}"; requestBody: unknown; responses: {"200":"#/components/schemas/StatusResponse","422":"#/components/schemas/HTTPValidationError"} };
  "DELETE /api/memory/{filename}": { method: "DELETE"; path: "/api/memory/{filename}"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/ab-tests": { method: "GET"; path: "/api/ab-tests"; requestBody: unknown; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/ab-tests/{test_id}": { method: "GET"; path: "/api/ab-tests/{test_id}"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/admin/depts": { method: "GET"; path: "/api/admin/depts"; requestBody: unknown; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/admin/depts/{dept_id}/flows": { method: "GET"; path: "/api/admin/depts/{dept_id}/flows"; requestBody: unknown; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/admin/flows": { method: "GET"; path: "/api/admin/flows"; requestBody: unknown; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/admin/tenants": { method: "GET"; path: "/api/admin/tenants"; requestBody: unknown; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/admin/users": { method: "GET"; path: "/api/admin/users"; requestBody: unknown; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/admin/users/{user_id}/depts": { method: "GET"; path: "/api/admin/users/{user_id}/depts"; requestBody: unknown; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/agents/discover": { method: "GET"; path: "/api/agents/discover"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/agents/registry": { method: "GET"; path: "/api/agents/registry"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/analytics": { method: "GET"; path: "/api/analytics"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/approval/pending": { method: "GET"; path: "/api/approval/pending"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/auth/me": { method: "GET"; path: "/api/auth/me"; requestBody: unknown; responses: {"200":"#/components/schemas/AuthMeResponse","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/build-ledger": { method: "GET"; path: "/api/build-ledger"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/cases/approved": { method: "GET"; path: "/api/cases/approved"; requestBody: unknown; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/cases/pending": { method: "GET"; path: "/api/cases/pending"; requestBody: unknown; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/cases/receipts/pending": { method: "GET"; path: "/api/cases/receipts/pending"; requestBody: unknown; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/chaotang/archive": { method: "GET"; path: "/api/chaotang/archive"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/chaotang/archive/{task_id}/retrospective": { method: "GET"; path: "/api/chaotang/archive/{task_id}/retrospective"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/chaotang/archive/knowledge/count": { method: "GET"; path: "/api/chaotang/archive/knowledge/count"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/chaotang/archive/search": { method: "GET"; path: "/api/chaotang/archive/search"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/chaotang/department-system": { method: "GET"; path: "/api/chaotang/department-system"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/chaotang/dept/{code}/overview": { method: "GET"; path: "/api/chaotang/dept/{code}/overview"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/chaotang/launch-loop/cases": { method: "GET"; path: "/api/chaotang/launch-loop/cases"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/chaotang/manor/ai-advice": { method: "GET"; path: "/api/chaotang/manor/ai-advice"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/chaotang/manor/groups": { method: "GET"; path: "/api/chaotang/manor/groups"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/chaotang/manor/groups/{groupId}/subagents": { method: "GET"; path: "/api/chaotang/manor/groups/{groupId}/subagents"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/chaotang/manor/opportunities": { method: "GET"; path: "/api/chaotang/manor/opportunities"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/chaotang/manor/overview": { method: "GET"; path: "/api/chaotang/manor/overview"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/chaotang/manor/policy-funds": { method: "GET"; path: "/api/chaotang/manor/policy-funds"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/chaotang/manor/projects": { method: "GET"; path: "/api/chaotang/manor/projects"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/chaotang/manor/supply-chain": { method: "GET"; path: "/api/chaotang/manor/supply-chain"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/chaotang/memorials": { method: "GET"; path: "/api/chaotang/memorials"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/chaotang/memorials/{run_id}": { method: "GET"; path: "/api/chaotang/memorials/{run_id}"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/chaotang/stream/{task_id}": { method: "GET"; path: "/api/chaotang/stream/{task_id}"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/chaotang/study/briefing": { method: "GET"; path: "/api/chaotang/study/briefing"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/chaotang/system/status": { method: "GET"; path: "/api/chaotang/system/status"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/chaotang/tasks": { method: "GET"; path: "/api/chaotang/tasks"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/chaotang/tasks/{task_id}": { method: "GET"; path: "/api/chaotang/tasks/{task_id}"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/chaotang/throne/overview": { method: "GET"; path: "/api/chaotang/throne/overview"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/chat/sessions": { method: "GET"; path: "/api/chat/sessions"; requestBody: unknown; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/chat/sessions/{session_id}": { method: "GET"; path: "/api/chat/sessions/{session_id}"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/commercial-loop/dashboard": { method: "GET"; path: "/api/commercial-loop/dashboard"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/compare": { method: "GET"; path: "/api/compare"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/compare/export": { method: "GET"; path: "/api/compare/export"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/compare/quality": { method: "GET"; path: "/api/compare/quality"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/court-session/latest": { method: "GET"; path: "/api/court-session/latest"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/court/backend/tasks/{task_id}": { method: "GET"; path: "/api/court/backend/tasks/{task_id}"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/court/build-ledger": { method: "GET"; path: "/api/court/build-ledger"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/court/chancellor-advice": { method: "GET"; path: "/api/court/chancellor-advice"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/court/dadian/feed": { method: "GET"; path: "/api/court/dadian/feed"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/court/dadian/pulse": { method: "GET"; path: "/api/court/dadian/pulse"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/court/decision-judgment": { method: "GET"; path: "/api/court/decision-judgment"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/court/dept/gong-bu/feasibility/result": { method: "GET"; path: "/api/court/dept/gong-bu/feasibility/result"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/court/dept/li-bu/recruit/result": { method: "GET"; path: "/api/court/dept/li-bu/recruit/result"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/court/forecast": { method: "GET"; path: "/api/court/forecast"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/court/grand-council/live": { method: "GET"; path: "/api/court/grand-council/live"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/court/ima-knowledge": { method: "GET"; path: "/api/court/ima-knowledge"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/court/intel": { method: "GET"; path: "/api/court/intel"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/court/intel/signals": { method: "GET"; path: "/api/court/intel/signals"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/court/learning/advisor-signal": { method: "GET"; path: "/api/court/learning/advisor-signal"; requestBody: unknown; responses: {"200":"object"} };
  "GET /api/court/learning/backtest": { method: "GET"; path: "/api/court/learning/backtest"; requestBody: unknown; responses: {"200":"object"} };
  "GET /api/court/learning/records": { method: "GET"; path: "/api/court/learning/records"; requestBody: unknown; responses: {"200":"object"} };
  "GET /api/court/pending": { method: "GET"; path: "/api/court/pending"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/court/shiguan/archives": { method: "GET"; path: "/api/court/shiguan/archives"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/court/shiguan/archives/{archive_id}": { method: "GET"; path: "/api/court/shiguan/archives/{archive_id}"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/court/shiguan/archives/{archive_id}/similar": { method: "GET"; path: "/api/court/shiguan/archives/{archive_id}/similar"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/court/shiguan/promo-archive": { method: "GET"; path: "/api/court/shiguan/promo-archive"; requestBody: unknown; responses: {"200":"object"} };
  "GET /api/court/shiguan/release-gates": { method: "GET"; path: "/api/court/shiguan/release-gates"; requestBody: unknown; responses: {"200":"object"} };
  "GET /api/court/shiguan/stats": { method: "GET"; path: "/api/court/shiguan/stats"; requestBody: unknown; responses: {"200":"object"} };
  "GET /api/court/si/{dept}": { method: "GET"; path: "/api/court/si/{dept}"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/court/si/{dept}/{si}": { method: "GET"; path: "/api/court/si/{dept}/{si}"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/court/state/{doc_id}": { method: "GET"; path: "/api/court/state/{doc_id}"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/court/taiyi/dashboard": { method: "GET"; path: "/api/court/taiyi/dashboard"; requestBody: unknown; responses: {"200":"object"} };
  "GET /api/court/taiyi/news": { method: "GET"; path: "/api/court/taiyi/news"; requestBody: unknown; responses: {"200":"object"} };
  "GET /api/court/true-chain-health": { method: "GET"; path: "/api/court/true-chain-health"; requestBody: unknown; responses: {"200":"object"} };
  "GET /api/court/zhuangyuan/ministry-metrics": { method: "GET"; path: "/api/court/zhuangyuan/ministry-metrics"; requestBody: unknown; responses: {"200":"object"} };
  "GET /api/critic/run/{run_id}": { method: "GET"; path: "/api/critic/run/{run_id}"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/direct/explain": { method: "GET"; path: "/api/direct/explain"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/direct/health": { method: "GET"; path: "/api/direct/health"; requestBody: unknown; responses: {"200":"object"} };
  "GET /api/direct/health/live": { method: "GET"; path: "/api/direct/health/live"; requestBody: unknown; responses: {"200":"object"} };
  "GET /api/direct/health/ready": { method: "GET"; path: "/api/direct/health/ready"; requestBody: unknown; responses: {"200":"object"} };
  "GET /api/direct/limits/status": { method: "GET"; path: "/api/direct/limits/status"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/direct/metrics": { method: "GET"; path: "/api/direct/metrics"; requestBody: unknown; responses: {"200":"object"} };
  "GET /api/direct/profiles": { method: "GET"; path: "/api/direct/profiles"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/direct/stats": { method: "GET"; path: "/api/direct/stats"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/drafts": { method: "GET"; path: "/api/drafts"; requestBody: unknown; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/drafts/{draft_id}": { method: "GET"; path: "/api/drafts/{draft_id}"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/drafts/stats": { method: "GET"; path: "/api/drafts/stats"; requestBody: unknown; responses: {"200":"#/components/schemas/DraftStats","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/feature-flags": { method: "GET"; path: "/api/feature-flags"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/feedback": { method: "GET"; path: "/api/feedback"; requestBody: unknown; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/flows": { method: "GET"; path: "/api/flows"; requestBody: unknown; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/flows/{filename}": { method: "GET"; path: "/api/flows/{filename}"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/governance/audit/summary": { method: "GET"; path: "/api/governance/audit/summary"; requestBody: unknown; responses: {"200":"object"} };
  "GET /api/governance/bills": { method: "GET"; path: "/api/governance/bills"; requestBody: unknown; responses: {"200":"object"} };
  "GET /api/governance/bills/{bill_id}/audit": { method: "GET"; path: "/api/governance/bills/{bill_id}/audit"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/governance/whoami": { method: "GET"; path: "/api/governance/whoami"; requestBody: unknown; responses: {"200":"object"} };
  "GET /api/guoli/overview": { method: "GET"; path: "/api/guoli/overview"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/hanlin/awards": { method: "GET"; path: "/api/hanlin/awards"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/hanlin/contributions": { method: "GET"; path: "/api/hanlin/contributions"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/hanlin/experiments": { method: "GET"; path: "/api/hanlin/experiments"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/hanlin/export-offerings": { method: "GET"; path: "/api/hanlin/export-offerings"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/hanlin/incubation": { method: "GET"; path: "/api/hanlin/incubation"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/hanlin/overview": { method: "GET"; path: "/api/hanlin/overview"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/hanlin/recommendations": { method: "GET"; path: "/api/hanlin/recommendations"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/hanlin/reset-demo": { method: "GET"; path: "/api/hanlin/reset-demo"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/hanlin/reviews": { method: "GET"; path: "/api/hanlin/reviews"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/hanlin/scouting": { method: "GET"; path: "/api/hanlin/scouting"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/hanlin/scouting/{candidate_id}": { method: "GET"; path: "/api/hanlin/scouting/{candidate_id}"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/hanlin/summary": { method: "GET"; path: "/api/hanlin/summary"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/health": { method: "GET"; path: "/api/health"; requestBody: unknown; responses: {"200":"#/components/schemas/HealthResponse"} };
  "GET /api/intel/evidence": { method: "GET"; path: "/api/intel/evidence"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/knowledge/health": { method: "GET"; path: "/api/knowledge/health"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/knowledge/search": { method: "GET"; path: "/api/knowledge/search"; requestBody: unknown; responses: {"200":"#/components/schemas/KnowledgeSearchResponse","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/knowledge/sources": { method: "GET"; path: "/api/knowledge/sources"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/knowledge/stats": { method: "GET"; path: "/api/knowledge/stats"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/kpi/business": { method: "GET"; path: "/api/kpi/business"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/kpi/calibration/stats": { method: "GET"; path: "/api/kpi/calibration/stats"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/kpi/latency": { method: "GET"; path: "/api/kpi/latency"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/kpi/regression": { method: "GET"; path: "/api/kpi/regression"; requestBody: unknown; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/kpi/slo": { method: "GET"; path: "/api/kpi/slo"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/legal/overview": { method: "GET"; path: "/api/legal/overview"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/local-ai/audit-courtos-brain": { method: "GET"; path: "/api/local-ai/audit-courtos-brain"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/local-ai/status": { method: "GET"; path: "/api/local-ai/status"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/memory": { method: "GET"; path: "/api/memory"; requestBody: unknown; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/memory/{filename}": { method: "GET"; path: "/api/memory/{filename}"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/memory/stats": { method: "GET"; path: "/api/memory/stats"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/metrics/tokens": { method: "GET"; path: "/api/metrics/tokens"; requestBody: unknown; responses: {"200":"object"} };
  "GET /api/models": { method: "GET"; path: "/api/models"; requestBody: unknown; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/observability/events": { method: "GET"; path: "/api/observability/events"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/observability/release-gate": { method: "GET"; path: "/api/observability/release-gate"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/observability/summary": { method: "GET"; path: "/api/observability/summary"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/preferences/{user_id}": { method: "GET"; path: "/api/preferences/{user_id}"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/preflight": { method: "GET"; path: "/api/preflight"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/presets": { method: "GET"; path: "/api/presets"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/prompts": { method: "GET"; path: "/api/prompts"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/prompts/{key}": { method: "GET"; path: "/api/prompts/{key}"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/prompts/{key}/files": { method: "GET"; path: "/api/prompts/{key}/files"; requestBody: unknown; responses: {"200":"#/components/schemas/PromptFilesResponse","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/prompts/{key}/versions": { method: "GET"; path: "/api/prompts/{key}/versions"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/prompts/grouped": { method: "GET"; path: "/api/prompts/grouped"; requestBody: unknown; responses: {"200":"#/components/schemas/PromptGroupedResponse","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/prompts/upgrades": { method: "GET"; path: "/api/prompts/upgrades"; requestBody: unknown; responses: {"200":"#/components/schemas/PromptUpgradesResponse","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/qintian/learning-path": { method: "GET"; path: "/api/qintian/learning-path"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/qintian/scenarios": { method: "GET"; path: "/api/qintian/scenarios"; requestBody: unknown; responses: {"200":"object"} };
  "GET /api/qintianjian/triggers/pending": { method: "GET"; path: "/api/qintianjian/triggers/pending"; requestBody: unknown; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/ready": { method: "GET"; path: "/api/ready"; requestBody: unknown; responses: {"200":"object"} };
  "GET /api/repair-insights": { method: "GET"; path: "/api/repair-insights"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/repairs": { method: "GET"; path: "/api/repairs"; requestBody: unknown; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/repairs/{session_id}": { method: "GET"; path: "/api/repairs/{session_id}"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/requirements": { method: "GET"; path: "/api/requirements"; requestBody: unknown; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/requirements/{req_id}": { method: "GET"; path: "/api/requirements/{req_id}"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/resources/profile": { method: "GET"; path: "/api/resources/profile"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/runs": { method: "GET"; path: "/api/runs"; requestBody: unknown; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/runs/{run_id}": { method: "GET"; path: "/api/runs/{run_id}"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/runs/{run_id}/export/final": { method: "GET"; path: "/api/runs/{run_id}/export/final"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/runs/{run_id}/feedback": { method: "GET"; path: "/api/runs/{run_id}/feedback"; requestBody: unknown; responses: {"200":"anyOf:object|null","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/runs/{run_id}/optimize/trigger": { method: "GET"; path: "/api/runs/{run_id}/optimize/trigger"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/runs/{run_id}/quality": { method: "GET"; path: "/api/runs/{run_id}/quality"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/runs/{run_id}/report": { method: "GET"; path: "/api/runs/{run_id}/report"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/runs/{run_id}/steps/{step_index}": { method: "GET"; path: "/api/runs/{run_id}/steps/{step_index}"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/runs/{run_id}/steps/{step_index}/export/output": { method: "GET"; path: "/api/runs/{run_id}/steps/{step_index}/export/output"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/runs/{run_id}/steps/{step_index}/export/prompt": { method: "GET"; path: "/api/runs/{run_id}/steps/{step_index}/export/prompt"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/runs/stream/{task_id}": { method: "GET"; path: "/api/runs/stream/{task_id}"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/runs/stream/{task_id}/status": { method: "GET"; path: "/api/runs/stream/{task_id}/status"; requestBody: unknown; responses: {"200":"#/components/schemas/TaskStatusResponse","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/scribe/archive-docs": { method: "GET"; path: "/api/scribe/archive-docs"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/scribe/lessons": { method: "GET"; path: "/api/scribe/lessons"; requestBody: unknown; responses: {"200":"object"} };
  "GET /api/shangshufang/finance-intel-loop/cases/{task_id}": { method: "GET"; path: "/api/shangshufang/finance-intel-loop/cases/{task_id}"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/shangshufang/home": { method: "GET"; path: "/api/shangshufang/home"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/shangshufang/im": { method: "GET"; path: "/api/shangshufang/im"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/shangshufang/tasks/{task_id}/status": { method: "GET"; path: "/api/shangshufang/tasks/{task_id}/status"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/swarm-runs/{swarm_run_id}": { method: "GET"; path: "/api/swarm-runs/{swarm_run_id}"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/swarm-runs/{swarm_run_id}/brief": { method: "GET"; path: "/api/swarm-runs/{swarm_run_id}/brief"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/swarm-runs/{swarm_run_id}/progress": { method: "GET"; path: "/api/swarm-runs/{swarm_run_id}/progress"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/swarm/config": { method: "GET"; path: "/api/swarm/config"; requestBody: unknown; responses: {"200":"#/components/schemas/SwarmConfigResponse","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/swarm/projects/{project_id}/quality-report": { method: "GET"; path: "/api/swarm/projects/{project_id}/quality-report"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/swarm/roster": { method: "GET"; path: "/api/swarm/roster"; requestBody: unknown; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/swarm/sessions": { method: "GET"; path: "/api/swarm/sessions"; requestBody: unknown; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/swarm/sessions/{session_id}": { method: "GET"; path: "/api/swarm/sessions/{session_id}"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/swarm/sessions/{session_id}/pack-report": { method: "GET"; path: "/api/swarm/sessions/{session_id}/pack-report"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/swarm/timeline": { method: "GET"; path: "/api/swarm/timeline"; requestBody: unknown; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/tasks": { method: "GET"; path: "/api/tasks"; requestBody: unknown; responses: {"200":"#/components/schemas/TasksSnapshot","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/tasks/{task_id}/events": { method: "GET"; path: "/api/tasks/{task_id}/events"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/throne/memorials": { method: "GET"; path: "/api/throne/memorials"; requestBody: unknown; responses: {"200":"#/components/schemas/MemorialsListResponse","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/throne/overview": { method: "GET"; path: "/api/throne/overview"; requestBody: unknown; responses: {"200":"#/components/schemas/OverviewResponse","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/throne/runs/{run_id}": { method: "GET"; path: "/api/throne/runs/{run_id}"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/tools": { method: "GET"; path: "/api/tools"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/voice/health": { method: "GET"; path: "/api/voice/health"; requestBody: unknown; responses: {"200":"#/components/schemas/StatusResponse"} };
  "GET /api/voice/sessions": { method: "GET"; path: "/api/voice/sessions"; requestBody: unknown; responses: {"200":"#/components/schemas/VoiceSessionsResponse","422":"#/components/schemas/HTTPValidationError"} };
  "GET /api/votes/proposals": { method: "GET"; path: "/api/votes/proposals"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "PATCH /api/chaotang/tasks/{task_id}/persist": { method: "PATCH"; path: "/api/chaotang/tasks/{task_id}/persist"; requestBody: "#/components/schemas/PatchTaskRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "PATCH /api/court/ima-knowledge": { method: "PATCH"; path: "/api/court/ima-knowledge"; requestBody: "#/components/schemas/_ImaKnowledgeStatusRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/ab-tests": { method: "POST"; path: "/api/ab-tests"; requestBody: "#/components/schemas/ABTestRequest"; responses: {"201":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/admin/depts": { method: "POST"; path: "/api/admin/depts"; requestBody: "#/components/schemas/DeptNameRequest"; responses: {"201":"#/components/schemas/DeptInfo","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/admin/tenants": { method: "POST"; path: "/api/admin/tenants"; requestBody: "#/components/schemas/TenantCreateRequest"; responses: {"201":"#/components/schemas/TenantCreatedResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/admin/users": { method: "POST"; path: "/api/admin/users"; requestBody: "#/components/schemas/UserCreateRequest"; responses: {"201":"#/components/schemas/UserCreatedResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/auth/login": { method: "POST"; path: "/api/auth/login"; requestBody: "#/components/schemas/LoginRequest"; responses: {"200":"#/components/schemas/LoginResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/auth/logout": { method: "POST"; path: "/api/auth/logout"; requestBody: unknown; responses: {"200":"#/components/schemas/StatusResponse"} };
  "POST /api/auth/register": { method: "POST"; path: "/api/auth/register"; requestBody: "#/components/schemas/web__schemas__auth__RegisterRequest"; responses: {"201":"#/components/schemas/RegisterResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/auth/verify-invite": { method: "POST"; path: "/api/auth/verify-invite"; requestBody: "#/components/schemas/VerifyInviteRequest"; responses: {"200":"#/components/schemas/VerifyInviteResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/bingbu/battlecard": { method: "POST"; path: "/api/bingbu/battlecard"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/build-ledger": { method: "POST"; path: "/api/build-ledger"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/cases/{filename}/approve": { method: "POST"; path: "/api/cases/{filename}/approve"; requestBody: unknown; responses: {"200":"#/components/schemas/CaseActionResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/cases/{filename}/reject": { method: "POST"; path: "/api/cases/{filename}/reject"; requestBody: "anyOf:#/components/schemas/CaseRejectRequest|null"; responses: {"200":"#/components/schemas/CaseActionResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/cases/receipts": { method: "POST"; path: "/api/cases/receipts"; requestBody: "#/components/schemas/ReceiptRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/chaotang/archive/{task_id}/retrospective": { method: "POST"; path: "/api/chaotang/archive/{task_id}/retrospective"; requestBody: "#/components/schemas/_RetrospectiveRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/chaotang/archive/chronicle": { method: "POST"; path: "/api/chaotang/archive/chronicle"; requestBody: "#/components/schemas/_ChronicleRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/chaotang/archive/knowledge/feedback": { method: "POST"; path: "/api/chaotang/archive/knowledge/feedback"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/chaotang/decree/{task_id}/proceed": { method: "POST"; path: "/api/chaotang/decree/{task_id}/proceed"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/chaotang/decree/dispatch": { method: "POST"; path: "/api/chaotang/decree/dispatch"; requestBody: "#/components/schemas/DispatchRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/chaotang/decree/draft": { method: "POST"; path: "/api/chaotang/decree/draft"; requestBody: "#/components/schemas/DraftRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/chaotang/department-system/route": { method: "POST"; path: "/api/chaotang/department-system/route"; requestBody: "#/components/schemas/_DepartmentRouteRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/chaotang/hubu/cashflow/preview": { method: "POST"; path: "/api/chaotang/hubu/cashflow/preview"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/chaotang/hubu/finance/intake/preview": { method: "POST"; path: "/api/chaotang/hubu/finance/intake/preview"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/chaotang/hubu/finance/reporting/decision/preview": { method: "POST"; path: "/api/chaotang/hubu/finance/reporting/decision/preview"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/chaotang/hubu/finance/reporting/preview": { method: "POST"; path: "/api/chaotang/hubu/finance/reporting/preview"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/chaotang/hubu/payment/decision/preview": { method: "POST"; path: "/api/chaotang/hubu/payment/decision/preview"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/chaotang/hubu/payment/preview": { method: "POST"; path: "/api/chaotang/hubu/payment/preview"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/chaotang/memorials/{run_id}/review": { method: "POST"; path: "/api/chaotang/memorials/{run_id}/review"; requestBody: "#/components/schemas/ReviewRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/chaotang/study/quick-command": { method: "POST"; path: "/api/chaotang/study/quick-command"; requestBody: "#/components/schemas/_QuickCommandRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/chaotang/study/run": { method: "POST"; path: "/api/chaotang/study/run"; requestBody: "#/components/schemas/StudyRunRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/chaotang/study/teaching": { method: "POST"; path: "/api/chaotang/study/teaching"; requestBody: "#/components/schemas/_TeachingRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/chaotang/tasks/persist": { method: "POST"; path: "/api/chaotang/tasks/persist"; requestBody: "#/components/schemas/PersistTaskRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/chaotang/throne/quick-summon": { method: "POST"; path: "/api/chaotang/throne/quick-summon"; requestBody: "#/components/schemas/_QuickSummonRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/chat": { method: "POST"; path: "/api/chat"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/chat/sessions": { method: "POST"; path: "/api/chat/sessions"; requestBody: "#/components/schemas/ChatSessionCreateRequest"; responses: {"201":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/chat/sessions/{session_id}/turns": { method: "POST"; path: "/api/chat/sessions/{session_id}/turns"; requestBody: "#/components/schemas/ChatSessionTurnRequest"; responses: {"200":"#/components/schemas/ChatSessionTurnResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/commercial-loop/golden-candidates/{candidate_id}/promote": { method: "POST"; path: "/api/commercial-loop/golden-candidates/{candidate_id}/promote"; requestBody: "#/components/schemas/GoldenReviewRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/commercial-loop/golden-candidates/{candidate_id}/reject": { method: "POST"; path: "/api/commercial-loop/golden-candidates/{candidate_id}/reject"; requestBody: "anyOf:#/components/schemas/GoldenReviewRequest|null"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/contracts/capability/activate": { method: "POST"; path: "/api/contracts/capability/activate"; requestBody: "#/components/schemas/CapabilityActivationRequest"; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/contracts/decision": { method: "POST"; path: "/api/contracts/decision"; requestBody: "#/components/schemas/ContractDecisionV1"; responses: {"200":"#/components/schemas/ContractDecisionV1","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/contracts/mission/{mission_contract_id}/confirm": { method: "POST"; path: "/api/contracts/mission/{mission_contract_id}/confirm"; requestBody: "#/components/schemas/MissionConfirmRequest"; responses: {"200":"#/components/schemas/ContractLineageStatusV1","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/contracts/mission/draft": { method: "POST"; path: "/api/contracts/mission/draft"; requestBody: "#/components/schemas/MissionContractV1"; responses: {"200":"#/components/schemas/MissionContractV1","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/contracts/support/evaluate": { method: "POST"; path: "/api/contracts/support/evaluate"; requestBody: "#/components/schemas/ContractIntakeV1"; responses: {"200":"#/components/schemas/ContractSupportDecisionV1","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/court/action": { method: "POST"; path: "/api/court/action"; requestBody: "#/components/schemas/ActionRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/court/build-ledger": { method: "POST"; path: "/api/court/build-ledger"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/court/bureaus/{department}/{bureau}/actions": { method: "POST"; path: "/api/court/bureaus/{department}/{bureau}/actions"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/court/decision-judgment": { method: "POST"; path: "/api/court/decision-judgment"; requestBody: "#/components/schemas/DecisionJudgmentRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/court/dept/gong-bu/feasibility": { method: "POST"; path: "/api/court/dept/gong-bu/feasibility"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/court/dept/li-bu/recruit": { method: "POST"; path: "/api/court/dept/li-bu/recruit"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/court/dept/swarm-dispatch": { method: "POST"; path: "/api/court/dept/swarm-dispatch"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/court/hubu/ask": { method: "POST"; path: "/api/court/hubu/ask"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/court/ima-knowledge": { method: "POST"; path: "/api/court/ima-knowledge"; requestBody: "#/components/schemas/_ImaKnowledgeUploadRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/court/intel/signals/{signal_id}/dispatch": { method: "POST"; path: "/api/court/intel/signals/{signal_id}/dispatch"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/court/junjichu/cases": { method: "POST"; path: "/api/court/junjichu/cases"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/court/orchestrate": { method: "POST"; path: "/api/court/orchestrate"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/court/orchestrate/all": { method: "POST"; path: "/api/court/orchestrate/all"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/court/orchestrate/sign-off": { method: "POST"; path: "/api/court/orchestrate/sign-off"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/court/register": { method: "POST"; path: "/api/court/register"; requestBody: "#/components/schemas/web__routers__court__RegisterRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/court/shiguan/analyze": { method: "POST"; path: "/api/court/shiguan/analyze"; requestBody: unknown; responses: {"200":"object"} };
  "POST /api/court/shiguan/archives/{archive_id}/verdict": { method: "POST"; path: "/api/court/shiguan/archives/{archive_id}/verdict"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/critic/analyze": { method: "POST"; path: "/api/critic/analyze"; requestBody: "#/components/schemas/CriticAnalyzeRequest"; responses: {"200":"#/components/schemas/CriticAnalyzeResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/direct/execute": { method: "POST"; path: "/api/direct/execute"; requestBody: "#/components/schemas/DirectCommandRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/direct/feedback": { method: "POST"; path: "/api/direct/feedback"; requestBody: "#/components/schemas/web__routers__direct__FeedbackRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/drafts/{draft_id}/approve": { method: "POST"; path: "/api/drafts/{draft_id}/approve"; requestBody: unknown; responses: {"200":"#/components/schemas/DraftStatusResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/drafts/{draft_id}/execute": { method: "POST"; path: "/api/drafts/{draft_id}/execute"; requestBody: unknown; responses: {"200":"#/components/schemas/DraftStatusResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/drafts/{draft_id}/reject": { method: "POST"; path: "/api/drafts/{draft_id}/reject"; requestBody: "anyOf:#/components/schemas/DraftRejectRequest|null"; responses: {"200":"#/components/schemas/DraftStatusResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/flows": { method: "POST"; path: "/api/flows"; requestBody: "#/components/schemas/FlowCreateRequest"; responses: {"201":"#/components/schemas/FlowCreatedResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/flows/test_step": { method: "POST"; path: "/api/flows/test_step"; requestBody: "#/components/schemas/TestStepRequest"; responses: {"200":"#/components/schemas/TaskAcceptedResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/gongbu/review": { method: "POST"; path: "/api/gongbu/review"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/governance/bills": { method: "POST"; path: "/api/governance/bills"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/governance/bills/{bill_id}/transition": { method: "POST"; path: "/api/governance/bills/{bill_id}/transition"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/governance/deliberate": { method: "POST"; path: "/api/governance/deliberate"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/governance/whoami": { method: "POST"; path: "/api/governance/whoami"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/hanlin/reset-demo": { method: "POST"; path: "/api/hanlin/reset-demo"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/hanlin/scouting/{candidate_id}": { method: "POST"; path: "/api/hanlin/scouting/{candidate_id}"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/intel/brief": { method: "POST"; path: "/api/intel/brief"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/intel/evidence/fill-gap": { method: "POST"; path: "/api/intel/evidence/fill-gap"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/knowledge/index": { method: "POST"; path: "/api/knowledge/index"; requestBody: unknown; responses: {"409":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/knowledge/upload": { method: "POST"; path: "/api/knowledge/upload"; requestBody: unknown; responses: {"409":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/kpi/business/{run_id}": { method: "POST"; path: "/api/kpi/business/{run_id}"; requestBody: "#/components/schemas/BusinessOutcomeRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/kpi/calibration": { method: "POST"; path: "/api/kpi/calibration"; requestBody: "#/components/schemas/CalibrationRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/legal/verdict": { method: "POST"; path: "/api/legal/verdict"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/legal/verdict/from-text": { method: "POST"; path: "/api/legal/verdict/from-text"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/libu/appointment/verdict": { method: "POST"; path: "/api/libu/appointment/verdict"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/libu/recruit/verdict": { method: "POST"; path: "/api/libu/recruit/verdict"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/local-ai/ask": { method: "POST"; path: "/api/local-ai/ask"; requestBody: "#/components/schemas/LocalAIAskRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/local-ai/index-courtos-brain": { method: "POST"; path: "/api/local-ai/index-courtos-brain"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/manor/analyze": { method: "POST"; path: "/api/manor/analyze"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/manor/stream": { method: "POST"; path: "/api/manor/stream"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/memory": { method: "POST"; path: "/api/memory"; requestBody: "#/components/schemas/MemoryCreateRequest"; responses: {"201":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/memory/rebuild-index": { method: "POST"; path: "/api/memory/rebuild-index"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/memory/search": { method: "POST"; path: "/api/memory/search"; requestBody: "#/components/schemas/MemorySearchRequest"; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/metrics": { method: "POST"; path: "/api/metrics"; requestBody: "#/components/schemas/MetricEventRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/orchestration/run": { method: "POST"; path: "/api/orchestration/run"; requestBody: "#/components/schemas/OrchestrationRunRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/preferences/{user_id}": { method: "POST"; path: "/api/preferences/{user_id}"; requestBody: "#/components/schemas/PreferenceUpdateRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/preferences/{user_id}/accepted-designs": { method: "POST"; path: "/api/preferences/{user_id}/accepted-designs"; requestBody: "#/components/schemas/AcceptedDesignRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/preferences/{user_id}/corrections": { method: "POST"; path: "/api/preferences/{user_id}/corrections"; requestBody: "#/components/schemas/CorrectionRecordRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/preferences/{user_id}/suggest-flow": { method: "POST"; path: "/api/preferences/{user_id}/suggest-flow"; requestBody: "#/components/schemas/SuggestFlowRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/prompt/suggest": { method: "POST"; path: "/api/prompt/suggest"; requestBody: "#/components/schemas/PromptSuggestRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/prompts/{key}/files/{filename}/accept": { method: "POST"; path: "/api/prompts/{key}/files/{filename}/accept"; requestBody: unknown; responses: {"200":"#/components/schemas/PromptProposalActionResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/prompts/{key}/files/{filename}/reject": { method: "POST"; path: "/api/prompts/{key}/files/{filename}/reject"; requestBody: unknown; responses: {"200":"#/components/schemas/PromptProposalActionResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/prompts/upgrades/check": { method: "POST"; path: "/api/prompts/upgrades/check"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/qintian/chat": { method: "POST"; path: "/api/qintian/chat"; requestBody: "#/components/schemas/QintianChatRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/qintian/chat-legacy": { method: "POST"; path: "/api/qintian/chat-legacy"; requestBody: "#/components/schemas/QintianChatRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/qintian/scenarios/generate": { method: "POST"; path: "/api/qintian/scenarios/generate"; requestBody: unknown; responses: {"200":"object"} };
  "POST /api/qintianjian/forecast": { method: "POST"; path: "/api/qintianjian/forecast"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/qintianjian/triggers/{trigger_id}/resolve": { method: "POST"; path: "/api/qintianjian/triggers/{trigger_id}/resolve"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/quotation/verdict": { method: "POST"; path: "/api/quotation/verdict"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/requirements/save": { method: "POST"; path: "/api/requirements/save"; requestBody: "#/components/schemas/RequirementSaveRequest"; responses: {"200":"#/components/schemas/RequirementSaveResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/resources/profile": { method: "POST"; path: "/api/resources/profile"; requestBody: "#/components/schemas/ResourceProfileUpdateRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/run": { method: "POST"; path: "/api/run"; requestBody: "#/components/schemas/RunFlowRequest"; responses: {"202":"#/components/schemas/RunFlowResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/runs/{run_id}/feedback": { method: "POST"; path: "/api/runs/{run_id}/feedback"; requestBody: "#/components/schemas/web__schemas__runs__FeedbackRequest"; responses: {"200":"#/components/schemas/FeedbackSaveResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/runs/{run_id}/optimize/apply": { method: "POST"; path: "/api/runs/{run_id}/optimize/apply"; requestBody: "#/components/schemas/OptimizeApplyRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/runs/{run_id}/repair": { method: "POST"; path: "/api/runs/{run_id}/repair"; requestBody: "#/components/schemas/RepairRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/runs/{run_id}/repair/async": { method: "POST"; path: "/api/runs/{run_id}/repair/async"; requestBody: "#/components/schemas/RepairRequest"; responses: {"200":"anyOf:#/components/schemas/TaskAcceptedResponse|object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/runs/{run_id}/rerun": { method: "POST"; path: "/api/runs/{run_id}/rerun"; requestBody: "#/components/schemas/RerunRequest"; responses: {"200":"#/components/schemas/RerunResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/runs/async": { method: "POST"; path: "/api/runs/async"; requestBody: "#/components/schemas/RunAsyncRequest"; responses: {"200":"#/components/schemas/TaskAcceptedResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/runs/stream/{task_id}/approve": { method: "POST"; path: "/api/runs/stream/{task_id}/approve"; requestBody: unknown; responses: {"200":"#/components/schemas/OkResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/runs/stream/{task_id}/openclaw_proceed": { method: "POST"; path: "/api/runs/stream/{task_id}/openclaw_proceed"; requestBody: unknown; responses: {"200":"#/components/schemas/OkResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/runs/stream/{task_id}/openclaw_reply": { method: "POST"; path: "/api/runs/stream/{task_id}/openclaw_reply"; requestBody: "#/components/schemas/OpenClawReplyRequest"; responses: {"200":"#/components/schemas/OkResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/runs/stream/{task_id}/reject": { method: "POST"; path: "/api/runs/stream/{task_id}/reject"; requestBody: unknown; responses: {"200":"#/components/schemas/OkResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/scribe/annals": { method: "POST"; path: "/api/scribe/annals"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/shangshufang/briefs/{brief_id}/decision": { method: "POST"; path: "/api/shangshufang/briefs/{brief_id}/decision"; requestBody: "#/components/schemas/BriefDecisionAdvanceRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/shangshufang/briefs/{brief_id}/decision/advance": { method: "POST"; path: "/api/shangshufang/briefs/{brief_id}/decision/advance"; requestBody: "#/components/schemas/BriefDecisionAdvanceRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/shangshufang/chancellor-chat": { method: "POST"; path: "/api/shangshufang/chancellor-chat"; requestBody: "#/components/schemas/ChancellorChatRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/shangshufang/confirm-edict": { method: "POST"; path: "/api/shangshufang/confirm-edict"; requestBody: "#/components/schemas/ConfirmEdictRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/shangshufang/draft-edict": { method: "POST"; path: "/api/shangshufang/draft-edict"; requestBody: "#/components/schemas/DraftEdictRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/shangshufang/edict-return": { method: "POST"; path: "/api/shangshufang/edict-return"; requestBody: "#/components/schemas/EdictReturnRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/shangshufang/finance-intel-loop/complete": { method: "POST"; path: "/api/shangshufang/finance-intel-loop/complete"; requestBody: "#/components/schemas/FinanceIntelLoopCompleteRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/shangshufang/finance-reporting-loop": { method: "POST"; path: "/api/shangshufang/finance-reporting-loop"; requestBody: "#/components/schemas/FinanceReportingLoopRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/shangshufang/finance-status-memorial": { method: "POST"; path: "/api/shangshufang/finance-status-memorial"; requestBody: "#/components/schemas/FinanceStatusMemorialRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/shangshufang/im": { method: "POST"; path: "/api/shangshufang/im"; requestBody: "#/components/schemas/ImPersistRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/shangshufang/pack-swarm-loop": { method: "POST"; path: "/api/shangshufang/pack-swarm-loop"; requestBody: "#/components/schemas/PackSwarmLoopRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/shangshufang/polish-edict": { method: "POST"; path: "/api/shangshufang/polish-edict"; requestBody: "#/components/schemas/PolishEdictRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/shangshufang/research-budget-loop": { method: "POST"; path: "/api/shangshufang/research-budget-loop"; requestBody: "#/components/schemas/ResearchBudgetLoopRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/shangshufang/tasks/{task_id}/decision": { method: "POST"; path: "/api/shangshufang/tasks/{task_id}/decision"; requestBody: "#/components/schemas/DecisionRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/shangshufang/tasks/{task_id}/swarm-deepen": { method: "POST"; path: "/api/shangshufang/tasks/{task_id}/swarm-deepen"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/shiguan/archives/{archive_id}/retrospective": { method: "POST"; path: "/api/shiguan/archives/{archive_id}/retrospective"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/swarm-runs": { method: "POST"; path: "/api/swarm-runs"; requestBody: "anyOf:#/components/schemas/CreateSwarmRunRequest|null"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/swarm-runs/{swarm_run_id}/retry": { method: "POST"; path: "/api/swarm-runs/{swarm_run_id}/retry"; requestBody: unknown; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/swarm-runs/serial": { method: "POST"; path: "/api/swarm-runs/serial"; requestBody: "anyOf:#/components/schemas/SerialLoopRequest|null"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/swarm/lipu/compliance-report": { method: "POST"; path: "/api/swarm/lipu/compliance-report"; requestBody: "#/components/schemas/LipuComplianceRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/swarm/run": { method: "POST"; path: "/api/swarm/run"; requestBody: "#/components/schemas/SwarmRunRequest"; responses: {"202":"#/components/schemas/SwarmRunResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/task-protocol/preview": { method: "POST"; path: "/api/task-protocol/preview"; requestBody: "#/components/schemas/TaskProtocolPreviewRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/throne/runs/{run_id}/digest": { method: "POST"; path: "/api/throne/runs/{run_id}/digest"; requestBody: unknown; responses: {"200":"#/components/schemas/DigestResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/throne/runs/{run_id}/transfer": { method: "POST"; path: "/api/throne/runs/{run_id}/transfer"; requestBody: "#/components/schemas/TransferRequest"; responses: {"201":"#/components/schemas/TransferResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/voice/process": { method: "POST"; path: "/api/voice/process"; requestBody: unknown; responses: {"200":"#/components/schemas/VoiceProcessResponse","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/votes/proposals": { method: "POST"; path: "/api/votes/proposals"; requestBody: "#/components/schemas/ProposalCreateRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/votes/proposals/{proposal_id}/vote": { method: "POST"; path: "/api/votes/proposals/{proposal_id}/vote"; requestBody: "#/components/schemas/VoteRequest"; responses: {"200":"#/components/schemas/VoteResult","422":"#/components/schemas/HTTPValidationError"} };
  "POST /api/yushi/review": { method: "POST"; path: "/api/yushi/review"; requestBody: "object"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "POST /v1/chat/completions": { method: "POST"; path: "/v1/chat/completions"; requestBody: "#/components/schemas/ChatCompletionRequest"; responses: {"200":"#/components/schemas/ChatCompletionResponse","422":"#/components/schemas/HTTPValidationError"} };
  "PUT /api/admin/depts/{dept_id}": { method: "PUT"; path: "/api/admin/depts/{dept_id}"; requestBody: "#/components/schemas/DeptNameRequest"; responses: {"200":"#/components/schemas/DeptInfo","422":"#/components/schemas/HTTPValidationError"} };
  "PUT /api/admin/depts/{dept_id}/flows": { method: "PUT"; path: "/api/admin/depts/{dept_id}/flows"; requestBody: "#/components/schemas/DeptFlowsRequest"; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "PUT /api/admin/users/{user_id}/depts": { method: "PUT"; path: "/api/admin/users/{user_id}/depts"; requestBody: "#/components/schemas/UserDeptsRequest"; responses: {"200":"array","422":"#/components/schemas/HTTPValidationError"} };
  "PUT /api/feature-flags/{name}": { method: "PUT"; path: "/api/feature-flags/{name}"; requestBody: "#/components/schemas/FeatureFlagUpdateRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "PUT /api/flows/{filename}": { method: "PUT"; path: "/api/flows/{filename}"; requestBody: "object"; responses: {"200":"#/components/schemas/FlowUpdateResponse","422":"#/components/schemas/HTTPValidationError"} };
  "PUT /api/memory/{filename}": { method: "PUT"; path: "/api/memory/{filename}"; requestBody: "#/components/schemas/MemoryUpdateRequest"; responses: {"200":"object","422":"#/components/schemas/HTTPValidationError"} };
  "PUT /api/prompts/{key}": { method: "PUT"; path: "/api/prompts/{key}"; requestBody: "#/components/schemas/PromptUpdateRequest"; responses: {"200":"#/components/schemas/PromptUpdateResponse","422":"#/components/schemas/HTTPValidationError"} };
  "PUT /api/prompts/{key}/files/{filename}": { method: "PUT"; path: "/api/prompts/{key}/files/{filename}"; requestBody: "#/components/schemas/PromptFileSaveRequest"; responses: {"200":"#/components/schemas/PromptFileSaveResponse","422":"#/components/schemas/HTTPValidationError"} };
  "PUT /api/runs/{run_id}/final-output": { method: "PUT"; path: "/api/runs/{run_id}/final-output"; requestBody: "#/components/schemas/EditFinalOutputRequest"; responses: {"200":"#/components/schemas/EditFinalOutputResponse","422":"#/components/schemas/HTTPValidationError"} };
}
